### ISSUE TITLE
No support to UNLV files

### ISSUE THREAD

**Issue by brucardoso2** [nguyenq/tess4j#10]
When I run tesseract via cli, it automatically uses any .uzn file with the same name of the target image.

Example: 
``` tesseract workingimage004.png output.txt -psm 4 ```

If I have a ```workingimage004.uzn``` file in the same location of my ```workingimage004.png``` it will use it.

Tess4J ignores the uzn file.

Here is my code:
```java
        Tesseract instance = Tesseract.getInstance();
        //In case you don't have your own tessdata, let it also be extracted for you
        File tessDataFolder = LoadLibs.extractTessResources("tessdata");

        //Set the tessdata path
        instance.setDatapath(tessDataFolder.getAbsolutePath());

        instance.setPageSegMode(4);
        try {
            String content = instance.doOCR(page);
        } catch (TesseractException e) {
            e.printStackTrace();
        }
```

Additional info:
Found the function that read and segments the image using a file UNLV at ``` ccstruct\blread.cpp:36 ``` (on tesseract source)

**Comment by 4F2E4A2E** [comment]
Please provide the exact mimetype and a test file, thank you.

**Comment by brucardoso2** [comment]
![workingimage004](https://cloud.githubusercontent.com/assets/440797/6148837/99f79e7e-b1eb-11e4-8814-b5430cf56f1d.png)

Please create a file named: workingimage004.uzn
with the following contents:
``` 600	213		1142	240		Header ```

**Comment by brucardoso2** [comment]
Hey @4F2E4A2E,
Just a friendly question, are you checking on this?
I just want to know if should I wait or try a different solution! Thanks

**Comment by 4F2E4A2E** [comment]
Yes i am, pls get online in skype, thx.

**Comment by 4F2E4A2E** [comment]
Something is not right:
* the png file provided have a lot more content then two lines
* the uzn file provided seams to be empty or with just 1KB
* you did not provide the mimetype

Help me out, this kind of format is new to me, in order to help i must be able to be 100% sure of the data integrity of those files and i need to be able to produce the uzn files, thanks.

**Comment by 4F2E4A2E** [comment]
via brucardoso2: https://github.com/OpenGreekAndLatin/greek-dev/wiki/uzn-format

**Comment by 4F2E4A2E** [comment]
Thanks brucardoso2 for introducing me to uzn.
Our lib does support it, but not automated, but it will in our next release. Untill then just parse your uzn and populate the java.awt.Rectangle. Here an example without reading in the uzn file and parsing it:

	File imageFile = new File("workingimage004.png");
	Tesseract instance = Tesseract.getInstance();  // JNA Interface Mapping
	File tessDataFolder = LoadLibs.extractTessResources("tessdata");
	instance.setDatapath(tessDataFolder.getAbsolutePath());

	//parse the uzn file and create a rectangle obj
	Rectangle rect = new Rectangle(600, 213, 1142, 240);
		try {
			String result = instance.doOCR(imageFile, rect);
			System.out.println(result);
		} catch (TesseractException e) {
			System.err.println(e.getMessage());
		}
	}

**Comment by 4F2E4A2E** [comment]
A proposal has been created as you can read here: #11 
@brucardoso2:  can i close this issue?

**Comment by brucardoso2** [comment]
@4F2E4A2E sure

**Comment by 4F2E4A2E** [comment]
Closing issue.
