### ISSUE TITLE
Can not open file "/pdf.ttf"

### ISSUE THREAD

**Issue by alexanderAnexsys** [nguyenq/tess4j#101]
I am having this exact issue which does not seem to have been opened here

[`https://github.com/tesseract-ocr/tesseract/issues/1304`](https://github.com/tesseract-ocr/tesseract/issues/1304)

**Comment by nguyenq** [comment]
Is your platform Linux and are you using JNA Direct Mapping `Tesseract1/TessAPI1` API? Try JNA Interface Mapping `Tesseract/TessAPI`.
