### ISSUE TITLE
Why is the class datapath variable not used?

### ISSUE THREAD

**Issue by alexanderAnexsys** [nguyenq/tess4j#102]
https://github.com/nguyenq/tess4j/blob/c7a80390264cd60d8c34d01e28bea3fd738e7c92/src/main/java/net/sourceforge/tess4j/Tesseract1.java#L446

**Comment by nguyenq** [comment]
It is used. Check a few lines below that statement.

**Comment by nguyenq** [comment]
@alexanderAnexsys Can this, and other issues, be closed?

**Comment by alexanderAnexsys** [comment]
yes
