### ISSUE TITLE
!strcmp(locale, "C"):Error:Assert failed:in file ../../../src/api/baseapi.cpp, line 191

### ISSUE THREAD

**Issue by jxc928** [nguyenq/tess4j#105]
Hi,
I am using tess4j in my demo project and get errors as showed below....
![image](https://user-images.githubusercontent.com/18159538/42013457-024740aa-7ad0-11e8-958c-dd8e2191a99d.png)

***Some informations if you need***
OS: Ubuntu 16.04
IDE: Intellij IDEA
Tesseract: 
![image](https://user-images.githubusercontent.com/18159538/42013567-80abc18c-7ad0-11e8-9938-ca88d298e7a3.png)

The tesseract works fine in command line but not in java...

***other informations***
1. As mentioned in this [link.](https://github.com/tesseract-ocr/tesseract/issues/1670). This problem also happens in python environment. Just want more people can help, so i submit issue also in here...
2. As mentioned in this [link](https://github.com/tesseract-ocr/tesseract/commit/3292484f67af8bdda23aa5e510918d0115785291). These codes are added in 4.0.0-beta.3 and i am using 4.0.0-beta.1.

So,,,,how can i solve this problem??

**Comment by jxc928** [comment]
I'm going to reinstall the tesseract in older version now..hope it works fine....

but still, any suggestion to solve this problem in new version of tesseract??? Thanks...

**Comment by alexanderAnexsys** [comment]
What does it say if you type "locale"?

**Comment by alexanderAnexsys** [comment]
Try: export LC_ALL=C

**Comment by jxc928** [comment]
@alexanderAnexsys thanks for replying!
As i type "locale" in command line, it showed as:
![image](https://user-images.githubusercontent.com/18159538/42022875-fa435698-7af0-11e8-99f8-741fe6638df9.png)

I haven't try type "export LC_ALL=C" yet, i'll try it later,,,, i wonder if this command will make any side effects or not?

**Comment by alexanderAnexsys** [comment]
Not sure, but it will solve your issue.
It can be reversed with export LC_ALL="en_US.UTF-8"

**Comment by jxc928** [comment]
@alexanderAnexsys thanks a lot~

Actually i reinstalled **tesseract** and **leptonica** with lower versions, showed as below : 
![image](https://user-images.githubusercontent.com/18159538/42031204-0998f762-7b08-11e8-8890-3fc26884d462.png)

And the problem **is not** happened anymore..

So,,
1. Maybe the way you suggested before will going fine with latest version. (maybe i will try it again few days later because of some reasons, 2nd tip is one of them). 
**For now, i haven't find out any useful information about what side effects will be happened after change the setting of LC_ALL, but i really don't think that changing the settings of OS is the best way to solve this problem.

2. As version of **tessdata** should match with **tesseract** : 
tessdata(4.00)       <===>   tesseract(>4.0.0)
tessdata(3.04.00)  <===>   tesseract(<4.0.0)
the results are getting better for sure using tessdata(4.00)...

**Comment by jxc928** [comment]
@alexanderAnexsys 
Hey there~
eum......bad news.....it doesn't work for me...

and if i add `export export LC_ALL=C` in `/etc/profile` ,,,more side effects:
1. when i reboot the system, i can't call my terminal anymore..

**Comment by 6FA3T** [comment]
@jxc928 which version tess4j you used before. i saw your leptonica version is 1.77.0. But tess4j-4.0.2 is depent on Lept4J 1.9.4(work on Upgrade to Leptonica 1.74.4).

**Comment by nguyenq** [comment]
Executing `export LC_ALL=C` at the terminal helped my unit tests run to completion for tesseract 4.0.0-beta.3, whose recent [commit](https://github.com/tesseract-ocr/tesseract/commit/3292484f67af8bdda23aa5e510918d0115785291) seems to have caused the reported issue.

**Comment by Xunnozza-Xenx** [comment]
Have the same problem.

Ubuntu 16, Intellij, Tesseract 4.0.0-beta and leptonica-1.75.3
=> !strcmp(locale, "C"):Error:Assert failed:in file baseapi.cpp, line 201

`export LC_ALL=C `
Didn't work. Something else that i can do?

**Comment by IntraCherche** [comment]
Same problem on Debian 9, Netbeans, Tess4j 4.2.1. 
`export LC_ALL=C` (or setting the environment variables via Set Project Configuration) worked but then every accented characters (à, é,...) were replaced by ? in the Netbeans console. leading to that kind of results.
`Ils ont ?t? se promener ? l'oc?an` instead of the expected `Ils ont été se promener à l'océan`.

Setting only LC_NUMERIC=C as with Tess4j 4.0.2 to keep accents is NOT sufficient anymore. It will only work when LANG is set to C (ie `export LANG=C`), messing up with accents.

**Comment by silverspell** [comment]
@Xunnozza-Xenx This also works on Eclipse / Run Configurations / Environment

**Comment by Raven98** [comment]
Same problem on CentOS 7, Eclipse, Tesseract 4.0.0-beta.4-138-g2093

**Comment by qingtianyu2013** [comment]
you can try 
`import locale
locale.setlocale(locale.LC_ALL, 'C')`

**Comment by jujiaocx** [comment]
you can try
`export LC_ALL=C`

**Comment by nicodn** [comment]
I'm on macOS 10.13.6 and with homebrew I worked around this issue by installing tesseract version 3.05.02

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f46fe1e0d95a9b262408f6ea9c33e3620b44a9ee/Formula/tesseract.rb`

Hope it gets resolved soon so we can upgrade to the latest release!
Thanks! 🙂

**Comment by nguyenq** [comment]
You can set the system locale within Java code using JNA as depicted in https://github.com/nguyenq/tess4j/issues/106#issuecomment-437361950.

**Comment by arun0009** [comment]
I had the same issue, I resolved it by setting environment variable in my [docker file](https://github.com/arun0009/ocr-tess4j-rest/blob/master/docker-compose.yml#L17). If anyone is interested in running it on docker https://github.com/arun0009/ocr-tess4j-rest

**Comment by belkevglaz** [comment]
Tesseract 4 requires LC_ALL, LC_CTYPE and LC_NUMERIC to be set to C: [https://github.com/tesseract-ocr/tesseract/blob/4.0.0-beta.4/src/api/baseapi.cpp#L203](https://github.com/tesseract-ocr/tesseract/blob/4.0.0-beta.4/src/api/baseapi.cpp#L203)

Setting up this enviroment variable for the whole system is not good idea. After that you will get unworkable terminal and several others application
There are some ways to solve this issue in partial cases:
1. use sh script where set this variable before call java -jar <any.jar>
2. if you are using IDEA, you can set this in block "Environment variables" for running configuration.
3. if you use systemd as start service manager, set it in Environment row

**Comment by agnelvishal** [comment]
After entering `export LC_ALL=C` in the terminal, run the java code in the same terminal window. If you are using IDE, open the IDE in the same terminal.

**Comment by nguyenq** [comment]
This restriction to C locale has been lifted in Tesseract 4.1.0 since https://github.com/tesseract-ocr/tesseract/commit/96f6fc28b80768a220e973f31100c9af725020cf commit.

**Comment by pavan097** [comment]
export LC_ALL=C  Solved my problem

**Comment by suncheng778** [comment]
所以低于4.1.0的版本都会有这个问题嘛
