### ISSUE TITLE
Tess4j libraries not found when changing tmpdir from command line in Windows

### ISSUE THREAD

**Issue by IntraCherche** [nguyenq/tess4j#108]
Hi,

First congratulation for your very useful project. Tess4J used to work great on my desktop java app under Windows 10 64 (I use maven in my project to integrate Tess4j). Yet I encounter issues on some customers' machines because of presumably software restriction policy (SRP) in place in my customer's company. It looks like the dll that are needed by tess4j are blocked when they are in the user's AppData/Local/temp folder. 

So on another machine I am testing the providing of a different temp dir. I launch the project with **-Djava.io.tmpdir=./temp** -jar MyJar.jar. The temp folder is populated with the tess4j folder including the 2 dlls for the x86-x64 platform, and a jna-xxxxx folder with 2 jna dlls.

Then when I try to instanciate Tess4J I get :

java.lang.Error: Le chemin d'accès spécifié est introuvable.
	at com.sun.jna.Native.open(Native Method) ~
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:171) ~
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398) ~
	at com.sun.jna.Native.register(Native.java:1396) ~
	at com.sun.jna.Native.register(Native.java:1156) ~
	at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)

The tessdata are configured and usually work (they are placed in .tessdata).

I looked at the code and when loading the libraries you set the jna path to the content of property java.io.tmpdir . So it should not pose a problem, should it ? 

Can you advise me on what to do ?

Thanks in advance for your help

Regards

**Comment by nguyenq** [comment]
I tried with `-Djava.io.tmpdir=C:\Temp` and had no issues.

**Comment by IntraCherche** [comment]
Oh my comment from yesterday disappeared. So actually there is no issue now. Indeed it failed because of my specifying relative path to "tmpdir". Using full path solved the problem. Sorry again that the comment to my comment disappeared.
