### ISSUE TITLE
Output Resolution should be variable.

### ISSUE THREAD

**Issue by korabocintake** [nguyenq/tess4j#109]
We use tesseract-ocr for captured screen image from PC display.
Screen resolution is low (traditionally 72ppi or 96ppi).
Tesseract requires more than 300dpi. 
In this case, we use the image previously multiplied by 3 or 4. 
(e.g.  72ppi x 4 = 288ppi, 96ppi x 3 = 288ppi, x4 = 384ppi)
In tess4j, the resolution of output image is fixed as 300dpi.
So we want to change this to variable value.

**Comment by korabocintake** [comment]
Thanks response. No need for changing input, but output image from jTessBoxEditor is important.
We want make scaled image from screen capture and save free dpi TIFF image for use of training.
I made pull request about this issue. Please check it.

**Comment by nguyenq** [comment]
Tesseract works best with 300-DPI images. jTessBoxEditor generates 300-DPI images for use in training, which does not alter input image. We fail to see how it could impact your work in anyway.
