### ISSUE TITLE
Proposal: Add UNZ Automated File Support

### ISSUE THREAD

**Issue by 4F2E4A2E** [nguyenq/tess4j#11]
As one can read here #10, there is currently no automated support for unz files.
I propose to add an automated support that, would check for unz files, parse them and populate a java.awt.Rectangle object and proceed with the process.

WDT?

**Comment by nguyenq** [comment]
Tesseract library, hence Tess4J, supports reading the UNLV zone file out-of-the-box. It needs to know the input filename; the PSM will be set accordingly automatically.

`TessBaseAPISetInputName(handle, inputfile.getAbsolutePath());`

**Comment by 4F2E4A2E** [comment]
When running tess4j with PSM 4

    instance.setPageSegMode(4);
this error occurs

    set_count == gridheight():Error:Assert failed:in file .\textord\colfind.cpp, line 648
Could it be that this functionality is broken? Seams like so: https://code.google.com/p/tesseract-ocr/issues/detail?id=653

**Comment by brucardoso2** [comment]
@4F2E4A2E Which tesseract*.dll were you using when you got this error?
In my tests I couldn't use http://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j/1.4.1 because it uses libtesseract302.dll.
This has been fixed on libtesseract303.dll (which this repository uses).

**Comment by 4F2E4A2E** [comment]
Tested with our latest release 1.4.1.

**Comment by brucardoso2** [comment]
The one in maven central? That is the one I mentioned that doesn't work.

**Comment by 4F2E4A2E** [comment]
Did not say otherwise.
Where do you have the info from that the fix is actually in the libtesseract303.dll release?

I could not find this information.

**Comment by brucardoso2** [comment]
In the issue's page, in this comment https://code.google.com/p/tesseract-ocr/issues/detail?id=653#c4.
But I went all the way to downloading their source code and inspecting the commit messages, found this commit https://code.google.com/p/tesseract-ocr/source/detail?r=64c739c8af9a6d0b002ed035473dae6758990986

**Comment by nguyenq** [comment]
It turns out that the support is in low-level TessAPI; the method call is not in the high-level Tesseract API. We'll try to include a call to `TessBaseAPISetInputName` method to provide UNZ support at that level.

**Comment by nguyenq** [comment]
UNZ support has been committed to tess4j-2 branch. Please verify. You won't need to set PSM.

Thanks.

**Comment by 4F2E4A2E** [comment]
Functionality has been released. 
Examples will follow soon. 
Closing.
