### ISSUE TITLE
Failed Loading languages

### ISSUE THREAD

**Issue by KasperJanssens** [nguyenq/tess4j#111]
Hi,

I have an installation of Tesseract 4.x (4.0.0-beta-1 from the Ubuntu repos). When I perform a tesseract --list-langs on the command line I get five languages loaded ('deu' among others). But when I use tess4j (I tried 4.0.2 and 4.1.1) I keep on getting an error message 
```
Failed loading language 'deu'
Tesseract couldn't load any languages!
```
Next, I get a core dump, I presume because of no languages but did not dig deeper in there. 

I have tried migrating from Tesseract 3.x yesterday (and of course also upgrade tess4j along with that) and seemingly had to do no code changes in Java code for it to compile. I also did not find any pointer that there would be changes. 

I guess the old code should still be runnable with the new major version of Tess4j and Tesseract? If not, can you point me to an example or so? If it should still be runnable, any idea what could cause this issue? I checked the language files, they are present, readable and larger than zero size. I am on Ubuntu 18.04, OpenJdk 10.0.1, Maven 3.5.4.

Kasper

Edit: Maybe I also have to mention I have according to me set the datapath correctly to point at the folder containing the language files, it is pointing to /usr/share/tesseract-ocr/4.00/tessdata, which contains the .traineddata files

**Comment by nguyenq** [comment]
Make sure you use the Tesseract 4.0x-compatible [language packs](https://github.com/tesseract-ocr): best or fast.

**Comment by KasperJanssens** [comment]
So I cloned this https://github.com/tesseract-ocr/tessdata_best and called the setDatapath to this tessdata_best folder, but I still get the same Failed loaded language 'deu' and a stack trace.

**Comment by nguyenq** [comment]
I looked at your test case. You seem to have incorrectly set the datapath. As far as I know, the language packs are always placed directly under `tessdata` folder. If your data files are under "/usr/local/share/4.00/tessdata", you'll need to call `instance.setDatapath("/usr/local/share/4.00/tessdata");`

In Tesseract 3.x, the last segment `tessdata` in the datapath is not needed.

**Comment by KasperJanssens** [comment]
I am not sure what you mean with that last comment. I did a git clone of the tessdata in /tessdata_best and I set my data path in the test case in tesseract-4-test to point to /tessdata_best, so that should be correct, should it not? I am most likely missing something silly, but I don't seem to find it.

**Comment by nguyenq** [comment]
[`OEM_TESSERACT_ONLY`](https://github.com/tesseract-ocr/tesseract/blob/master/src/ccstruct/publictypes.h) is for legacy language packs (3.0x). If you use newer ones -- fast or best -- leave `OcrEngineMode`  at default.

I could be wrong about insistence on `tessdata` name for data folder for Tesseract 4.x. It was true for Tesseract 3.x, though.

**Comment by KasperJanssens** [comment]
I think you're right about the tessdata folder, in tesseract 3 you could do it both ways. I do think that it is weird that I get a message about language pack issues when the issue seems to be the engine mode. But I guess my problem is solved right now.
