### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by ermik** [nguyenq/tess4j#114]
Dear Quan and Tess4J team,

please specify the status of macOS runtime support.  As a user of VietOCR3 on macOS I'd like to know if there are future improvements to the tools that will support macOS.

**Comment by nguyenq** [comment]
[VietOCR3](https://github.com/nguyenq/VietOCR3), the Java Swing frontend, is still being maintained and supported to the latest Tesseract binary version. No new feature is planned, unless the users put in a RFE that is considered worthwhile for the community.

The new JavaFX frontend, [VietOCRfx](https://github.com/nguyenq/VietOCRfx), is under development and, hopefully, will have the same set of functionality as the Swing version.
