### ISSUE TITLE
tess4j may not work right when running from Jar

### ISSUE THREAD

**Issue by BullyWiiPlaza** [nguyenq/tess4j#115]
When running my code from the `IDE`, the `OCR `results are fine. When running the code from `Jar`, the `OCR `returns an empty String for the same image input and I don't get any kinds of exceptions. I don't understand why this happens. More details [here](https://stackoverflow.com/questions/52169641).

**Comment by nguyenq** [comment]
Sounds like the JAR was not packaged properly. Make sure all the required JARs are in the classpath.

**Comment by BullyWiiPlaza** [comment]
Yes. Since I'm using `maven`, I expect it to be done correctly by default:
```
<dependency>
	<groupId>net.sourceforge.tess4j</groupId>
	<artifactId>tess4j</artifactId>
	<version>LATEST</version> <!-- 4.2.1 -->
</dependency>
```

But I checked anyway and these are the` JAR`s I have:

```
jai-imageio-core-1.4.0.jar
jna-4.5.2.jar
commons-io-2.6.jar
lept4j-1.10.0.jar
tess4j-4.2.2.jar
```

It looks fine to me but why is the `Tess4J`s behavior from `JAR` different to running from source? I'm also specifying the same `tessdata` path.

I tried using a [native `Tesseract-OCR` installation](https://digi.bib.uni-mannheim.de/tesseract/) and it also returned an empty string for my example image even when running from source unlike `Tess4J` which works from source but not from `JAR`. With `Tesseract-OCR` I'm getting the warning

```
Tesseract Open Source OCR Engine vv4.0.0-beta.1.20180608 with Leptonica
Warning. Invalid resolution 0 dpi. Using 70 instead.
Empty page!!
Empty page!!
```

but I couldn't fix it by forcing `DPI` to be written to the `PNG` on the disc and by resizing the image size. With `Tess4J` resizing alone worked. Strange.

**Comment by nguyenq** [comment]
You may want to check out [VietOCR3](https://github.com/nguyenq/VietOCR3) and [VietOCRfx](https://github.com/nguyenq/VietOCRfx) projects to see how they are packaged. They use and bundle tess4j library.

**Comment by BullyWiiPlaza** [comment]
Thanks for the hint. I'm using `IntelliJ` and since no build instructions are provided, I was having trouble to build it. Apparently you're using `Gradle` but I'm using `Maven`. I still doubt it's a `JAR` packaging issue since I don't get any exceptions related to missing or misplaced `DLL`s or `JAR`s. It must be something else causing this. You really can't think of what it could be?

**Comment by BullyWiiPlaza** [comment]
I'm closing this issue since it's no longer relevant: I had more luck calling the native `Tesseract-OCR` `tesseract.exe` binary manually and by using bigger images in general to improve recognition.
