### ISSUE TITLE
can i use this in linux like Centos？

### ISSUE THREAD

**Issue by limng06** [nguyenq/tess4j#116]
看起来需要微软C++库支持是不是就不能在linux上跑了？

**Comment by 6FA3T** [comment]
不需要，你看教程。在linux下，需要tesseract-orc的支持。具体参考https://github.com/tesseract-ocr/tesseract

**Comment by nguyenq** [comment]
Install Tesseract on CentOS as described [here](https://groups.google.com/forum/#!topic/tesseract-ocr/u-PZaakaKs0), then you're good to go.
