### ISSUE TITLE
Tessj4 - Error opening data file ./tessdata/eng.traineddata

### ISSUE THREAD

**Issue by SeritiAutomation** [nguyenq/tess4j#119]
OS: Windows 10
IDE: IntelliJ 
Added **tess4j** version **4.2.3** dependency in the POM file.
     
After this in project root folder; I created tessdata folder and placed eng.traineddata 
This error I got "Tessj4 - Error opening data file ./tessdata/eng.traineddata"

Below is the code:
`import net.sourceforge.tess4j.Tesseract;`
`import net.sourceforge.tess4j.TesseractException;`
`import java.io.File;`

`public class Demo{`
    `public static void main(String [] args) {`
        `Tesseract instance = new Tesseract();`
        `instance.setDatapath("tessdata");`
        `instance.setLanguage("eng");`
        `try {`
            `String result = instance.doOCR(new File("Capture.png"));`
            `System.out.println(result);`
        `} catch (TesseractException e) {`
            `System.err.println(e.getMessage());`
        `}`
    `}`
`}`
Also when I run program; I observed that in **temp** folder below two .dll get created on this location "C:\Users\deepakv.WINJITBIOS\AppData\Local\Temp\tess4j\win32-x86-64"

libtesseract400.dll
liblept1760.dll

Apart from the above; also I have download the binaries "**tesseract-ocr-w32-setup-v4.0.0-rc3.20181014.exe**" from  "**https://github.com/UB-Mannheim/tesseract/wiki**"
This installed at **C:\Users\deepakv.WINJITBIOS\AppData\Local\Tesseract-OCR**

Any help on this would be much appreciated.

**Comment by SeritiAutomation** [comment]
> Make sure you use the LSTM-compatible version of `.trainnedata` file. There are 2 compatible ones: fast and best, which can be downloaded from https://github.com/tesseract-ocr.

I deleted the eng.traineddata from tessdata and tried files from fast and the best.. but still i am getting the same error.
https://github.com/tesseract-ocr/tessdata_best
https://github.com/tesseract-ocr/tessdata_fast

**Comment by nguyenq** [comment]
You can try setting with absolute path to `tessdata` folder, for example:

`instance.setDatapath("C:\\somepath\\tessdata");`

**Comment by SeritiAutomation** [comment]
> You can try setting with absolute path to `tessdata` folder, for example:
> 
> `instance.setDatapath("C:\\somepath\\tessdata");`

Thanks it working now.

**Comment by nguyenq** [comment]
Can this ticket be closed?
