### ISSUE TITLE
Tesseract creates PDF documents with "glyphless" font

### ISSUE THREAD

**Issue by aderoks** [nguyenq/tess4j#120]
I have a set of PDFs which were scanned. Being scanned, the entire content was just images and was not searchable. I tried to convert the PDF into a searchable one by using the combo of Ghostscript and Tesseract (via Tess4j). I converted the scanned PDF into jpg images using Ghostscript, and converted the generated images back to PDFs using Tesseract.

```
Tesseract tessInst = new Tesseract();
tessInst.setDatapath("D://Tess//tessdata");
List<RenderedFormat> list = new ArrayList<RenderedFormat>();
list.add(RenderedFormat.PDF);

for (int i = 0; i < images.size(); i++)
    tess.createDocuments(i + ".jpg", "D://Tess//output" + i, list);
```

The PDFs were generated fine, and are even searchable, but when I select a word, the selection highlight is a little skewed from the actual word.  I tried generating a DOM structure by using PDF2Dom, as I had been doing with other PDFs which were searchable without OCR processing and getting great results, but when I ran it on these Tesseract generated PDFs, I got the following exception:

`Error loading type 0 with ttf descendant font 'GlyphLessFont' Message: java.io.IOException: Multi byte glyph name not supported. class java.io.IOException`

I could not find any configuration where I can change the output font. The output font should be a configurable parameter.

**Comment by nguyenq** [comment]
Since this seems to be an issue with Tesseract, you may want to file a report with [them](https://github.com/tesseract-ocr/tesseract/issues/). We saw a few similar PDF-related issues filed.

**Comment by aderoks** [comment]
I have opened the same issue in Tesseract as well as advised by you.

(https://github.com/tesseract-ocr/tesseract/issues/2034)

**Comment by aderoks** [comment]
They have closed the issue saying that they do not provide support for 3rd party projects.

**Comment by jbreiden** [comment]
I wrote the PDF renderer for Tesseract and created the font it uses. Could you please explain to me exactly what `Multi byte glyph name not supported.` is referring to? I've attached an XML representation of the font.

[glyphless.ttx.txt](https://github.com/nguyenq/tess4j/files/2530417/glyphless.ttx.txt)

**Comment by jbreiden** [comment]
And here is the direct font if that helps with debugging.

[font.zip](https://github.com/nguyenq/tess4j/files/2530426/font.zip)

**Comment by jbreiden** [comment]
Wait, this isn't the right spot either. I should be talking to the author of PDF2Dom. Please put me in touch.

**Comment by aderoks** [comment]
This is the Github profile of the creator of PDF2Dom.

https://github.com/radkovo

**Comment by nguyenq** [comment]
Not an issue with Tess4J per se.
