### ISSUE TITLE
doOCR() method is throwing null pointer exception on MAC OS 10.13 but the same code is working on Windows 10 OS

### ISSUE THREAD

**Issue by QA2Dev** [nguyenq/tess4j#124]
I'm facing null pointer exception at doOCR("filepath") method of tess4j while running tests on MAC OS 10.13.5 but same tests are running without exception on Windows 10 OS ().

kindly let me know if there is any dependency to be installed for MAC OS.

Details

Tess4j ver 4.2.3
Java 8

**Comment by QA2Dev** [comment]
@nguyenq kindly let me know if you require further details.

**Comment by nguyenq** [comment]
Tesseract would have to be installed first.

**Comment by QA2Dev** [comment]
@nguyenq Even after installing tesseract when I run the tests, it's throwing java exception

**Comment by QA2Dev** [comment]
@nguyenq I am getting the below error after installing tesseract and run doOCR() method.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff50a8a59f, pid=10759, tid=0x0000000000001a03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsystem_platform.dylib+0x159f]  _platform_memmove$VARIANT$Nehalem+0x19f
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#

**Comment by nguyenq** [comment]
What is Tesseract version? Can you first try `export LC_ALL=C` at the command line before running your program?

**Comment by QA2Dev** [comment]
@nguyenq kindly find below details of tesseract installed on Mac OS 10.13.5
tesseract 4.0.0
 leptonica-1.76.0
  libjpeg 9c : libpng 1.6.35 : libtiff 4.0.9 : zlib 1.2.11
 Found AVX
 Found SSE

**Comment by nguyenq** [comment]
We do not have a Mac to investigate the issue.

Could be related to https://bugs.openjdk.java.net/browse/JDK-8192785. Can you try with newer JVM than 8?

**Comment by QA2Dev** [comment]
@nguyenq On MAC itself today I downloaded tess4j dependencies using Maven POM.xml and ran the tests I was able to retrieve tests succesfully. I didn't face any issue.

When I downloaded dependencies using build.gradle and ran tests, at doOCR() method JRE is getting crashed.

As you suggested, let me work with Java 9 and retry.

**Comment by nguyenq** [comment]
I'm not familiar with gradle, but if the Maven setup worked, then the problem is probably somewhere else outside of tess4j.

**Comment by QA2Dev** [comment]
@nguyenq I have created a new gradle project to test ocr it's working fine but when I implemented the same in another gradle project then jre is getting crashed. please find below the code used.

ITesseract instance = new Tesseract();
		try {
			System.out.println("***************Display************************");
			File imageFile = new File("C:\\AUT\\operation.png");
			String val = instance.doOCR(imageFile);
			System.out.print(val);
		}
		catch (TesseractException e)
		{
			System.err.println(e.getMessage());
		}

**Comment by QA2Dev** [comment]
@nguyenq I'm getting the below issue at doOCR() method, kindly look into to that you might get the root cause of the issue.
**pos.x () == c_outline->start_pos ().x () && pos.y () == c_outline->start_pos ().y ():Error:Assert failed:in file polyaprx.cpp, line 208**
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000124c32c41, pid=1273, tid=0x0000000000001c03
#
# JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.dylib+0x159c41]  _ZNK7ERRCODE5errorEPKc16TessErrorLogCodeS1_z+0x173
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

**Comment by nguyenq** [comment]
Here is the source file pertinent to the assert fail.

https://github.com/tesseract-ocr/tesseract/blob/master/src/ccstruct/polyaprx.cpp

You may want to dig into it to determine what has caused the error.

**Comment by nguyenq** [comment]
Have you tried to uninstall and reinstall Tesseract?

**Comment by QA2Dev** [comment]
@nguyenq I will try and let you know, thank you

**Comment by QA2Dev** [comment]
@nguyenq I tried runing tests with JNA 5.1.0 and I'm getting the same error as follows

 A fatal error has been detected by the Java Runtime Environment:

  SIGILL (0x4) at pc=0x000000011d741c41, pid=69885, tid=0x0000000000001b03

 JRE version: Java(TM) SE Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.181-b13 mixed mode bsd-amd64 compressed oops)
 Problematic frame:
pos.x () == c_outline->start_pos ().x () && pos.y () == c_outline->start_pos ().y ():Error:Assert failed:in file polyaprx.cpp, line 208
 C  [libtesseract.dylib+0x159c41]  _ZNK7ERRCODE5errorEPKc16TessErrorLogCodeS1_z+0x173

 Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Users/ctl-user/Downloads/com-lego-education-codingexpress-master/hs_err_pid69885.log

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.


Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by QA2Dev** [comment]
Hi @nguyenq  kindly let me know if you find any clue to resolve this issue.

**Comment by QA2Dev** [comment]
@nguyenq 

Warning: Invalid resolution 0 dpi. Using 70 instead.
pos.x () == c_outline->start_pos ().x () && pos.y () == c_outline->start_pos ().y ():Error:Assert failed:in file polyaprx.cpp, line 208
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x0000000128922014, pid=26227, tid=0x0000000000004303
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.121-b13 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.4.dylib+0x21c014]  ERRCODE::error(char const*, TessErrorLogCode, char const*, ...) const+0x174
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/e001844/Documents/LegoWorkspace/com-lego-education-codingexpress/hs_err_pid26227.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

**Comment by QA2Dev** [comment]
@nguyenq I am facing this problem only when I used this with Cucumber-JVM framework, when use this code in Cucumber Steps.

**Comment by SoWhatIamComing** [comment]
I have the same problem,is there a solution to handler it?

**Comment by nguyenq** [comment]
Is this still an issue with the latest version of Tesseract/Tess4J? Can this be closed?

**Comment by nguyenq** [comment]
No response from OP.
