### ISSUE TITLE
tess4j read_params_file: parameter not found: error which can shutdown tomacat thread.

### ISSUE THREAD

**Issue by vvsvv** [nguyenq/tess4j#125]
String result = "";
		ITesseract instance = new Tesseract1();
		File tessTrainedDataLoc = OpenmrsUtil.getDirectoryInApplicationDataDirectory(
			GlobalPropertyHelper.getGlobalProperty(OpenmrsConstants.GLOBAL_PROPERTY_OCR_TESS_DATA_DIR));
		instance.setDatapath(tessTrainedDataLoc.getAbsolutePath());
		instance.setLanguage(language);
		try {
			result = instance.doOCR(imageFile);
			log.info("Tessact result: " + result);
		}
		catch (TesseractException e) {
			log.error(e.getMessage());
		}
		finally {
			return result;
		}

**Comment by vvsvv** [comment]
**int TessBaseAPIInit1(TessBaseAPI var1, String var2, String var3, int var4, PointerByReference var5, int var6);**
the method make an fatal error

**Comment by vvsvv** [comment]
tomcat will occur 502 Bad Gateway.

**Comment by nguyenq** [comment]
With little info given against many unknown variables, it's difficult to diagnose the reported issue. Does `tessTrainedDataLoc.getAbsolutePath` point to `tessdata` folder? Are the versions of Tess4J and Tesseract compatible?

https://github.com/nguyenq/tess4j/releases

**Comment by vvsvv** [comment]
tesseract 4.0.0
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.4.2) : libpng 1.2.54 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.4 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

**Comment by vvsvv** [comment]
<dependency>
		    <groupId>net.sourceforge.tess4j</groupId>
		    <artifactId>tess4j</artifactId>
		    <version>4.2.2</version>
	    </dependency>

**Comment by vvsvv** [comment]
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by nguyenq** [comment]
You probably need tess4j-4.3.0 to be compatible with tesseract 4.0.0.

The source is available. You should be able to step through it, or execute the unit tests.

**Comment by vvsvv** [comment]
![image](https://user-images.githubusercontent.com/20897218/48328007-e1987b80-e67c-11e8-9827-9b544a8a5c96.png)

**Comment by vvsvv** [comment]
![image](https://user-images.githubusercontent.com/20897218/48328033-07be1b80-e67d-11e8-842c-f11afa7c3904.png)

**Comment by vvsvv** [comment]
I changed to tess4j4.3.0, and also encounter the fatal error. tomcat will shut down when step next.

**Comment by vvsvv** [comment]
![image](https://user-images.githubusercontent.com/20897218/48328095-65eafe80-e67d-11e8-9546-5feae346556e.png)

**Comment by nguyenq** [comment]
You haven't mentioned about the OS you're using. Anyway, it could be something about your Tesseract installation. You may want to re-install it. Once that done, try to get a simple console app to work first before trying it on a server environment.

**Comment by vvsvv** [comment]
Tesseract 4.00’s command line could work on linux.

**Comment by nguyenq** [comment]
We suggest you try a small console app example on your server first to make sure everything is set up correctly before trying it on Tomcat.

**Comment by nguyenq** [comment]
Seems similar to https://github.com/tesseract-ocr/tesseract/issues/1620. Make sure your set the correct datapath and use compatible `traineddata` files.
