### ISSUE TITLE
Can We execute tess4j methods from Bamboo with out the tesseract installation?

### ISSUE THREAD

**Issue by AntonJerald2410** [nguyenq/tess4j#126]
Hi nguyenq,

I have installed the tesseract in ubuntu 14.04 using the below command.

sudo apt-get install tesseract-ocr

After that I am able to use tess4j and tesseract in the local Ubuntu machine. 

I want to execute this from Bamboo (Hosted in Linux machine), But I can not install tesseract-ocr in Bamboo!

Can you help me on this.

**Comment by nguyenq** [comment]
An installed Tesseract is required. We're not familiar with Bamboo to render assistance.
