### ISSUE TITLE
TessOrientation

### ISSUE THREAD

**Issue by Siignature** [nguyenq/tess4j#127]
I need to specify the page orientation (TessOrientation) because Tesseract is rotating some input images every time. How can I set it?

```
Tesseract tessInst = new Tesseract();
tessInst.setLanguage("eng");
tessInst.setDatapath("tessdata");
tessInst.setPageSegMode(TessPageSegMode.PSM_SPARSE_TEXT_OSD);
```

**Comment by nguyenq** [comment]
I'm not sure if that's possible. You may want to post your question on Tesseract forum for guidance.

**Comment by nguyenq** [comment]
Maybe an issue with Tesseract.

https://github.com/tesseract-ocr/tesseract/issues/1165
