### ISSUE TITLE
for psm 7 - java.lang.Error: Invalid memory access

### ISSUE THREAD

**Issue by dattatembare** [nguyenq/tess4j#129]
CASE 1 :: I got an error while executing --> 
```
package com.ea.ocr.tesseract;

import java.io.File;

import com.sun.jna.NativeLibrary;

import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.Tesseract1;
import net.sourceforge.tess4j.TesseractException;

public class Test {

	public static void main(String[] args) {
		try {
			File file = new File("C:/OCR/9-2-3.png");
			NativeLibrary.addSearchPath("TESSDATA_PREFIX", "C:/Program Files (x86)/Tesseract-OCR/tessdata/");
			 Tesseract1 instance = new Tesseract1();
			//Tesseract instance = new Tesseract();
			instance.setDatapath("C:/Program Files (x86)/Tesseract-OCR/tessdata/");
			instance.setLanguage("eng");
			instance.setPageSegMode(7);
			System.out.println(instance.doOCR(file));
		} catch (TesseractException e) {
			System.out.println("Error while reading file");
		}
	}

}

```

Result::

```

contains_unichar_id(unichar_id):Error:Assert failed:in file c:\projects\github\tesseract-ocr\src\ccutil\unicharset.h, line 511
Exception in thread "main" java.lang.Error: Invalid memory access
	at net.sourceforge.tess4j.TessAPI1.TessBaseAPIGetUTF8Text(Native Method)
	at net.sourceforge.tess4j.Tesseract1.getOCRText(Tesseract1.java:413)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:269)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:191)
	at net.sourceforge.tess4j.Tesseract1.doOCR(Tesseract1.java:175)
	at com.ea.ocr.tesseract.Test.main(Test.java:22)

```
Here is the test file for which I got an error Image attached here -->
![9-2-3](https://user-images.githubusercontent.com/33232124/49489876-0961a600-f81b-11e8-8f2e-10bb0a225e12.png)

**One interesting thing here, if I use**  `setPageSegMode(3)` **then result is `Empty page!!`
and if I use `setPageSegMode(6)` getting some matching result**  ```Other‘3 _ Deep Chand 
Name ```
I was expecting an empty string or some other exception so that I can handle it and use different psm programmatically but with this `Invalid memory access` application is breaking.

For the same example above, if I use ` Tesseract instance = new Tesseract(); ` then same results for psm 3 and 6, and error for psm 7 is 

```
contains_unichar_id(unichar_id):Error:Assert failed:in file c:\projects\github\tesseract-ocr\src\ccutil\unicharset.h, line 511
Exception in thread "main" java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokePointer(Native Method)
	at com.sun.jna.Function.invokePointer(Function.java:490)
	at com.sun.jna.Function.invoke(Function.java:434)
	at com.sun.jna.Function.invoke(Function.java:354)
	at com.sun.jna.Library$Handler.invoke(Library.java:244)
	at com.sun.proxy.$Proxy0.TessBaseAPIGetUTF8Text(Unknown Source)
	at net.sourceforge.tess4j.Tesseract.getOCRText(Tesseract.java:433)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:288)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:209)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:193)
	at com.ea.ocr.tesseract.Test.main(Test.java:22)

```

Case 2 ::
Previously, I have observed the same error when the language was not appropriate like image had Hindi text + and English Number and I was providing `hin+eng` it gave me `Invalid memory error`, and it worked when I changed the language to `hin`

System Info
```
Windows 10 64 bit

C:\Program Files (x86)\Tesseract-OCR>tesseract --version
tesseract 4.00.00alpha
 leptonica-1.74.1
  libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.5.0) : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.8 : libwebp 0.4.3 : libopenjp2 2.1.0
```

I hope I have provided enough information for this issue, please let me know if you need more.
Thanks in advance.

**Note: I checked the old issues's description but didn't find relevant to my issue.**

**Comment by dattatembare** [comment]
@nguyenq Need your attention here, I really stuck at this point. Can you please guide me?

**Comment by dattatembare** [comment]
I have tested on the command line, psm 3 and 6 results are same as tess4j, psm 7 returned some text which is not valid but at least didn't fail with an error. 

```
c:\Program Files (x86)\Tesseract-OCR>tesseract C:\OCR\9-2-3.png C:\OCR\9-2-3 -l eng -psm 3
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
Empty page!!
Empty page!!
```

```
c:\Program Files (x86)\Tesseract-OCR>tesseract C:\OCR\9-2-3.png C:\OCR\9-2-3 -l eng -psm 6
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
```

Result: 
```
_ Deep Chand
Name *
```

```
c:\Program Files (x86)\Tesseract-OCR>tesseract C:\OCR\9-2-3.png C:\OCR\9-2-3 -l eng -psm 7
Tesseract Open Source OCR Engine v4.00.00alpha with Leptonica
```

Result: `th - C`

**Comment by nguyenq** [comment]
Why running v4.00.00alpha and not final v4.0.0? There was a huge number of changes and fixes committed by Tesseract developers.

**Comment by nguyenq** [comment]
You were using tesseract-4.00.00alpha, which was unstable and buggy.

**Comment by dattatembare** [comment]
I'm still using the same version ` tesseract-4.00.00alpha` because I'm facing an error with `v4.0.0`, but tess4j version upgrade from `4.0.1` to `4.3.0` resolved my issue.
I would like to upgrade my tesseract version if #112 has a fix or workaround.

**Comment by nguyenq** [comment]
Use the latest version `4.3.1`.

**Comment by dattatembare** [comment]
Thanks! @nguyenq 
I'm all set with errors.
