### ISSUE TITLE
Ghostscript WARN messages

### ISSUE THREAD

**Issue by brucardoso2** [nguyenq/tess4j#13]
Using `PdfUtilities.convertPdf2Png(inputPdfFile)` outputs this:
```
log4j:WARN No appenders could be found for logger (org.ghost4j.Ghostscript).
log4j:WARN Please initialize the log4j system properly.
```
The conversion works fine, but the warning is annoying :)

**Comment by nguyenq** [comment]
Ghost4J uses Log4J for logging, which needs a `log4j.properties` file, which can be found in the tess4j package.

**Comment by 4F2E4A2E** [comment]
Here the mentioned log4j.properties example: [tess4j/src/test/resources/log4j.properties](https://github.com/nguyenq/tess4j/blob/master/src/test/resources/log4j.properties)

Closing issue.
