### ISSUE TITLE
NullPointerException in

### ISSUE THREAD

**Issue by saifjsl** [nguyenq/tess4j#130]
Hi, I know this is a very useless issue report. But since 4.2.2 we are getting a NullPointerException when running `getSegmentedRegions()` doing OCR in our unit-tests. We are still stuck 4.2.1. Not sure how can I be of anymore help. All 4.2.2/3/4 and 4.3.0 report this problem

**Comment by nguyenq** [comment]
Commit 7f00f42dc0d0f6d48a253afa1949b224b2f40322 is the only change from 4.2.1 to 4.2.2. Can you get the source files and debug through them?

**Comment by nguyenq** [comment]
Please try with new release [tess4j-4.3.1](https://github.com/nguyenq/tess4j/releases/tag/tess4j-4.3.1).

**Comment by nguyenq** [comment]
No response from OP.
