### ISSUE TITLE
Performance issue under Linux

### ISSUE THREAD

**Issue by nikolayzeltser** [nguyenq/tess4j#131]
Hi! I experience an interesting behavior with Tess4J running under CentOS.
My environment:
CentOS7 (4 CPU with AVX2 and etc.)
Tomcat 8.5
JRE 1.8.191-b12
latest Tesseract4 installed with yum
latest Tess4J invoked by servlet

I take the same file and serially trigger recognition multiple times.
And timing is always the same:
First and second runs last for 2 second
The third and below take 12 second

Application restart doesn't have any effect (12s for first and below)
Tomcat restart forces the situation to repeat: 2s, 2s, 12s ...

When I run Tesseract from command line it is always fast with no performance degradation

When I deploy my application to Windows server and use dll, the timing is stable with no performance degradation.

Please, help!

I can give you all application sources including teamviewer connection

**Comment by nguyenq** [comment]
Are you keeping the same `TessAPI` instance for multiple image runs? You may want to clear the cache between runs. Look at `TessBaseAPIClear` or `TessBaseAPIClearAdaptiveClassifier` in [documentation](http://tess4j.sourceforge.net/docs/docs-4.3/).

**Comment by nikolayzeltser** [comment]
I create a new Tesseract instance in each run

**Comment by nikolayzeltser** [comment]
And I call TessBaseAPIDelete at the end of each execution

**Comment by nguyenq** [comment]
Make sure you call `dispose` to release resources.

**Comment by nikolayzeltser** [comment]
I do call it

**Comment by nguyenq** [comment]
Can you try with `Tesseract1` API and/or latest JNA version?

**Comment by nikolayzeltser** [comment]
1. Replaced apii init string to
ITesseract instance = new Tesseract1();  
No effect
2. Replaced jna-4.1.0.jar with jna-5.1.0.jar in jre/lib/ext
No Effect

**Comment by nguyenq** [comment]
Tesseract CLI uses `Renderer` API, not `GetUTF8Text` as currently called by `doOCR`. You may wan to try that.

**Comment by nguyenq** [comment]
Try using `createDocuments`  method.

**Comment by nikolayzeltser** [comment]
Have tried. It's even slower. The third run is 7 times slower than the first and the second: 
5s, 5s, 35s

**Comment by nikolayzeltser** [comment]
Hi! I've redesigned my application to run Tesseract by CMD call without Tess4J. It is fast and stable now.
It proves that there is something wrong in tess4j-jna layer :(

**Comment by nguyenq** [comment]
The user has resorted to the CLI instead of Tesseract API to resolve the performance issue. Note that the CLI uses `ProcessPages` method with `ResultRenderer` API.

https://github.com/tesseract-ocr/tesseract/blob/master/src/api/tesseractmain.cpp
