### ISSUE TITLE
ERROR net.sourceforge.tess4j.Tesseract - null

### ISSUE THREAD

**Issue by veir-panda** [nguyenq/tess4j#132]
## Issue:

Hello, I'm facing NullPointerException while using tess4j for a test on Linux, but the same code runs well on Windows 10. 

I 'm sure I have a right Linux tesseract envs, because I execute with the command code `tesseract` and it's works fine.

Could you please give me any idea? 

Thanks.

## Test code:
Here is the test code, and it's runs well on the windows 10, using with idea 2017.3.

Test.java
```java
public class Test {
    public static void main(String[] args) {
        try {
            System.out.println(discern(args[0], args[1]));
        } catch (TesseractException e) {
            e.printStackTrace();
        }
    }

    public static String discern(String fontLibraryUrl,String ImgUrl) throws TesseractException {
        ITesseract instance = new Tesseract();
        instance.setDatapath(fontLibraryUrl);
        instance.setLanguage("chi_sim");
        File imgDir = new File(ImgUrl);
        long startTime = System.currentTimeMillis();
        String str = instance.doOCR(imgDir);
        long endTime = System.currentTimeMillis();
        System.out.println(endTime-startTime);
        return str;
    }
}
```
pom.xml:
(Here the version is 4.2.2, and I hva tried 4.2.3, 4.3.0 too.)
```
<dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>4.2.2</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>log4j-over-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

## Error details:
I have packaged for a jar and run it on the linux, and I got the flowing error(the image is exist):
```
[root@localhost tmp]# java -jar OCR-1.0-SNAPSHOT.jar /home/veir/tmp/tessdata /home/veir/tmp/demo_ctpn.png
2018-12-17 03:29:18.333 [main] ERROR net.sourceforge.tess4j.Tesseract - null
java.lang.NullPointerException: null
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:826)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at Test.discern(Test.java:33)
	at Test.main(Test.java:20)
net.sourceforge.tess4j.TesseractException: java.lang.NullPointerException
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)
	at Test.discern(Test.java:33)
	at Test.main(Test.java:20)
Caused by: java.lang.NullPointerException
	at net.sourceforge.tess4j.Tesseract.dispose(Tesseract.java:826)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:239)
	... 3 more
```

## Linux envs:
os:
```
[root@localhost tmp]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@localhost tmp]# uname -r
3.10.0-957.1.3.el7.x86_64
```
jdk: 
```
[root@localhost tmp]# java -version
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
```
tesseract:
```
[root@localhost tmp]# tesseract -v
tesseract 4.0.0-99-g94521
 leptonica-1.75.3
  libjpeg 6b (libjpeg-turbo 1.2.90) : libpng 1.5.13 : libtiff 4.0.3 : zlib 1.2.7

 Found AVX2
 Found AVX
 Found SSE
```

**Comment by hoctester** [comment]
Same issue on Ubuntu 16.04.4 LTS

> 
net.sourceforge.tess4j.TesseractException: java.lang.NullPointerException
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245)
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194)

`<dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId> org.apache.cassandra</groupId>
            <artifactId>cassandra-all</artifactId>
            <version>0.8.1</version>

            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-log4j12</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>

        </dependency>`

**Comment by veir-panda** [comment]
Thanks a lot!

I have solved by install tesseract latest using offical rpm [tesseract wiki](https://github.com/tesseract-ocr/tesseract/wiki).

After that I have met exception like [105](https://github.com/nguyenq/tess4j/issues/105) and soled by using this [way](https://github.com/nguyenq/tess4j/issues/106#issuecomment-437361950).

Thanks a lot again!
