### ISSUE TITLE
Not able to run in amazon server (RHEL)

### ISSUE THREAD

**Issue by Karthikeyantkr** [nguyenq/tess4j#137]
I have tried installing tesseract-ocr-3.02.02.tar.gz and leptonica-1.75.3.tar.gz in my linux machine. along with Ghostscript. 
But I am unable to find why my tesseract program is not working.

It's working well in windows. Please help. I have posted these issue across all the blogs and portal. 

@nguyenq Kindly help me!!!

**Comment by nguyenq** [comment]
More details about the errors would be helpful for anyone wanting to help.

Why didn't you use the latest Tesseract version, 4.0.0?
