### ISSUE TITLE
The PDF created by Tesseract.createDocuments(String[], String[], List<RenderedFormat>) are locked

### ISSUE THREAD

**Issue by bolaumius** [nguyenq/tess4j#139]
I have to deal with a lot of huge PDF files so what I'm doing is: get the PDF file, create 1 different PDF for each page, generate an OCR'd PDF from them and then merge them all into a single PDF (splitting and merging are done by IText). My application crashes when it attempts merge the OCR'd PDFs, right when it tries to open the first file.

If after generating my OCR'd PDFs I simply run the method that merges the OCR'd PDFs it works perfectly, so I'm assuming that the issue is due to tess4j creating those files but without unlocking them so when IText tries to open them it throws an Exception.

**Comment by nguyenq** [comment]
Are you using multiple or a single `RenderedFormat`? In the past, we had a few resource (output file) not released issues, and I believe the fix was calling `TessDeleteResultRenderer` method. If you're using multiple `ResultRenderer`, I wonder if we need to call `TessDeleteResultRenderer` for each one.

**Comment by bolaumius** [comment]
This is how I'm doing it:

`Tesseract tessInst = new Tesseract();
List<RenderedFormat> list = new ArrayList<RenderedFormat>();
list.add(RenderedFormat.PDF);
tessInst.createDocuments(input.getAbsolutePath(), output.getAbsolutePath(), list);`

**Comment by bolaumius** [comment]
I thought that I tess4j 4.X didn't support PDF for some reason (I'm pretty sure I downloaded a version that didn't) so I was using 3.X, after reading your post and finding the newest version it does indeed support PDF and the issue I had was also indeed fixed.

Sorry for wasting your time and thanks for your help.

**Comment by nguyenq** [comment]
You're welcome. Glad the issue was resolved for you.
