### ISSUE TITLE
Tess4j not able to extract font info from a scanned document

### ISSUE THREAD

**Issue by loveleshg** [nguyenq/tess4j#140]
below code does not get font info with tesseract 4.0
String fontName = TessAPI1.TessResultIteratorWordFontAttributes(ri, boldB, italicB, underlinedB,
monospaceB, serifB, smallcapsB, pointSizeB, fontIdB);

fontName return is null , all other attributes return also has wrong values

**Comment by nguyenq** [comment]
https://github.com/tesseract-ocr/tesseract/issues/1074
