### ISSUE TITLE
count >= 0:Error:Assert failed

### ISSUE THREAD

**Issue by schmitzCatz** [nguyenq/tess4j#142]
Hi,

this error occurs currently with the shipped tesseract.dll's for windows. See: https://github.com/tesseract-ocr/tesseract/issues/1664
This has already been fixed by the developer, but the shipped with tess4j are not patched accordingly. 

Please update the binary to a more recent version.

Kind Regards

**Comment by nguyenq** [comment]
How would you reproduce the issue?

**Comment by schmitzCatz** [comment]
Hi,
I used the Lates maven release 4.3.1. Can't get it to work:
        File image = new File("C:/bin/Tess4J/eurotext.tif");
        Tesseract tessInst = new Tesseract();
        tessInst.setDatapath("C://bin//Tess4J");
        try {
            String result= tessInst.doOCR(image);
            System.out.println(result);
        } catch (TesseractException e) {
            System.err.println(e.getMessage());
        }

**Comment by nguyenq** [comment]
We can't reproduce the issue. Do you have VC++ 2015 runtime installed?

Anyway, the datapath setting should include `tessdata`, such as:

`tessInst.setDatapath("C:/bin/Tess4J/tessdata");`

**Comment by nguyenq** [comment]
Not reproducible.
