### ISSUE TITLE
multi-page PDF: cancel  ocr not working

### ISSUE THREAD

**Issue by andron3000** [nguyenq/tess4j#145]
I didn't find any test that describes **cancel OCR operation** for multi-page pdf/tiff document. Even if call:
  ```
  public void cancel() {
        monitor.cancel = (cancelThis, words) -> true;
    }
```

inside ProgressMonitor class, ocr not stopped.

**Comment by andron3000** [comment]
```
class ProgressMonitor extends Thread {

    private ITessAPI.ETEXT_DESC monitor;
    private StringBuilder outputMessage = new StringBuilder();

    ProgressMonitor(ITessAPI.ETEXT_DESC monitor) {
        this.monitor = monitor;
    }

    public String getMessage() {
        return outputMessage.toString();
    }

    @Override
    public void run() {
        try {
            while (true) {
                System.out.println("ocr alive: " + (monitor.ocr_alive == TRUE));
                System.out.println("progress: " + monitor.progress);

                outputMessage.append(monitor.more_to_come);
                if (monitor.progress >= 100) {
                    System.out.println("Call to cancel...");
                    cancel();
                    break;
                }
                Thread.sleep(1000);
            }
        } catch (Exception ioe) {
            ioe.printStackTrace();
        }
    }

    /**
     * Cancels OCR operation.
     */
    public void cancel() {
        monitor.cancel = (cancelThis, words) -> true;
    }

    /**
     * Resets cancel flag.
     */
    public void reset() {
        monitor.cancel = null;
    }
}
```

**Comment by andron3000** [comment]
My code:

        api.TessBaseAPISetImage2(handle, pix);
        api.TessBaseAPIRecognize(handle, monitor);

        ProgressMonitor progressMonitor = new ProgressMonitor(monitor);
        progressMonitor.start();

        int result = api.TessBaseAPIProcessPages(handle, imageFile.getAbsolutePath(), null, 0, renderer);

        if (result == ITessAPI.FALSE) {
            throw new TesseractException("Error during processing page.");
        }

        api.TessBaseAPIMeanTextConf(handle);

**Comment by nguyenq** [comment]
It's been a long while since we last looked into this area. You may want to look at the new `TessMonitor` API available since Tesseract 4.0.0 release. Tesseract project may have C examples demontrating usage of these new API that you may be able to adapt to Java.

**Comment by andron3000** [comment]
Thanks

**Comment by nguyenq** [comment]
https://github.com/tesseract-ocr/tesseract/blob/master/unittest/progress_test.cc

**Comment by nguyenq** [comment]
@andron3000 Did you ever get it to work?

**Comment by nguyenq** [comment]
No response from OP.
