### ISSUE TITLE
Tesseract creates PDF documents with "GlyphLessFont " font Using 4.0

### ISSUE THREAD

**Issue by dharam116** [nguyenq/tess4j#146]
Hi ,

I am working on tesseract, converting tiff to searchable PDF.  Some files are converting right but some file having "GlyphLessFont" font .  Can I resolved this issue. ?

I am using Tesseract Open Source OCR Engine v4.0.0.20181030 with Leptonica Version of Tesseract.

**Comment by nguyenq** [comment]
Does it also happen with running Tesseract on the command line?

**Comment by nguyenq** [comment]
No response from OP.
