### ISSUE TITLE
Hi nguyenq

### ISSUE THREAD

**Issue by madhuse** [nguyenq/tess4j#147]

**Comment by madhuse** [comment]
Downloading the Tesseract means i have to download the Source code of the Tesseract.
after that i have perform below steps
 $ tar xzf tesseract-ocr-3.02.02.tar.gz
 $ cd tesseract-3.01
 $ ./autogen.sh
 $ ./configure
 $ make
 $ sudo make install
 $ sudo ldconfig

please help me sir

**Comment by nguyenq** [comment]
That's a very old version of Tesseract! Please visit [Tesseract](https://github.com/tesseract-ocr/tesseract/wiki) site for instructions on how to compile or install on Linux.

**Comment by madhuse** [comment]
Hi sir iam running Tess4J version4.3.1 in my windows successfully.
for that libtesseract400.dll file is generated .
In the next implementation i need to use the Hindi language files .
iam confused  about which version of Tesseract iam using?

Please provide link to download the Hindi trained data file for Tess4J 4.3.1.

**Comment by nguyenq** [comment]
The `.traineddata` files are available from Tesseract site. You'd need to look under `tessdata*` folders.

**Comment by madhuse** [comment]
Which version of Tesseract .trained files i  need to download? , to recognise Hindi text
 iam using Tess4J  4.3.1 in windows .

T

**Comment by nguyenq** [comment]
Did you read through Tesseract website?

https://github.com/tesseract-ocr/tesseract/wiki/Data-Files

**Comment by madhuse** [comment]
Hi 
Iam running tess4j 4.3.0 in windows successfully able to recognize the eng and hindi  text perfectly .
my problem is when i convert the tess4j 4.3.0 maven project into Simple java project, hindi text is not able to recognize i have added the dll files and all the jars and eng.trained data and hin.trained data.
can u please tell me why iam not able to recognize hindi text.

Thank you

**Comment by nguyenq** [comment]
You do not need to mess with the DLLs. Please follow the [tutorial](http://tess4j.sourceforge.net/tutorial/).

**Comment by nguyenq** [comment]
Do you still have a problem? Can this ticket be closed?

**Comment by nguyenq** [comment]
No response from OP.
