### ISSUE TITLE
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.

### ISSUE THREAD

**Issue by changetoblow** [nguyenq/tess4j#149]
Hello, I now use the tess4j API to identify images in Tika, and there is no problem when I only deal with images, but I have a problem when I deal with word file, because there are embedded images in the word file, and the error information is as follows:

17:33:28.423 [main] ERROR net.sourceforge.tess4j.Tesseract - Unsupported image format. May need to install JAI Image I/O package. https://github.com/jai-imageio/jai-imageio-core java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package. https://github.com/jai-imageio/jai-imageio-core at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214) at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194) at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397) at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72) at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139) at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156) at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) at org.apache.tika.Tika.parseToString(Tika.java:608) at org.apache.tika.Tika.parseToString(Tika.java:723) at com.tika.test.tt.main(tt.java:20) 17:33:28.423 [main] WARN org.apache.tika.parser.ocr.TesseractOCRParser - java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package. https://github.com/jai-imageio/jai-imageio-core net.sourceforge.tess4j.TesseractException: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package. https://github.com/jai-imageio/jai-imageio-core at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:245) at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:194) at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:397) at org.apache.tika.parser.ocr.TesseractOCRParser.parse(TesseractOCRParser.java:242) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) at org.apache.tika.parser.DelegatingParser.parse(DelegatingParser.java:72) at org.apache.tika.extractor.ParsingEmbeddedDocumentExtractor.parseEmbedded(ParsingEmbeddedDocumentExtractor.java:104) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedFile(AbstractOOXMLExtractor.java:391) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedPart(AbstractOOXMLExtractor.java:264) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.handleEmbeddedParts(AbstractOOXMLExtractor.java:206) at org.apache.tika.parser.microsoft.ooxml.AbstractOOXMLExtractor.getXHTML(AbstractOOXMLExtractor.java:139) at org.apache.tika.parser.microsoft.ooxml.OOXMLExtractorFactory.parse(OOXMLExtractorFactory.java:156) at org.apache.tika.parser.microsoft.ooxml.OOXMLParser.parse(OOXMLParser.java:110) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:280) at org.apache.tika.parser.AutoDetectParser.parse(AutoDetectParser.java:143) at org.apache.tika.Tika.parseToString(Tika.java:608) at org.apache.tika.Tika.parseToString(Tika.java:723) at com.tika.test.tt.main(tt.java:20) Caused by: java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package. https://github.com/jai-imageio/jai-imageio-core at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:214) ... 20 common frames omitted

I have checked in two ways , first by using maven repository i.e

<dependency>
<groupId>com.github.jai-imageio</groupId>
<artifactId>jai-imageio-core</artifactId>
<version>1.4.0</version>
</dependency>

 Secondly , I have also checked by including the jar i.e jai-imageio-core-1.4.0.jar
In both ways I am getting the same error , how can I fix this?

**Comment by nguyenq** [comment]
Because Word is not an image file. You'd need to print it to an image or PDF format first.

**Comment by changetoblow** [comment]
Hello, I follow your idea, and I find that the culprit of this problem is that when tika parses the embedded image in word, it finally parses into a temporary file with suffix TMP and sends it to tess4j for identification, but tess4j cannot recognize this file.So how to modify the type generated by tika to adapt to tess4j? Can you give me some ideas

**Comment by changetoblow** [comment]
resolved

**Comment by vijayalangaram** [comment]
@changetoblow  @nguyenq  

same error for me  unable to resolve even after applied data path and image io core jar and dependency .

**Is it possible to doocr on mongodb stored image .**

**It's Perfectly working for local image file and Is it possible for stored image in mongodb ?**
 
**got a errors regarding jar file and i was correctly added dependency nd jar cross checked with version also but unable to resolve.**
Can please guide me !!


```
public static void main(String[] args) {
		SpringApplication.run(JavalocaldoocrApplication.class, args);		
		Mongo mongodb = new MongoClient("localhost", 27017);		
		DB db = mongodb.getDB("test-db");	
		DBCollection collection = db.getCollection("user");		
               **File image = new File("mongodb://localhost:27017//test-db//user");**	
	    Tesseract tessInst = new Tesseract();     	   
          //	    tessInst.setDatapath("C:\Program Files (x86)\Tesseract-OCR\tessdata");
	    final String datapath =  "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata";	    		
	    tessInst.setDatapath (new File("datapath").getPath());   
	    try {
	          String result= tessInst.doOCR(image);
	          System.out.println(result);
	       } catch (TesseractException e) {
	          System.err.println(e.getMessage());
		 }		 }}
```


![2019-11-06 19_24_36-](https://user-images.githubusercontent.com/48197654/68388466-b0b32f80-0186-11ea-9be3-41662efc0006.png)
