### ISSUE TITLE
libtesseract400.dll Compilation problems

### ISSUE THREAD

**Issue by changetoblow** [nguyenq/tess4j#150]
@nguyenq Hello, I want to know under tess4j libtesseract500. How the DLL is compiled, I try to use the https://github.com/tesseract-ocr/tesseract source code to compile, but it is especially big, and can't use, need any particular way

**Comment by nguyenq** [comment]
Please refer to [Compiling Tesseract and Libleptonica (using vcpkg)](https://github.com/charlesw/tesseract/wiki/Compiling-Tesseract-and-Libleptonica-(using-vcpkg)) page for instructions on how to build Tesseract and Leptonica DLLs.

**Comment by changetoblow** [comment]
@nguyenq Thanks for your advice
