### ISSUE TITLE
Different result between native and java calls

### ISSUE THREAD

**Issue by belkevglaz** [nguyenq/tess4j#151]
Hi nguyenq.
I faced with weird issue. I have binarazed picture with one word and tried to get word's boundaries.
In case of native call `tesseract material.png materail -l rus+eng tsv` I got result:

> level	page_num	block_num	par_num	line_num	word_num	left	top	width	 height	conf	text
> 1	1	0	0	0	0	0	0	230	86	-1	
> 2	1	1	0	0	0	29	23	191	41	-1	
> 3	1	1	1	0	0	29	23	191	41	-1	
> 4	1	1	1	1	0	29	23	191	41	-1	
> 5	1	1	1	1	1	29	23	191	41	96	Материал

In case of java call ( set only lang and datapath, nothing more)
`		tesseract1.setLanguage("eng+rus");
		tesseract1.setDatapath("/usr/share/tesseract-ocr/4.00/tessdata");`
I got result rectangle
> 29.0	24.0	190.0	40.0

It is possible that java set any tesseract params implicitly ? 
The test picture is very simple.
![MaxEntropy](https://user-images.githubusercontent.com/4264068/58815733-ce58f780-8630-11e9-9f7c-e8e5e35ea073.png)
Could you please help to understand what is a problem of this difference ?
My environment is :
> $ tesseract -v
tesseract 4.0.0
 leptonica-1.76.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 1.5.2) : libpng 1.6.36 : libtiff 4.0.10 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.0
 Found AVX2
 Found AVX
 Found SSE

> $ sudo apt list --installed | grep tesseract
> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
> libtesseract4/disco,now 4.0.0-2 amd64 [installed,automatic]
> tesseract-ocr-eng/disco,disco,now 1:4.00~git30-7274cfa-1 all [installed,automatic]
> tesseract-ocr-osd/disco,disco,now 1:4.00~git30-7274cfa-1 all [installed,automatic]
> tesseract-ocr-rus/disco,disco,now 1:4.00~git30-7274cfa-1 all [installed]
> tesseract-ocr/disco,now 4.0.0-2 amd64 [installed]

**Comment by nguyenq** [comment]
You invoked the CLI with `tsv` option; you should call likewise with the API. In `tsv` file in `tessdata\config` folder, there is a setting for `tessedit_create_tsv` variable. Try to do the same using API.

**Comment by belkevglaz** [comment]
I used the same variable from `/usr/share/tesseract-ocr/4.00/tessdata/configs/tsv` where in tsv file content `tessedit_create_tsv 1`

> tesseract1.setLanguage("eng+rus");
> tesseract1.setDatapath("/usr/share/tesseract-ocr/4.00/tessdata");
> tesseract1.setTessVariable("tessedit_create_tsv", "1");

The result the same as in previous tests.

**Comment by nguyenq** [comment]
You will need to use the new `TsvRenderer` methods available in Tesseract-5.0.0 alpha version. Try the latest from Git repository.

**Comment by belkevglaz** [comment]
Hi, nguyenq
Thanks for your response. I think that I found root of cause and it is in ImageIO itself (that I use for work with images), not in TessJ4.
I have binarized picture saved by ImageIO in`bmp` format. If I pass this image to tesseract over CLI - blocks recognized very well, bu if I reads this image again through ImageIO and pass to tess4j - I got wrong results as I mentioned in initial post. 
To solve this, applied additional processing on image - save as `BufferedImage.TYPE_BYTE_BINARY` type to clear color model.
I suppose you can close this issue.
