### ISSUE TITLE
Add support for `tessedit_write_images` config parameter

### ISSUE THREAD

**Issue by CoeJoder** [nguyenq/tess4j#152]
Currently this config option has no effect in Tess4J.  It's supposed to cause Tesseract to write the post-processed OCR image to `tessinput.tif`.  It's important for fine-tuning the OCR quality.

I've created a SSCCE for testing this feature:
https://github.com/CoeJoder/sample_writeimages

**Comment by nguyenq** [comment]
You can call `GetThresholdedImage` to obtain the images.

**Comment by CoeJoder** [comment]
Thanks for the reply.  The problem with that solution is that it is not injectable.  The library classes `Tesseract` or `Tesseract1` would have to be subclassed to get access to protected API object, and the `getOCR` method overridden so that `GetThresholdImage` is called before `TessBaseAPIDelete`.  Popular frameworks which use Tess4j, such as Sikulix, insantiate `Tesseract1` directly and so you wouldn't be able t swap in a custom object.

Would you consider a PR where the OCR method checks for the `tessedit_write_images` option and calls `GetThresholdedImage` conditionally?

**Comment by nguyenq** [comment]
In [Tesseract code](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/baseapi.cpp), if the call invokes `ProcessPage` API method, then the `tessedit_write_images` parameter will be considered.

I modified `testResultRenderer` test case with the following, and it produced `tessinput.tif` at the project's root directory.

```
        String[] params = {"tessedit_write_images"};
        String vals[] = {"1"};
```

If you still think it still does not meet your needs, please submit a PR.

Thanks.

**Comment by nguyenq** [comment]
`createDocuments` method would also check for this parameter, if set.

**Comment by CoeJoder** [comment]
Seems like this option is only intended for certain operations, and Tess4j is working as intended.  It would be helpful for my purposes if this option was more widely applicable, but I think it's a better suggestion for the Tesseract project itself.  Thanks
