### ISSUE TITLE
Tess4j 4.3.1 java.lang.UnsatisfiedLinkError: The specified module could not be found.

### ISSUE THREAD

**Issue by phyrumsk** [nguyenq/tess4j#153]
Hi, I try Tess4j 4.3.1 wrapper with Java. 
My System is Windows 10 64bit. 
I already installed JDK 1.8, Visual C++ 2015-2019 (x64) & 
JAR files that are included in the projects: 
lept4j-1.12.0.jar
tess4j-4.3.1.jar
jna-5.3.1.jar
commons-io-2.6.jar
ghost4j-1.0.1.jar
jai-imageio-core-1.4.0.jar
jboss-vfs-3.2.14.Final.jar
jul-to-slf4j-1.7.26.jar
log4j-1.2.17.jar
pdfbox-2.0.12.jar
pdfbox-tools-2.0.12.jar
slf4j-api-1.7.26.jar
slf4j-log4j12-1.7.26.jar

When calling "doOCR(imageFile)", It gave error "Exception in thread "main" java.lang.UnsatisfiedLinkError: The specified module could not be found." 

I checked C:\Users\phyrum\AppData\Local\Temp\tess4j\win32-x86-64. 
There are : 
liblept1744.dll
liblept1770.dll
liblept1780.dll
libtesseract3051.dll
libtesseract400.dll

Sample of my codes: 
```
String  inputFileName;
Scanner input_image_file = new Scanner( System.in ); 
System.out.print("Input File Name: ");
inputFileName = input_image_file.nextLine().trim();
File imageFile = new File(inputFileName);
ITesseract instance = new Tesseract();  // JNA Interface Mapping
final String dir = System.getProperty("user.dir");
instance.setDatapath(dir+"/tessdata");
try {
    	instance.setLanguage("khm");
        String resultKhm = instance.doOCR(imageFile);
        System.out.println(resultKhm);
} catch (TesseractException e) {
	System.err.println(e);
}
```

I don't know the real cause of this error. I've search and read some opened issues. but it can't help.
Any suggestion or solution?

_Originally posted by @phyrumsk in https://github.com/nguyenq/tess4j/issues/95#issuecomment-502038847_

**Comment by nguyenq** [comment]
On Windows, tess4j-4.3.1 must go with lept4j-1.10.0 because `libtesseract400.dll` is statically linked against `liblept1760.dll`.

**Comment by phyrumsk** [comment]
@nguyenq Thanks so much. It works after replacing lept4j-1.12.0.jar with lept4j-1.10.0.jar.

**Comment by phyrumsk** [comment]
Hi, Tess4j 4.3.1 & lept4j-1.10.0.jar works fine when running using Eclipse in windows as tess4j folder and required DLL files were automatically extracted in C:\Users\phyrum\AppData\Local\Temp\. 

However, while export the application to JAR file with option that "Package required libraries into generated JAR".  tess4j folder did not automatically extract to temp folder which causes **"java.lang.UnsatisfiedLinkError: The specified module could not be found. ".**
If I manually copy the tess4j and required DLLs, then the program work fine. 

Any suggestion?
