### ISSUE TITLE
createDocuments API limited to image filename instead of byte[] 

### ISSUE THREAD

**Issue by harelfar2** [nguyenq/tess4j#154]
Can you please add additional api to the ocr with rendering please, so we will be able to infer the `createDocuments()` method with `BufferedImage`? 
From my testings, this api is much better than the `doOcr()`, and is equivalent to the command line usage. 
The fact that you have to give a `path` in order to infer, makes the program a little cumbersome because if you're only given `byte[]`, you will have to create and save a temp file, and read it again.

**BTW 1**: Why `doOcr()` is more common and everyone uses it, and not `createDocuments()`? 
**BTW 2**: Now that we still can't use `BufferedImage` as parameter to  `createDocuments()`, does anyone know how to create a file in memory so we could use its path to `createDocuments()`?
I tried to use `DefaultFileSystemManager` with `RamFileProvider` as suggested [here](https://stackoverflow.com/questions/17595091/how-to-create-new-java-io-file-in-memory/17595303#comment30938295_17595282) but I got lost due to lack of documentation. Can someone provide some code examples?
Thanks ahead.

**Comment by nguyenq** [comment]
The most common usage is specifying filenames as input, such as at the CLI.  `doOCR` is widely used because it produces direct text output.

New APIs similar to `createDocuments` have been added to support buffered images as input. Please check it out from the Repo.

Thanks.

**Comment by harelfar2** [comment]
Thanks a lot! that really helps me.

**Comment by harelfar2** [comment]
Thank you for the quick response and method overload.
But the whole point of my request was to not deliver the filename as parameter, because I'm in a situation that I'm only getting the image bytes and the file doesn't exist in my system. 
Can you make it work that way? 
Thanks ahead!

**Comment by nguyenq** [comment]
That `filename` parameter is optional --  it can be `null` or any `string`; it's used as title for some file types, such as hocr.

**Comment by harelfar2** [comment]
Got it.
Thanks again!

**Comment by nguyenq** [comment]
Can this be closed?

**Comment by harelfar2** [comment]
Yes closing
