### ISSUE TITLE
 Tess4j 4.3.1: DLL files are not automatically extracted which causes Error: java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by phyrumsk** [nguyenq/tess4j#155]
Hi, Tess4j 4.3.1 & lept4j-1.10.0.jar works fine when running using Eclipse in windows as tess4j folder and required DLL files were automatically extracted in C:\Users\phyrum\AppData\Local\Temp\. 

However, while export the application to JAR file with option that "Package required libraries into generated JAR".  tess4j folder did not automatically extract to temp folder which causes **"java.lang.UnsatisfiedLinkError: The specified module could not be found. ".**
If I manually copy the tess4j and required DLLs, then the program work fine. 

Any suggestion?

_Originally posted by @phyrumsk in https://github.com/nguyenq/tess4j/issues/153#issuecomment-503572288_

**Comment by nguyenq** [comment]
You may want to post your question on StackOverflow for assistance in this regard.

**Comment by phyrumsk** [comment]
Ok I will post on StackOverflow. Thanks very much.
