### ISSUE TITLE
Why DetectOS is not supported?

### ISSUE THREAD

**Issue by vipulpatel2103** [nguyenq/tess4j#156]
I want the orientation angle of an Image. Here I face that there is not a wrapper method exist to detect orientation angle. What is the alternative solution or why DetectOS does not exist?

**Comment by nguyenq** [comment]
Does `DetectOS` exist in [capi](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/capi.h) interface?

You can use `TessBaseAPIDetectOrientationScript`.

**Comment by vipulpatel2103** [comment]
No, it's not there. 

I tried with TessBaseAPIDetectOrientationScript, but it's not giving me a correct orientation angle. I checked the test-case "TessAPI1Test.testTessBaseAPIDetectOrientationScript()", but I think it's not correct.  The orientation angle of the test image is 0, but it's giving 270. 

Can you please tell me why it's wrong or am I doing something wrong?

**Comment by nguyenq** [comment]
The input language parameter should be set to `osd`.

https://github.com/tesseract-ocr/tesseract/blob/master/unittest/osd_test.cc

**Comment by vipulpatel2103** [comment]
Thanks, @nguyenq for your help.
