### ISSUE TITLE
Getting "Warning: Invalid resolution 0 dpi. Using 70 instead." for PDF files. Use 300 DPI for PDF or let user set DPI.

### ISSUE THREAD

**Issue by NguyenAndrew** [nguyenq/tess4j#157]
Hello! Thank you for this open source project.

I was testing OCRing a PDF file using this library, and noticed I was getting this warning in my tests: `Warning: Invalid resolution 0 dpi. Using 70 instead.` I believe this might be an error in Tess4J, as I would have believed the default would have been 300 dpi for a document (and not 0 dpi). Can this functionality be fixed? Might also be useful to have something like

```
tesseract.setDPI(300)
tesseract1.setDPI(300)
```

which would also solve the problem!

Thanks again!
Andy Nguyen

**Comment by aivanovski** [comment]
Tesseract CLI program has option --dpi, which according its source code do this:
`api.SetVariable("user_defined_dpi", dpi_string);`


Here is solution in Java which works in my machine:
```
Tesseract tesseract = new Tesseract()
tesseract.setTessVariable("user_defined_dpi", "270");
```


[Link to Tesseract CLI source code](https://github.com/tesseract-ocr/tesseract/blob/8dc33b9815268da4e206f431168a1a88b0c7794a/src/api/tesseractmain.cpp#L678)

**Comment by NguyenAndrew** [comment]
@aivanovski Awesome! `tesseract.setTessVariable("user_defined_dpi", "300");` worked for me, and got rid of the warning!

**Comment by nguyenq** [comment]
Fixed in commit https://github.com/nguyenq/tess4j/commit/414ee6adcff0d6f8d774735285fea96b7d8e478f.
