### ISSUE TITLE
TessBaseAPIDetectOrientationScript : Getting wrong orientation angle

### ISSUE THREAD

**Issue by vipulpatel2103** [nguyenq/tess4j#158]
My goal is to find orientation angle and I am using "TessBaseAPIDetectOrientationScript" to detect the angle.

below is sample code:

```
public void detectOrientation(Pix srcPix) {
    TessBaseAPI handle = TessAPI1.TessBaseAPICreate();
    TessAPI1.TessBaseAPIInit3(handle, "tessdata", "osd");
    TessAPI1.TessBaseAPISetImage2(handle, srcPix);
    IntBuffer orientDegB = IntBuffer.allocate(1);
    FloatBuffer orientConfB = FloatBuffer.allocate(1);
    PointerByReference scriptNameB = new PointerByReference();
    FloatBuffer scriptConfB = FloatBuffer.allocate(1);
    int result = TessAPI1
        .TessBaseAPIDetectOrientationScript(handle, orientDegB, orientConfB, scriptNameB,
            scriptConfB);
    if (result == TRUE) {
      angle = orientDegB.get();
    }
  }
```
It's working fine but not always and calculate the wrong orientation angle.
I have attached the sample image (tiff format). The actual angle of this image is 0 degree but returns 180 degrees.

[Source Image.zip](https://github.com/nguyenq/tess4j/files/3436858/Source.Image.zip)

**Comment by nguyenq** [comment]
We should know that the results from Tesseract OCR engine are not always accurate; Tess4J just reflects that. For instance:

`tesseract.exe C:\Temp\ActualImage.tif stdout --psm 0`

```
Page 1
Warning. Invalid resolution 0 dpi. Using 70 instead.
Page number: 0
Orientation in degrees: 180
Rotate: 180
Orientation confidence: 2.43
Script: Cyrillic
Script confidence: 2.49
```

I suggest you create a new issue at [Tesseract project site](https://github.com/tesseract-ocr/tesseract/issues). Be sure to attach your example images.

**Comment by vipulpatel2103** [comment]
Hi @nguyenq, Thanks for this result.
