### ISSUE TITLE
Cannot delete file after OCR

### ISSUE THREAD

**Issue by julbaril** [nguyenq/tess4j#16]
The following code throws java.io.IOException: Unable to delete file: multipage_tif_example.pdf

#######################
File input = new File("multipage_tif_example.tif");
Tesseract1 instance = new Tesseract1();
instance.createDocuments(input.getPath(), input.getPath() , Arrays.asList(RenderedFormat.PDF));
File output = new File("multipage_tif_example.tif.pdf");
FileUtils.forceDelete(output);
##########################

Is there a handle kept by Tess4j on the output files?
Is there there a way to remove that handle?

**Comment by 4F2E4A2E** [comment]
Is that the whole function? Any extra code? Example tif for us to be able to reproduce? Log files? Tess4j version?

**Comment by julbaril** [comment]
Yes this is the whole function, the example tif is the one included in tess4j named "multipage_tif_example.tif", for some reason Github won't allow me to host it in this reply. 

The Tess4j version is the latest on Github, we downloaded it less than 30 minutes ago to see the problem was still an issue with the latest and it seems to be the case.

This is everything we could gather from the console : 

Exception in thread "main" java.io.IOException: Unable to delete file: multipage_tif_example.tif.pdf
	at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1390)
	at app.TessTest.main(TessTest.java:20)
Page 1
Page 2
Page 3
Page 4
Page 5
Page 6

**Comment by nguyenq** [comment]
Can you please try with v2.0.0?

**Comment by 4F2E4A2E** [comment]
I will take a look, but Quan is right, why are you guys not using a maven release?
Which OS?

**Comment by julbaril** [comment]
Hey guys,

I just tried it out with v2.0.0, the function is executed without any exception and the outcome is the one expected. I will do a few more tests later to see if it works with other cases.

OS is Windows 8.1

Thanks.

**Comment by 4F2E4A2E** [comment]
All tests passed on Windows 8.1. I am closing this issue, thanks fpr reporting.
