### ISSUE TITLE
Encounter NoSuchMethodException when using version 4.4.0

### ISSUE THREAD

**Issue by tsengfhy** [nguyenq/tess4j#161]
I got that Tess4j 4.4.0 depends on a different version of JNA in contrast with the pom.xml show in master branch, in that case, Native.load() can't work. But when I change it to 4.3.1 it works well.

**Comment by tsengfhy** [comment]
Yes, I even can't run a simple case if only depend on that with version 4.4.0.

**Comment by nguyenq** [comment]
JNA 5.x.x is a specified requirement for Tess4J 4.4.0.

**Comment by tsengfhy** [comment]
I‘m so sorry, but kindly let me know why does this happen?
![test](https://user-images.githubusercontent.com/33931266/64023586-37d29e80-cb6b-11e9-966f-62d0bb933bf4.jpg)

**Comment by nguyenq** [comment]
You still have jna-4.5.2 somewhere in your machine. Try to do a clean-up. You can delete JNA files downloaded to your `.m2` folder and try to run it again. It should download the latest.

**Comment by nguyenq** [comment]
Did you manage to resolve the dependency conflicts?

**Comment by tsengfhy** [comment]
I tried to clean up my local maven repository and run a simply case with that of version 4.4.0, but it also didn't work. At last i decided to use that of version 4.3.1.
Despite this, thanks a lot for your help.

**Comment by nguyenq** [comment]
According to the aforementioned articles, you should place JNA as a direct dependency at the top of your POM to force that preferred version load first.

```
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.4.0</version>
        </dependency>
```

**Comment by JuNiOnGithub** [comment]
Hi, 

I got almost the same issue : 
`Java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85) ~[tess4j-4.4.0.jar:4.4.0]
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42) ~[tess4j-4.4.0.jar:4.4.0]
	at net.sourceforge.tess4j.Tesseract.init(Tesseract.java:427) ~[tess4j-4.4.0.jar:4.4.0]
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:223) ~[tess4j-4.4.0.jar:4.4.0]
	at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:195) ~[tess4j-4.4.0.jar:4.4.0]`

I got the correct version of JNA and the same version of Tess4J
![image](https://user-images.githubusercontent.com/45942347/65675017-c55fbc00-e04d-11e9-9617-8f2494ab46b3.png)

The Tess4J 4.3.1 seems to work fine tho.

**Comment by nguyenq** [comment]
[tess4j-4.4.1](https://github.com/nguyenq/tess4j/releases/tag/tess4j-4.4.1) has been released to address the issue.
