### ISSUE TITLE
pdf output file size

### ISSUE THREAD

**Issue by nibi79** [nguyenq/tess4j#162]
hi, I've a question.

When I ocr a document the size of the output file is much bigger than the input file.
e.g. the input pdf has 0.39 MB the output pdf has 1,3 MB. I'm not sure but it seems that the image in the pdf file is stored with higher dpi.
How can I decrease the file size?

**Comment by nguyenq** [comment]
Tess4J converts PDF to images in fixed 300-DPI resolutions (for optimal recognition results) before sending them to Tesseract, which produces the searchable PDF. You may want to convert PDF yourself in desired resolutions to achieve smaller file size output.

**Comment by nibi79** [comment]
thank you for your answer.

I attached my input and output file. Perhaps you can take a look on these two files?

[output.pdf](https://github.com/nguyenq/tess4j/files/3564873/output.pdf)
[input.pdf](https://github.com/nguyenq/tess4j/files/3564875/input.pdf)

Can you explain to me why the output file is so much bigger?  Is that normal?

**Comment by nguyenq** [comment]
I've offered my explanation.

**Comment by nibi79** [comment]
when I use 
_System.setProperty("pdf.library", "pdfbox");_
the file has only 0,69MB
