### ISSUE TITLE
Is there a way to set multiple paths for tess4j to find data files?

### ISSUE THREAD

**Issue by Mararsh** [nguyenq/tess4j#164]
Hi, nguyenq,
Thank you for your great efforts!
I am embedding your works in my project. I have following question: Is there a way to set multiple paths for tess4j to find data files?
tess4j already includes subpath "tessdata" which provide 2 data files: eng(15M) and osd(10M) and can recoginze English out of box. 
In my project, I will pack 4 Chinese data files to help users not download by themselves. And I want to use 2 data files included in tess4j too. Meawhile I want to permit users define their tessdata path if they've installed tesseract or have download some other data files.
One solution for my plan is to copy all these data files under one path. But I feel this way is not good since more disk usage and cpu time are need.
So I am thinking is it possible tess4j could find data files under multiple paths?  
Best Regards. Thanks in advance!

**Comment by Mararsh** [comment]
My final solution is to download data files in "Fast" set 
   https://github.com/tesseract-ocr/tessdata_fast  
which are small enough, quick enough, and good enough. If user defines tessdata path, my tool will check whether the expected language files under it and copy files to it if not exist.
Best Regards.

**Comment by nguyenq** [comment]
Yes, that is a sensible solution: moving the downloaded data files to the `tessdata` folder, as we're not sure if Tesseract would support multiple datapaths.
