### ISSUE TITLE
eng.traineddata from tessdata_best

### ISSUE THREAD

**Issue by balmma** [nguyenq/tess4j#166]
What's the reason to include the pure tessdata_best (non integerized) traineddata in Tess4J?

Wouldn't it be more appropriate to include either an integerized version of tessdata_best or even tessdata_fast? Perfomance would be 4 to 5 times better without any serious compromise in accuracy. Additionally the traineddata model size is much smaller.

**Comment by balmma** [comment]
We have an ongoing discussion about this topic in the SikuliX project:
RaiMan/SikuliX1@10eb379

**Comment by nguyenq** [comment]
Yes, `tessdata_fast` should be used, as it was recommended. We thought the project had it all along. We updated VietOCR project with `fast` data two years ago, but forgot to do the same with Tess4J. Thanks for pointing it out. Will make a new release soon for this update.

**Comment by balmma** [comment]
I see you've already commited the other file, thanks.

Will close the issue.
