### ISSUE TITLE
getting started with tess4J

### ISSUE THREAD

**Issue by duvachat** [nguyenq/tess4j#168]
I would like to use tess4J but I cannot find the getting started guide with tess4J.

**Comment by nguyenq** [comment]
You did not look in Wiki page. [Project site](http://tess4j.sf.net/) also has documentation.

**Comment by duvachat** [comment]
Thanks for the answer, but I did look to Wiki page and I was unable to understand, trying to get a document called "Getting Start with tess4J". I tried to use "ant" but it did not work, not recognizing the pom.xml file. My version of Eclipse also did not recognize the xml files.
Finally I simply replaced the tess4J et Lept4J jar files, coming from tess4J sourceforge, bpy the new ones and it works (except an issue on dpi resolution which seems to have nothing to do with the update.
 
Thanks again.
 
 
 
 
> Message du 09/11/19 23:38> De : "Quan Nguyen" > A : "nguyenq/tess4j" > Copie à : "duvachat" , "Author" > Objet : Re: [nguyenq/tess4j] getting started with tess4J (#168)> >
> You did not look in Wiki page. Project site also has documentation.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5HROGIP7SKFU4Q3CE3QS43XBA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDUQZ3Q#issuecomment-552144110", "url": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5HROGIP7SKFU4Q3CE3QS43XBA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEDUQZ3Q#issuecomment-552144110", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by nguyenq** [comment]
Ant was the old build system used. Maven is the current one.

**Comment by duvachat** [comment]
OK, Thanks
 
 
 
 
> Message du 22/11/19 00:56> De : "Quan Nguyen" > A : "nguyenq/tess4j" > Copie à : "duvachat" , "Author" > Objet : Re: [nguyenq/tess4j] getting started with tess4J (#168)> >
> Ant was the old build system used. Maven is the current one.
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5AVOOF45G24WIC7NNLQU4NZDA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE4B2SQ#issuecomment-557325642", "url": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5AVOOF45G24WIC7NNLQU4NZDA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE4B2SQ#issuecomment-557325642", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by nguyenq** [comment]
Can this ticket be closed?

**Comment by duvachat** [comment]
Yes it is,
 
Thanks
 
 
 
 
> Message du 28/11/19 15:36> De : "Quan Nguyen" > A : "nguyenq/tess4j" > Copie à : "duvachat" , "Author" > Objet : Re: [nguyenq/tess4j] getting started with tess4J (#168)> >
> Can this ticket be closed?
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5GJYE6J27TU2FC4UCLQV7JQBA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFMY5MA#issuecomment-559517360", "url": "https://github.com/nguyenq/tess4j/issues/168?email_source=notifications\u0026email_token=ALEXK5GJYE6J27TU2FC4UCLQV7JQBA5CNFSM4JLJVAQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFMY5MA#issuecomment-559517360", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
