### ISSUE TITLE
CentOS 7 error at tesseract::Tesseract::recog_all_words

### ISSUE THREAD

**Issue by eisenreich** [nguyenq/tess4j#172]
I'm developing an application to detect the text of a canvas inside the browser. The development environment is Windows 10 and everything works well.

When I like to run this on the build-machine with CentOS 7 the following error occur. Btw. on the machine I installed the following packages: `tesseract`, `tesseract-langpack-deu` and `tesseract-devel.x86_64`. Tesseract Version is `3.04.00.`.

**Error:**
```
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f47388f3a5f, pid=7637, tid=0x00007f475092f700
#
# JRE version: OpenJDK Runtime Environment (8.0_212-b04) (build 1.8.0_212-b04)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b04 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so+0xc3a5f]  tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+0x5bf
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```

I already tried to set the locale regarding different bug reports, but without success.

The current locale on the machine is: 
```
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

I tried the following commands without success:
`export LC_ALL=C` and 
```
export LC_ALL=C
export LANG=C
export LANGUAGE=C
```

If the whole error.log file is needed, just tell me.

**Comment by nguyenq** [comment]
That looks like a very old Tesseract version. The error may not be related to locale. Can you try with newer versions, such as 4.1.0?

**Comment by nguyenq** [comment]
Can the ticket be closed?
