### ISSUE TITLE
Orientation confidence returned by TessBaseAPIDetectOrientationScript

### ISSUE THREAD

**Issue by kamrapooja** [nguyenq/tess4j#173]
Hi,
TessBaseAPIDetectOrientationScript gives orientation confidence and script confidence.
What are the minimum and maximum values of confidence.
I got orientation confidence 8-15 for set of images. What is range of good confidence?

**Comment by nguyenq** [comment]
From the comments in the [code](https://github.com/tesseract-ocr/tesseract/blob/master/src/api/baseapi.cpp):

> 15.0 is reasonably confident

0 appears to be the minimum.

**Comment by kamrapooja** [comment]
Confidence on some images range from between 1 - 5. What 1 implies or 5. 
Is it confidence percentage or something else. Please help
What is maximum confidence?

**Comment by nguyenq** [comment]
Did you look in Tesseract documentation and/or code? You may need to post your questions at [Tesseract Discussion Group](https://groups.google.com/forum/#!forum/tesseract-ocr) for answers.

**Comment by kamrapooja** [comment]
ok
