### ISSUE TITLE
The recognition results of tess4j and tesseract are inconsistent.

### ISSUE THREAD

**Issue by bleemliu** [nguyenq/tess4j#176]
tess4j version: 4.5.1
tesseract version: 4.1.1
leptonica version: 1.79
system: centos 7

I saw the Change Log on the tess4j website[http://tess4j.sourceforge.net/changelog.html], where tess4j 4.5.1 USES Leptonica 1.79.0 and Tesseract 4.1.1. But is it normal that I get inconsistent results using tess4j and Leptonica + Tesseract?

test data: http://q3820ps1a.bkt.clouddn.com/test/S00105-15295112.png
traineddata: https://github.com/tesseract-ocr/tessdata/blob/master/chi_sim.traineddata

**Comment by nguyenq** [comment]
If you call the same API methods with the same parameters, you'd get the same results.

**Comment by nguyenq** [comment]
Can the ticket be closed?

**Comment by bleemliu** [comment]
> Can the ticket be closed?

http://qiniu.ofcoder.com/test/S00105-15295112.png
