### ISSUE TITLE
How to run it in MA

### ISSUE THREAD

**Issue by XiaolinZhangALD** [nguyenq/tess4j#179]
Hello,I want to run it in mac and centos. But when i run it in mac , only show this message to me . How i can fix it ? Thank you 
![image](https://user-images.githubusercontent.com/43067715/76603601-35082b80-6548-11ea-9dbe-6a655686f263.png)

**Comment by XiaolinZhangALD** [comment]
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by nguyenq** [comment]
Do you have Tesseract installed on your machine? Which version is it?

**Comment by XiaolinZhangALD** [comment]
Yes , the version of tesseract is 'tesseract 5.0.0-alpha-584-g13e5' .I used 'brew install tesseract' to download tesseract

**Comment by nguyenq** [comment]
Tesseract 5.0.0 is still in alpha stage, so there isn't a tess4j release for it yet.

But you can try an old [tess4j-5.0.0-SNAPSHOT](https://oss.sonatype.org/#nexus-search;gav~net.sourceforge.tess4j~tess4j~~~~kw,versionexpand).

**Comment by XiaolinZhangALD** [comment]
Thanks ,the version of  tess4j-5.0.0-SNAPSHOT is useful .

**Comment by nguyenq** [comment]
Can the ticket be closed?
