### ISSUE TITLE
SLF4JBridgeHandler conflicts with slf4j-jdk14

### ISSUE THREAD

**Issue by grahams** [nguyenq/tess4j#183]
The `LoggerConfig` class pulls in the SLF4JBridgeHandler

```java
        try {
            if (!isLoaded) {
                SLF4JBridgeHandler.removeHandlersForRootLogger();
                SLF4JBridgeHandler.install();
                this.isLoaded = true;
            }[..]
```

Furthermore, the `pom.xml` sets dependencies on `jul-to-slf4j`, `jcl-to-slf4j`, `log4j-to-slf4j`.

The purpose of the SLF4J Bridges are for legacy applications which depend on older logging mechanisms (like java.util.Logging (JUL), Java Common Logging (JCL), or log4j).  They intercept messages heading for those older mechanisms and redirect them into SLF4J.

The problem with this is that if you have a Bridge enabled, then a downstream user configures SLF4J to bind to one of these legacy mechanisms, you end up with an infinite loop.  For example, the `jul-to-slf4j` bridge intercepts JUL messages, but if the downstream user has configured slf4j to use the `slf4j-jdk14` binding, you have SLF's Bridge intercepting all messages bound for JUL, but then emitting messages right back to JUL, which is again intercepted by SLF, etc.

Looking at the source for this project, it doesn't seem like there's any (obvious) reason to rely on a bridge. Logging messages all seem correctly targeted to slf4j Logger objects.  I commented out the above code in `LoggerConfig` and didn't see any obvious missing log entries...

The [SLF4J docs](http://www.slf4j.org/legacy.html#jul-to-slf4j) speak towards these limitations of these bridges.  Furthermore there are performance penalties incurred by using the bridges.

Am I missing a need for the bridge in tess4j?  We allow our users to choose their slf4j binding, and as it stands, if they choose `slf4j-jdk14` our application hangs with infinite log loops.  I assume we'd have a similar issue if the customer configured `slf4j-log4j` as the binding.

**Comment by grahams** [comment]
If you're interested in more specifics about the changes, you can check out our [fork here](https://github.com/SnowboundSoftware/tess4j)...

**Comment by nguyenq** [comment]
Please submit a PR. Thank you.

**Comment by grahams** [comment]
@nguyenq Will do, i'll clean things up a bit more in the morning and send it over.  Thanks.

**Comment by nguyenq** [comment]
Thank you for the PR.
