### ISSUE TITLE
Character Count Discrepancies Depending on Iterator Used

### ISSUE THREAD

**Issue by RyanLuMaye** [nguyenq/tess4j#186]
Hello, I was working with tess4j and wanted to get the bounding boxes of the characters inside a word, while making sure I knew which characters matched with certain words. This way I could know exactly where substrings were within a document. To do this I planned on first using `TessResultIteratorGetUTF8Text` to get the length of the next word in a document, and then iterated by symbol and called `TessPageIteratorBoundingBox` for the length of the string.  While this worked fine for some images, for others the characters summed when iterating by `RIL_SYMBOL`  did not ending matching the sum of the lengths of strings when iterating by `RIL_WORD`. Obviously I am a little confused by this behavior. If I had to guess I know Tesseract does a sort of spell checking to help choose certain characters over others but I also believe this behaves the same regardless of how one iterates. I have attached a Kotlin file (with txt extension) showing this behavior, and the image that is creating these discrepancies.

![testPDF2](https://user-images.githubusercontent.com/44307661/83453662-82e25080-a420-11ea-821f-ca213db59077.jpg)

[TesseractTest.kt.txt](https://github.com/nguyenq/tess4j/files/4713419/TesseractTest.kt.txt)

**Comment by nguyenq** [comment]
I think the issue should be directed to Tesseract developers.

https://github.com/tesseract-ocr/tesseract

**Comment by RyanLuMaye** [comment]
@nguyenq So I've been digging a bit more and I've found that iterating by symbols can add up to the same value as iterating by words, but that is because occasionally when one would call `TessResultIteratorGetUTF8Text` the length of the string wasn't equal to one. This makes me think that there is some encoding issue going on here. Maybe some other encoding is being used in the C++ version of Tesseract that isn't being converted correctly to UTF-8? I tried to make Tesseract filter the output to only values ranging from a-z (since those values seem to work fine and was testing if using filtering would be a good work around) via `TessBaseAPISetVariable` but that didn't seem to have an effect. I've read that this should work since v4.1 (Im using Tess4j v4.5.1) but maybe I'm doing something wrong. 

I'll create an issue on the main Tesseract project and then reference it from here if you think the issue is with that project still. I mainly just want to get your opinion on what could be going on after this new information since I don't want to create an issue that might be irrelevant. I'm not that great with C++ but I can try checking if similar behavior occurs with the original library. Also I've attached an updated Kotlin file with the character filtering attempt and non single length string behavior if you want to check that out.

[TesseractTest2.kt.txt](https://github.com/nguyenq/tess4j/files/4720024/TesseractTest2.kt.txt)

**Comment by nguyenq** [comment]
Congratulations, you have just unknowingly exposed me to a new programming language. Thank you very much.

Kidding aside, you probably can see that Tess4J's low-level API is simply a thin wrapper around Tesseract C API; as such, I suspect you would get the same results if you ran your example in native code.

Not sure if that was an encoding issue, but I notice that Tesseract occasionally and randomly would inject an addditional choice for a character in the string result; for example, it may return "màáy" for Vietnamese word "máy". I didn't delve too deep into the native code (I'm not that experienced with C/C++ myself), but I would think the algorithm would return the character with the highest confidence; however, a bug in the native code that has added an extra character choice skewering the result a little bit. Someone did mention the behavior in one of Tesseract's issues.
