### ISSUE TITLE
Is there a way to set dpi ? ... the tesseract option is --dpi

### ISSUE THREAD

**Issue by Ortega-Dan** [nguyenq/tess4j#187]
Here the option from linux man page
![image](https://user-images.githubusercontent.com/24926168/85602897-72835700-b615-11ea-8caf-70cabf15cccd.png)

**Comment by nguyenq** [comment]
`api.SetTessVariable("user_defined_dpi", dpi_string);`

**Comment by Ortega-Dan** [comment]
Thank you very much.
