### ISSUE TITLE
Tess4j performance improvement

### ISSUE THREAD

**Issue by tarunshah** [nguyenq/tess4j#188]
I'm using tess4j v-4.4.0 for converting tif files into text. So I not only wanted to convert it into text but I also had to perform NER and extract entities out of that text and then mark it on the tif file.
The current approach I'm using is first, I convert tif file into text. Secondly, I send the extracted text to NER engine, that led me to list of multiple entities. finally I have do one more iteration for converting tif into words with their coordinates.

Using the above approach takes lot of time and I want to cut through 3rd step. Is there any way I can convert words with coordinates in first iteration and then create text from it precisely.

I already tried to use the words with coordinates to convert into text but it's not same as it directly comes as text from tess4j.

Is there any better way to do this?

**Comment by nguyenq** [comment]
You mean you already tried `createDocumentsWithResults​` method (which returns `OCRResult` object)?

**Comment by tarunshah** [comment]
@nguyenq  Thanks for reply

I have used this :-
Step 1: Extract as text of document
```
Tesseract instance = new Tesseract();
String text = instance.doOCR(buffereImage);
```

Step 2: Find required substring using NLP from Stpe 1 text

step 3: find coordinates of substring using

`List<Word> wordList = instance.getWords(bufferedImage, ITessAPI.TessPageIteratorLevel.RIL_WORD);`

In this approach, I have to apply OCR 2 times.

Now, I want to perform this activity with 1 orc iteration. For this i have written one method to convert list of words to string

```
String convertWordsToString(List<Word> wordList)
{
     // Logic
    return text;
}
```

In the above method, the converted text is not that precise as extracted by doOCR method.

Is there any solution to get text and and word list with coordinates in single iteration?
Or
any predefined method in doing so

**Comment by nguyenq** [comment]
You can try `createDocuments`, which accepts multiple renderers, or `createDocumentsWithResults` to see which one is suitable for you.

**Comment by nguyenq** [comment]
Did you try?

**Comment by nguyenq** [comment]
No reponse from OP.
