### ISSUE TITLE
HOCR output location

### ISSUE THREAD

**Issue by paulovictorv** [nguyenq/tess4j#19]
Hi, I've enable HOCR output for Tess4j but I'm unable to find the resulting hocr file.

Where is the default output location for it?

Thanks

**Comment by 4F2E4A2E** [comment]
Can you please provide a unit test example? Which version are you using?

**Comment by paulovictorv** [comment]
Well, there's no unit test for it, I just enabled the HOCR output using the Tesseract1 class. 

The version for Tess4j is 1.3.0 and Tesseract is version 3.03.

**Comment by 4F2E4A2E** [comment]
I meant a code example or your unit test for it. Is there any particular reason why you are not using a newer Release? https://github.com/nguyenq/tess4j/releases/tag/tess4j-2.0.0
Investigating...

**Comment by paulovictorv** [comment]
Well, I didn't know there was a newer version, so that's why :D

I will try with a newer version and get back to you.

Thanks a lot

2015-06-03 14:51 GMT-03:00 4F2E4A2E <notifications@github.com>:

> I meant a code example or your unit test for it. Is there any particular
> reason why you are not using a newer Release?
> https://github.com/nguyenq/tess4j/releases/tag/tess4j-2.0.0
> Investigating...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nguyenq/tess4j/issues/19#issuecomment-108545399>.
>



-- 
Paulo Victor Vieira de Melo
Graduando em Ciência da Computação
Lattes : http://lattes.cnpq.br/7418993216312941
Currículo StackOverflow Carrers:
http://careers.stackoverflow.com/paulovictorv
UFAL - IC

**Comment by 4F2E4A2E** [comment]
Hi there! Did you make use of the setHocr like described in the wiki [1]?
Please take notice that the hocr file will be the return value, you will have to take care of persisting the file to the file system yourself.

```java
instance.setHocr(true);
result = instance.doOCR(imageFile);
```

1: https://github.com/nguyenq/tess4j/wiki/Code-Sample#junit-hocr-example

**Comment by 4F2E4A2E** [comment]
Did you manage to get it done? Can i close this one?

**Comment by paulovictorv** [comment]
Sorry for the delay. Yeah, it was pretty obvious, but I couldn't find any
documentation at the time.

You can go ahead and close this, thanks for the help.

2015-06-06 2:30 GMT-03:00 4F2E4A2E <notifications@github.com>:

> Did you manage to get it done? Can i close this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nguyenq/tess4j/issues/19#issuecomment-109531248>.
>



-- 
Paulo Victor Vieira de Melo
Graduando em Ciência da Computação
Lattes : http://lattes.cnpq.br/7418993216312941
Currículo StackOverflow Carrers:
http://careers.stackoverflow.com/paulovictorv
UFAL - IC

**Comment by 4F2E4A2E** [comment]
No problem! Thank you for the feedback. By the way what are you actually doing with the HOCR files? Creating PDFs?
