### ISSUE TITLE
MacOS tess4j ghostscript issue

### ISSUE THREAD

**Issue by weiwang11** [nguyenq/tess4j#195]
I'm trying to extract text from PDFs using tess4j but it's outputting `EE ee EE EE EE ee` and similar text, even though windows is significantly better.

I had the same problem on windows but moving `gsdll64.dll` to `src/main/resources` fixed the issue for me and the output is almost 100% accurate. I can't seem to figure out how to fix this on macOS. 

I added `-Djna.library.path=/usr/local/lib` to my args and it still doesn't work even though both ghostscript and tesseract is installed via homebrew and should have a symlink to `/usr/local/lib`. I also tried moving `libtesseract.4.dylib` and `libgs.9.52.dylib` to `src/main/resources` as well and tried moving them to a `darwin` folder under resources doesn't help either.

Am I doing something wrong or does tess4j just not work as well on macOS compared to windows?

The PDFs I'm using is also very clear without any noise or marks.

Tess4J: 4.5.2
Tesseract: 4.1.1
Leptonica: 1.80.0
Ghostscript: 9.5.2

This is using eng.traineddata.

**Comment by weiwang11** [comment]
The issue appears to be PdfBox's ImageType.RGB. I changed to ImageType.GRAY to match the output of PdfGsUtilities.

**Comment by nguyenq** [comment]
We constanly keep up to date with the dependencies. Will publish an update soon.

Thank you.
