### ISSUE TITLE
Tess4j 4.5.3 crashing

### ISSUE THREAD

**Issue by SledgeHammer01** [nguyenq/tess4j#198]
- Spring Boot 2.3.4
- Oracle JDK 11.0.7
- Windows 10 x64 Pro
- Tess4j 4.5.3

I'm trying to ocr a doc and get its structure and bounding rectangles, so:

Document
  Page
    Paragraph
      Line
        Word

I am using a 4 page legal document in TIFF format for testing and I keep getting:

<terminated, exit value: -1073740940>C:\Program Files\Java\jdk-11.0.7\bin\javaw.exe (Oct 5, 2020, 10:31:43 AM)	

My code looks like:

```
	private void ocrImage(TessBaseAPI handle, BufferedImage bufferedImage) {
		ByteBuffer byteBuffer = ImageIOHelper.convertImageData(bufferedImage);

		int bitsPerPixel = bufferedImage.getColorModel().getPixelSize();
		int bytesPerPixel = bitsPerPixel / 8;
		int bytesPerLine = (int)Math.ceil(bufferedImage.getWidth() * bitsPerPixel / 8.0);

		TessAPI1.TessBaseAPISetImage(handle, byteBuffer, bufferedImage.getWidth(), bufferedImage.getHeight(), bytesPerPixel, bytesPerLine);
		TessAPI1.TessBaseAPIRecognize(handle, null);

		TessResultIterator paragraphIterator = TessAPI1.TessBaseAPIGetIterator(handle);

		processParagraphs(paragraphIterator);
System.out.println("C" + this.i);
		TessAPI1.TessResultIteratorDelete(paragraphIterator);
System.out.println("D" + this.i);		
	}

```

I have tracked down the cause to the TessAPI1.TessResultIteratorDelete(paragraphIterator); call. If I comment this out, it completes successfully, but per the docs, I need that to free the native memory.

In processParagraphs, I use the same method and it doesn't cause an issue:

```
	private void processParagraphs(TessResultIterator paragraphIterator) {
		TessPageIterator pageIterator = TessAPI1.TessResultIteratorGetPageIterator(paragraphIterator);

		do {
			IntBuffer left = IntBuffer.allocate(1);
			IntBuffer top = IntBuffer.allocate(1);
			IntBuffer right = IntBuffer.allocate(1);
			IntBuffer bottom = IntBuffer.allocate(1);

			TessAPI1.TessPageIteratorBoundingBox(pageIterator, TessPageIteratorLevel.RIL_PARA, left, top, right, bottom);

			System.out.println(String.format("PARAGRAPH: %d, %d, %d, %d", left.get(), top.get(), right.get(), bottom.get()));

			TessResultIterator lineIterator = TessAPI1.TessResultIteratorCopy(paragraphIterator);

			//processLines(lineIterator);
System.out.println("A" + this.i);
			TessAPI1.TessResultIteratorDelete(lineIterator);
System.out.println("B" + this.i);
		} while (TessAPI1.TessResultIteratorNext(paragraphIterator, TessPageIteratorLevel.RIL_PARA) == TessAPI1.TRUE);

		TessAPI1.TessPageIteratorDelete(pageIterator);
	}

```

Both the TessResultIteratorDelete and the TessPageIteratorDelete work in this method.

**Comment by nguyenq** [comment]
Sorry, we haven't got around to investigating this, which would involve digging into Tesseract native code. From a pragmatic standpoint, if it does not cause memory leaks, then consider your code is good enough.

**Comment by jsubercaze** [comment]
Hello, we encountered the same issue and it leads to a memory leak since we can not free the iterator.

**Comment by nguyenq** [comment]
@SledgeHammer01 Looks like you are calling `TessPageIteratorDelete` twice; it would throw exceptions if you attempted to delete an already deleted object. We don't think you can reuse an `Iterator` for multiple `PageIteratorLevel`.

**Comment by nguyenq** [comment]
@jsubercaze The unit tests and the code has been updated to include proper disposal of the iterator objects. Please check it out and let us know the results. Thanks.

**Comment by SledgeHammer01** [comment]
> @SledgeHammer01 Looks like you are calling `TessPageIteratorDelete` twice; it would throw exceptions if you attempted to delete an already deleted object. We don't think you can reuse an `Iterator` for multiple `PageIteratorLevel`.

I'm not clear on what you mean. Picture a call/nesting graph as:

1TessResultIterator paragraphIterator = TessAPI1.TessBaseAPIGetIterator(handle);
2  TessPageIterator pageIterator = TessAPI1.TessResultIteratorGetPageIterator(paragraphIterator);
3    TessResultIterator lineIterator = TessAPI1.TessResultIteratorCopy(paragraphIterator);
4    delete lineIterator
5  delete pageIterator
6 delete paragraphIterator

So you are saying 4 is also deleting the iterator created in 2?

If so, we just do 5 & 6? And skipping 4 does not cause a leak? Wouldn't calling 1 at each level return an interator back at the start of the page?

Can you show how the 1 - 6 should be structured?

Thanks.

**Comment by nguyenq** [comment]
I'm not sure exactly what `TessResultIteratorCopy` does (you'd need to consult Tesseract native code) or what you're trying to do with it, but delete lineIterator could have deleted paragraphIterator.

Can you list your `processLines` method so we could understand your intent? But I don't think you can use nested processing loops like that. I guess you would need to get separate iterators to loop through all the paragraphs and then all the lines.

**Comment by SledgeHammer01** [comment]
> I'm not sure exactly what `TessResultIteratorCopy` does (you'd need to consult Tesseract native code) or what you're trying to do with it, but delete lineIterator could have deleted paragraphIterator.
> 
> Can you list your `processLines` method so we could understand your intent? But I don't think you can use nested processing loops like that. You probably would need to get separate iterators to loop through all the paragraphs and all the lines.

I am trying to get the HIERACHY of the document as described.

Page 1
  Paragraph 1
     Lines 1
        Word 1
        Word 2
     Lines 2
        Word 1
   Paragraph 2
       .
       .
       .

All the different "process" methods are the same idea:

```
	private void processLines(TessResultIterator lineIterator) {
		TessPageIterator pageIterator = TessAPI1.TessResultIteratorGetPageIterator(lineIterator);

		do {
			IntBuffer left = IntBuffer.allocate(1);
			IntBuffer top = IntBuffer.allocate(1);
			IntBuffer right = IntBuffer.allocate(1);
			IntBuffer bottom = IntBuffer.allocate(1);

			TessAPI1.TessPageIteratorBoundingBox(pageIterator, TessPageIteratorLevel.RIL_TEXTLINE, left, top, right, bottom);

			TessResultIterator wordIterator = TessAPI1.TessResultIteratorCopy(lineIterator);

			this.lines.add(new TessLine(new TessBoundingBox(left.get(), top.get(), right.get(), bottom.get()), wordIterator));

			TessAPI1.TessResultIteratorDelete(wordIterator);
		} while ((TessAPI1.TessPageIteratorIsAtFinalElement(pageIterator, TessPageIteratorLevel.RIL_PARA, TessPageIteratorLevel.RIL_TEXTLINE) == 0) &&
				 (TessAPI1.TessResultIteratorNext(lineIterator, TessPageIteratorLevel.RIL_TEXTLINE) == TessAPI1.TRUE));

		//TessAPI1.TessPageIteratorDelete(pageIterator);
	}
```

Conceptually, I get the page iterator and loop through paragraphs. For each paragraph, I want to loop through the lines just for that paragraph and so on.

**Comment by nguyenq** [comment]
No, I don't think it works like that, the nested loops. Each level requires separate iterations. Once you got all the collections, you can correlate them by checking whether the children's region (rectangle) is contained within the bounds of their parent.

**Comment by nguyenq** [comment]
Upon further investigation, I found that it's OK to delete separate copies of `ResultIterator`, but do not call both `TessPageIteratorDelete` and `TessResultIteratorDelete` at the same time since deleting one probably deletes the associated other as well.

**Comment by nguyenq** [comment]
[tess4j-4.5.4](https://github.com/nguyenq/tess4j/releases/tag/tess4j-4.5.4) has been released to address the issue.
