### ISSUE TITLE
PDF with Chinese chars

### ISSUE THREAD

**Issue by juanmarques** [nguyenq/tess4j#201]
Hello I'm trying to OCR a Chinese PDF with chi_sim.traineddata but seems it doesn't work.
I can get the result as a text , but not the searchable pdf.

Is there any limitations?

Thank you.

**Comment by nguyenq** [comment]
What would you get with Tesseract CLI?

**Comment by juanmarques** [comment]
If I convert the pdf to png it works fine.

**Comment by nguyenq** [comment]
tess4j would attempt to convert PDF to TIFF (via GS or PDFBox) and then send the TIFF image to tesseract engine. You need to provide more details (library version, environment, Java, etc.).

**Comment by nguyenq** [comment]
> If I convert the pdf to png it works fine.

I'd like to clarify. tess4j does not have a problem with the png?

**Comment by juanmarques** [comment]
Hello @nguyenq,sorry for the late reply.

It works fine with png.

Here's the details:
```
Java 8
tess4j version: 4.5.3
tessdata: chi_sim
```

I will try to find some samples to send to you.

Thank you.

**Comment by nguyenq** [comment]
You'd need to focus on the PDF-to-image conversion part. How did you convert your PDF to PNG?

**Comment by nguyenq** [comment]
No response from OP.
