### ISSUE TITLE
Remove Ghost4J

### ISSUE THREAD

**Issue by JaquelineP** [nguyenq/tess4j#206]
There are several security issues in ghost4J's dependencies, especially because they utilize commons-beanutils in version 1.9.2. The more recent version 1.9.4 would resolve the security issues. However, ghost4j isn't under active development. Last change was almost 2 years ago. For more details see this [issue](https://github.com/zippy1978/ghost4j/issues/73)

Do you have any plans on removing ghost4J dependency and therefore the support to convert pdfs?
Is it possible to deactivate this functionality?

**Comment by nguyenq** [comment]
Let's wait for ghost4j's owner to respond. Meanwhile, you can force use of PDFBox by setting a system property.

http://tess4j.sourceforge.net/docs/docs-4.4/net/sourceforge/tess4j/util/PdfUtilities.html

**Comment by nguyenq** [comment]
Ghost4j dependency has been removed in Release [5.1.1](https://github.com/nguyenq/tess4j/releases/tag/tess4j-5.1.1) due to log4j and other vulnerabilities.

Thank you for bringing this issue to our attention.

**Comment by Abu-Abdullah** [comment]
there is a recent ghost4J v1.0.5
you might want to restore this function again

**Comment by nguyenq** [comment]
@Abu-Abdullah It's not being considered until that version is published to Maven. Thanks for bringing it to our attention.
