### ISSUE TITLE
garbled text from ocr attempt on image without text

### ISSUE THREAD

**Issue by tooptoop4** [nguyenq/tess4j#208]
If I run doOcr  on an image that contains no text. ie
```http://voice.gardenbird.co.uk/wp-content/uploads/2016/10/Robin-on-branch.jpg```

I get a garbled response like:
Mey st\neS\nEe ae\nLie....

is there some option to return empty string or null if it has low confidence in finding text?

**Comment by nguyenq** [comment]
`doOCR` returns only text. You'd need to use other methods that return confidence values as well.

http://tess4j.sourceforge.net/docs/docs-4.4/net/sourceforge/tess4j/Tesseract.html
