### ISSUE TITLE
[error] java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by marcelocecin** [nguyenq/tess4j#209]
[error] java.lang.UnsatisfiedLinkError ( java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': /lib/x86_64-linux-gnu/libtesseract.so.4: undefined symbol: TessPDFRendererCreateTextonly )

**Comment by nguyenq** [comment]
An issue report should include system and software configuration. It will help in quicker problem diagnosis and resolution.

**Comment by marcelocecin** [comment]
tesseract 4.1.1
 leptonica-1.79.0
  libgif 5.1.4 : libjpeg 8d (libjpeg-turbo 2.0.3) : libpng 1.6.37 : libtiff 4.1.0 : zlib 1.2.11 : libwebp 0.6.1 : libopenjp2 2.3.1
 Found AVX
 Found SSE
 Found libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.4

Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import cv2
cv2.version
'4.2.0'

Ubuntu 20.04.1 LTS

**Comment by nguyenq** [comment]
Seems like an incompatible tess4j version. Which version are you using?

**Comment by marcelocecin** [comment]
in which folder do I need to put the tess4j-4.5.4.jar file?

**Comment by nguyenq** [comment]
It needs to be in your classpath.

**Comment by marcelocecin** [comment]
I'm using [SikuliX](https://github.com/RaiMan/SikuliX1) v1.1.4 (Build # 272) in [TagUI](https://github.com/kelaberetiv/TagUI) to provide computer vision, OCR, low-level keyboard and mouse capabilities

**Comment by marcelocecin** [comment]
Tess4J is bundled in the SikuliX jars as the access layer to Tesseract. No need to have an extra Tess4J jar.

**Comment by marcelocecin** [comment]
https://github.com/tesseract-ocr/tesseract/issues/3274

**Comment by nguyenq** [comment]
It looks like your SikuliX is still loading tess4j-3.x version for Tesseract 3.x, which has `TessPDFRendererCreateTextonly` function. That function is removed in Tesseract 4.x. You need to upgrade SiluliX to use tess4j-4.5.4 to go with your Tesseract 4.1.1.

**Comment by marcelocecin** [comment]
I downgraded tesseract to version 3.05.02
the error has now changed:
Failed loading language 'eng'
Tesseract couldn't load any languages!
