### ISSUE TITLE
Windows Server 2019 error instance.doOCR

### ISSUE THREAD

**Issue by AlexBravoInostroza01** [nguyenq/tess4j#211]
I am presenting a problem when executing instance.doOCR in windows server 2019, it gives the image error, instead I run on a physical pc it works fine

![image](https://user-images.githubusercontent.com/77693511/113177635-20b2d180-9224-11eb-8685-167c033d778d.png)

**Comment by nguyenq** [comment]
Do you have the appropriate VC++ runtime installed?
