### ISSUE TITLE
Change directory where libtesseract##.dll and liblet##.dll  files are extracted.

### ISSUE THREAD

**Issue by StScAllen** [nguyenq/tess4j#212]
Is there any way to change the directory these dll files are extracted to?  I have a bizarre installation setup and would like tess4j to look for them in another location.  Preferably inside the installation directory.

**Comment by nguyenq** [comment]
There's no other option. The directory where the DLLs extracted to is defined by `java.io.tmpdir` systerm property.

Alternately, you can copy the DLLs to any directory and then set `jna.library.path` property to tell JNA where to locate and load the native library.

**Comment by nguyenq** [comment]
`java.io.tmpdir` seems settable.

**Comment by StScAllen** [comment]
Yeah, that worked nicely for my needs.  Sorry I didn't follow up.

Thanks!
