### ISSUE TITLE
Extract tables API in Tesseract-OCR 5.0

### ISSUE THREAD

**Issue by neosis** [nguyenq/tess4j#216]
Hi,
Few months back a new API is made available in Tesseract OCR - [https://github.com/tesseract-ocr/tesseract/commit/122daf1d640753ecd77208da6636e9e5ac4d0e07]

Tess4J master has been bumped to support the tesseract-OCR 5.0. Is support for this new tables related API available in current master of Tess4j?

Best
Ashutosh

**Comment by nguyenq** [comment]
It seems this new API has not been exposed in Tesseract's [C-API](https://github.com/tesseract-ocr/tesseract/blob/master/include/tesseract/capi.h). You may want to request Tesseract developers to do that before Java client programs can use it.

**Comment by nguyenq** [comment]
But it looks like that commit for tables has been [backed out](https://github.com/tesseract-ocr/tesseract/commit/4df822a3fc481f026250fcf2bb4c0e7583df1dd5) of Tesseract codebase.
