### ISSUE TITLE
Tess4J v4.5.5 UnsatisfiedLink

### ISSUE THREAD

**Issue by youngsys** [nguyenq/tess4j#217]
Hi guys!

Thanks for your latest build.
Unfortunately I get an UnsatisfiedLink exception.
I am on Windows 10 64 bit.
DependencyWalker shows it is looking for liblept1790.dll.
In the AppData\temp\tess4J\win32-x86-64 folder I get libtesseract411.dll and liblept1811.dll.
If I copy liblept1811.dll to liblept1790.dll the exception on loading goes away.
I haven't taken it any further: I presume it would be unwise for me to continue to use it in this state ...?

Cheers!

**Comment by nguyenq** [comment]
tess4j-4.5.5's Windows binary depends on lept4j-1.13.3.

**Comment by youngsys** [comment]
Aha! I was confused by the Maven entry (attached).
If I use 1.13.3 it's all good.
Could you tell me what the "Updates" column means?
Thanks
<img width="548" alt="Capture" src="https://user-images.githubusercontent.com/20759387/126829157-6740250a-4005-4c20-891d-7bac124f8c19.PNG">

**Comment by youngsys** [comment]
I did some research. I'm even more confused about what the Updates column means. I think it means there is a later version, but it's not the right one for this dependency. Really useful! Not!
Thx.

**Comment by nguyenq** [comment]
@youngsys Yes, the Updates column lists the latest version published on Maven. For this case, however, the bundled Tesseract 4.1.1 Windows binary was linked against the older Leptonica 1.79, not the latest.
