### ISSUE TITLE
Ubuntu 20.04 build error

### ISSUE THREAD

**Issue by alex73** [nguyenq/tess4j#218]
Ubuntu 20.04 contains liblept5 1.79.0-1 and libtesseract4 4.1.1

Results :

Failed tests:   testTessVersion(net.sourceforge.tess4j.TessAPI1Test)
  testTessVersion(net.sourceforge.tess4j.TessAPITest)

Tests in error: 
  testTessBaseAPIGetUTF8Text_Pix(net.sourceforge.tess4j.TessAPI1Test): Error looking up function 'boxaSizeConsistency': /lib/x86_64-linux-gnu/liblept.so.5: undefined symbol: boxaSizeConsistency
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testTessBaseAPIDetectOrientationScript(net.sourceforge.tess4j.TessAPI1Test): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testGetSegmentedRegions(net.sourceforge.tess4j.Tesseract1Test): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testCreateDocumentsWithResults1(net.sourceforge.tess4j.Tesseract1Test): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testTessBaseAPIGetComponentImages(net.sourceforge.tess4j.TessAPITest): Could not initialize class net.sourceforge.lept4j.Leptonica1
  testCreateDocumentsWithResults1(net.sourceforge.tess4j.TesseractTest): Could not initialize class net.sourceforge.lept4j.Leptonica1

Tests run: 79, Failures: 2, Errors: 8, Skipped: 2

**Comment by nguyenq** [comment]
Make sure you use [lept4j version](https://github.com/nguyenq/lept4j/releases) compatible with your Leptonica version.

**Comment by alex73** [comment]
Yes, liblept5 1.79.0-1 requires lept4j-1.13.3.
My fault - I tried to compile tess4j's master instead tess4j-4 branch.
