### ISSUE TITLE
tomcat 9 war file with tess4j is giving java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by sanjeebsarkar** [nguyenq/tess4j#223]
Hi ,
First of all, thank you so much for building this to help with OCR related work in Windows. Although there is a small problem when I am running this is in Windows 7 64bit, here are the VC++ redist packages I have installed :

![image](https://user-images.githubusercontent.com/58333434/141395403-c719c093-c8d6-4efe-858b-14e9e26179ce.png)

The thing is , this program is working fine with eclipse-tomcat. In eclipse , there is Temp folder also getting created in the C:\ partition. 
And the TESSDATA_PREFIX path is also set to tesseract 5.0.0 installation location's tessdata folder.

After creating a war file and pasting it in tomcat 9 / webapps folder , and then running the startup.bat file. The tomcat 9 turns on perfectly , even the tess4j folder is also getting created in the tomcat9/temp folder. 

![image](https://user-images.githubusercontent.com/58333434/141396768-c4930b3e-e85f-4fe3-8b91-343ee9e1d2d5.png)

And all these are the jar files which have been included in the project build path.
![image](https://user-images.githubusercontent.com/58333434/141396878-8173ad41-160a-4d70-8a64-eca288c96e78.png)

So after deploying the war file when I am sending a request, I am getting this 500 error in postman,

`

<!doctype html>
<html lang="en">

<head>
	<title>HTTP Status 500 – Internal Server Error</title>
	<style type="text/css">
		h1 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 22px;
		}

		h2 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 16px;
		}

		h3 {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
			font-size: 14px;
		}

		body {
			font-family: Tahoma, Arial, sans-serif;
			color: black;
			background-color: white;
		}

		b {
			font-family: Tahoma, Arial, sans-serif;
			color: white;
			background-color: #525D76;
		}

		p {
			font-family: Tahoma, Arial, sans-serif;
			background: white;
			color: black;
			font-size: 12px;
		}

		a {
			color: black;
		}

		a.name {
			color: black;
		}

		.line {
			height: 1px;
			background-color: #525D76;
			border: none;
		}
	</style>
</head>

<body>
	<h1>HTTP Status 500 – Internal Server Error</h1>
	<hr class="line" />
	<p><b>Type</b> Exception Report</p>
	<p><b>Message</b> Servlet execution threw an exception</p>
	<p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.
	</p>
	<p><b>Exception</b></p>
	<pre>javax.servlet.ServletException: Servlet execution threw an exception
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
	<p><b>Root Cause</b></p>
	<pre>java.lang.UnsatisfiedLinkError: The specified module could not be found.

	com.sun.jna.Native.open(Native Method)
	com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288)
	com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	com.sun.jna.Library$Handler.&lt;init&gt;(Library.java:179)
	com.sun.jna.Native.loadLibrary(Native.java:569)
	com.sun.jna.Native.loadLibrary(Native.java:544)
	net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:85)
	net.sourceforge.tess4j.TessAPI.&lt;clinit&gt;(TessAPI.java:42)
	net.sourceforge.tess4j.Tesseract.init(Tesseract.java:427)
	net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:311)
	net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:294)
	net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:275)
	net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:259)
	com.ReadQR.readTextfromImage(ReadQR.java:184)
	com.ReadQR.readTextAndSetPagesFromImage(ReadQR.java:213)
	com.ReadQR.ReadQr(ReadQR.java:106)
	com.Post.doPost(Post.java:58)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre>
	<p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p>
	<hr class="line" />
	<h3>Apache Tomcat/9.0.27</h3>
</body>

</html>

`

Can you please tell me what mistake I am doing ? This is running completely fine in tomcat 9 , in windows 10 64bit.

Thank you.

**Comment by nguyenq** [comment]
Make sure that the app have write/read access to Tomcat's temp folder. You may want to set the system property `jna.debug_load=true` to print the library search paths that JNA is searching for the native libraries to load.

https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md

**Comment by sanjeebsarkar** [comment]
> Make sure that the app have write/read access to Tomcat's temp folder. You may want to set the system property `jna.debug_load=true` to print the library search paths that JNA is searching for the native libraries to load.
> 
> https://github.com/java-native-access/jna/blob/master/www/FrequentlyAskedQuestions.md

Hi ,
 I will check the jna.debug_load , on the other hand , tomcat is able to create a folder inside its /temp folder. So read write is not an issue.

One thing, the TESSDATA_PREFIX is added to system path, do I need to add the tess4j's dlls also to system path ?

**Comment by nguyenq** [comment]
The environment variable `TESSDATA_PREFIX` should not be added to system path; it should be set to the parent directory of your `tessdata` directory.

Just wanted to confirm, are you running JDK 64 bit?

**Comment by sanjeebsarkar** [comment]
Hi ,
I may have said it wrong, I have added TESSDATA_PREFIX to the environment variable, and it points to the installation/tessdata folder , this is the screenshot of the tessdata path set in the $PATH variable in Windows 7.
![image](https://user-images.githubusercontent.com/58333434/141601945-afd17812-cdfa-446c-ad97-3fbffa8ba36f.png)


And , yes I am using jdk 64 biy, here is a cmd version output details of the java :

![image](https://user-images.githubusercontent.com/58333434/141602282-167ceea9-187b-4dbf-b233-22d83488a636.png)

is there any additional setting I have to do for tomcat to help it find the dll's ?

**Comment by nguyenq** [comment]
`TESSDATA_PREFIX` variable should be set to `D:\Program Files\Tesseract-OCR`.

What is printed out when you run with `jna.debug_load=true`?

**Comment by sanjeebsarkar** [comment]
Hi ,
Please give me some time, I am working on the jna argument.

I will change the path also.

**Comment by sanjeebsarkar** [comment]
Hi 

Here is cmd output with the -D option added in tomcat 9,

![image](https://user-images.githubusercontent.com/58333434/141605029-60935a54-42fd-4a7b-aa83-c40cc703057a.png)

Is this what you were looking for ?

**Comment by nguyenq** [comment]
JNA indeed tried to look up the native libraries in Tomcat's Temp directory but, for some reasons, was unable to load the DLLs found. I notice the JNA version is very old -- not sure if that could be a problem.

All I can suggest now is to create a simple console app using tess4j. Once you can get that to work, you can then try to apply to the server app.

**Comment by sanjeebsarkar** [comment]
Hi ,
Thank you for replying , 
Which version of JNA would you recommend ?

**Comment by sanjeebsarkar** [comment]
Ok , I will try to do that, can you please tell me a little bit clear as to what to do ? Create a standalone "main method" program, and create a jar file and then call it from war file ?

**Comment by nguyenq** [comment]
tess4j's dependencies: https://mvnrepository.com/artifact/net.sourceforge.tess4j/tess4j/4.5.5

Just to get a simple console app to ensure you get all the required dependencies for tess4j and get it to run. I'm not experience with WAR packaging or Java application server to give advice on.

**Comment by sanjeebsarkar** [comment]
Ok, Understood.. 
Anyway, we can close this issue, since I am stuck on my side. I will reopen this issue once I have something to report.

Thanks for all the help.

**Comment by nguyenq** [comment]
Good luck. The OP, who opened the issue, can close it as well.
