### ISSUE TITLE
Building own Jar for Linux and Macos

### ISSUE THREAD

**Issue by roflox** [nguyenq/tess4j#226]
Hello,

I am trying to create a single Jar file that would contain all necessary dll, so and dylib files so that I can deploy it cross-platform without the need to install Tesseract or Leptonica. I am running into some problems when I try to package Linux libraries. This is my resources folder:
![image](https://user-images.githubusercontent.com/38251746/153959913-00633982-813b-4eed-a786-b893efee204c.png)

But when I try to run on my Linux  VM
`mvn package`

I get this:
![image](https://user-images.githubusercontent.com/38251746/153961596-1d3e6584-8911-49f4-b7ef-0894d85e361e.png)

Could you please navigate me what should I do to be able to create one such JAR file? Thank you for your time.

Best regards

**Comment by nguyenq** [comment]
Regarding the correct library name and folder, please consult JNA code to verify.

https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Platform.java
https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/NativeLibrary.java

But the locale error seems to point to something else, not the location.

When you build [Leptonica](https://github.com/DanBloomberg/leptonica), make sure it includes all the necessary dependencies (tiff, png, jpeg, etc.).
