### ISSUE TITLE
OCRResult only contains last page's scan

### ISSUE THREAD

**Issue by lynlevans** [nguyenq/tess4j#233]
We've encountered a bug when calling **_createDocumentsWithResults_**() from **_Tesseract/tess4j 4.5.5_**. The Tiff scanned by the method call, has 32 pages, and ~3100 words. Yet, the result produced by the Java call only contains the result of the last page scanned.

The OCRResult, in Java, is an empty string in this bounding box: [ [Confidence: 95.000000 Bounding box: 313 434 938 822]], which is the same result when scanning the last page of the Tiff file.

Can the Tess4j team investigate this bug ?

**Comment by nguyenq** [comment]
Please check out the fix and let us know.

Thanks.
