### ISSUE TITLE
Can tess4j be used to convert a pdf with images as content to a searchable pd

### ISSUE THREAD

**Issue by nimiththomas** [nguyenq/tess4j#239]
I need to convert a pdf with images as content to a searchable pdf(the pdf should also contain the images but it should be searchable)

And sorry for posting this as a issue. Didn't know how to clarify this question

**Comment by nguyenq** [comment]
The answer is yes — via `createDocuments` method.

**Comment by nimiththomas** [comment]
Thanks for the clarification
