### ISSUE TITLE
meanTextConfidence is 0 for doc with empty last page but non-empty others in createDocumentsWithResults method

### ISSUE THREAD

**Issue by yshyman** [nguyenq/tess4j#242]
I am doing PDF ocr and found a bug that meanTextConfidence reports 0 in case last page of a PDF is empty while other are not. This returns empty info in OCRResult object.

Attaching sample document
[res.pdf](https://github.com/nguyenq/tess4j/files/10413308/res.pdf)

Best regards,
Yurii

**Comment by nguyenq** [comment]
We're unable to reproduce the issue. A valid meanTextConfidence value was returned for the PDF file.

**Comment by nguyenq** [comment]
Not an issue.
