### ISSUE TITLE
Tess4J should not package dependencies

### ISSUE THREAD

**Issue by alycecil** [nguyenq/tess4j#25]
This is maven breaking behaviour that should only be used for a final production application jar; not a library.

**Comment by 4F2E4A2E** [comment]
Thank you for creating this issue.
You're right, but maybe that is our scope, to deliver a final production jar.
Do you have any suggestions on how to do that in our specific case? Please deliver some, we would be glad to go through them.

As far as i can see there is no changes done by you so far in your fork:
https://github.com/nguyenq/tess4j/compare/master...wcecil:master

**Comment by wcecil** [comment]
The ideals of using a build and dependency management tool is to not have to bring all the libraries into your jar.

While a mega/fat jar is sometimes right; that usually in the case of the final application to be run by a server or user. Which to my understanding is not what tess4j is for. Tess4j is a library which is included in an application to do a cross talk to the ocr library. The application should handle the dependencies. Including the dependencies in your pom is sufficient to let the application developer use and get the dependencies at time of build.

That being said the native ocr library should be included in the jar as its not retrievable by common build tools.

If you wish to maintain a all in one jar for releasing not through maven-central / for use in applications without a dependency management tool, that is fine.

I'll work on it tonight; sadly I've had a lot of non-developer life get in the way.

**Comment by 4F2E4A2E** [comment]
I totally makes sense, i guess the reason we did it this way was because at the beginning many libs weren't on maven central.
But i think, that we can give it a try.
Non-Developer life getting in the way is actually great! Well, at least sometimes :)

@nguyenq : what do you say? Maybe only for all libs hosted at maven central?

**Comment by wcecil** [comment]
Some of the others are on non maven-central repositories and we could add <repository> tags for those as well

**Comment by nguyenq** [comment]
I agree that, as a library, the JAR should not include the dependencies. Is there a Maven plugin that enables that packaging?

**Comment by wcecil** [comment]
we can keep using shade; to pull everything from maven-resources-plugin

Add a global exclude for classes like
```xml
<exclude>**.class</exclude>
```


then add filters for what we want to keep like:
```xml
<filter>
     <artifact>group:artifact</artifact>
     <includes>
          <include>**</include>
     </includes>
</filter>
```

**Comment by 4F2E4A2E** [comment]
Fixing this without plugins or packing, but mainly throught maven dependencies, as soon as all dependencies (remaining one) are on maven central.
Added a request / help offer for moving the j2big lib to maven central: https://github.com/levigo/jbig2-imageio/issues/5
I think, that we, PDFBox any many others could benefit from this.

**Comment by nguyenq** [comment]
@4F2E4A2E Can this be closed? If yes, please go ahead.

Thanks.
