### ISSUE TITLE
Other languages can not use except eng

### ISSUE THREAD

**Issue by fivesmallq** [nguyenq/tess4j#26]
OS X EI Capitan 10.11.1
JDK8_60
test4j 2.0.1
tesseract 3.04.00

i installed tesseraect from brew.
````
brew reinstall tesseract --all-languages --with-training-tools
````

tessdata path is ``/usr/local/share/`` and it has ``chi_sim.traineddata``
![image](https://cloud.githubusercontent.com/assets/745063/11415386/2cb12c4c-943d-11e5-96f6-a3aed0c2abcb.png)

but when i use tess4j to load ``chi_sim``, here is code

````java
public class TesseractOCR {
    private static Logger logger = LoggerFactory.getLogger(TesseractOCR.class);

    //default config
    private final static String DEFAULT_TESSDATA_PATH = "/usr/local/share";
    private final static String DEFAULT_PAGE_SEG_MODE = "3";
    private final static String DEFAULT_LANG = "chi_sim";

    public static void main(String[] args) {
        Tesseract instance = new Tesseract();  // JNA Interface Mapping
        instance.setLanguage(DEFAULT_LANG);
        instance.setDatapath(DEFAULT_TESSDATA_PATH);
        instance.setPageSegMode(Integer.parseInt(DEFAULT_PAGE_SEG_MODE));
        BufferedImage image = Images.from("ocr/data/input/1.png");
        String result = "";
        try {
            result = instance.doOCR(image);
        } catch (TesseractException e) {
            logger.error("ocr image error!", e);
        }
        logger.info(result);
    }
}
````

````
Failed loading language 'chi_sim'
Tesseract couldn't load any languages!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000012a54e933, pid=3139, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.dylib+0x12933]  tesseract::Tesseract::recog_all_words(PAGE_RES*, ETEXT_DESC*, TBOX const*, char const*, int)+0xb9
#
````

the jvm crashed. here is log https://gist.github.com/fivesmallq/1f6d349c02e9bbab9b80

``eng`` is ok.

-----------------

also, i clone the tess4j project from github. and update junit test to set language ``chi_sim``,  put ``chi_sim.traineddata`` to ``src/main/resources``, It appeared the same problem. 

````
➜  tessdata git:(master) which tesseract
/usr/local/bin/tesseract
````
````
➜  tessdata git:(master) tesseract --list-langs
List of available languages (107):
...
chi_sim
chi_tra
...
````

````
➜  ocr  tesseract 2.jpg -l chi_sim result
Tesseract Open Source OCR Engine v3.04.00 with Leptonica
Warning in pixReadMemJpeg: work-around: writing to a temp file
Detected 56 diacritics
````

i use tesseract with the command line is ok.

---------------

is it not currently does not support tesseract 3.04.00 ?

Thank you

**Comment by 4F2E4A2E** [comment]
Hey there!

3.04 is currently not supported, please use one of the latest release, more info at the release page. 

To get it running under Linux it's very easy, although I have a Mac, I'd never have tried tess4j on a macosx. 

I will give it a try and get back to you.
Please post the information if you find out more. 

Best regards,
OJ

**Comment by fivesmallq** [comment]
@4F2E4A2E OK, Thank you，I will try it use tesseract 3.03.00 on Ubuntu.

**Comment by vovtz** [comment]
No need to use Ubuntu, because Tess4J works under OS X as well (at least under 10.10 - Yosemite). You do need to use the current release together with Tesseract 3.03 though.

**Comment by 4F2E4A2E** [comment]
Good to know! :)
Did you install tesseract via brew?

**Comment by vovtz** [comment]
No, I built it from source because (at the time?) version 3.03 was not available in the Homebrew repo.

**Comment by 4F2E4A2E** [comment]
Nice thanks.

**Comment by DavyLin** [comment]
@4F2E4A2E hello,i have the same error.Did you solve this error?

**Comment by 4F2E4A2E** [comment]
There was no error, only the datapath beeing not loaded correctly. Tell me more and i may be able to help you :)

**Comment by fivesmallq** [comment]
tesseract 3.04.00
 leptonica-1.72
  libjpeg 8d (libjpeg-turbo 1.3.0) : libpng 1.2.50 : libtiff 4.0.3 : zlib 1.2.8

tess4j-2.0.1 works well on Ubuntu 14.04 and JDK 1.8.0_77

**Comment by DavyLin** [comment]
@4F2E4A2E 
tesseract 3.0.2
leptonic-1.69
tess4j-1.5 
jdk1.7.0_45
datapath=/usr/local/share/

but the error info:

Failed loading language 'chi_sim'
Tesseract couldn't load any languages!
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000011c657a8a, pid=1578, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.dylib+0xf3a8a]  _ZN9tesseract8Classify18CharNormClassifierEP5TBLOBRK6DENORMP20INT_TEMPLATES_STRUCTP13ADAPT_RESULTS+0x7a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Volumes/HDD/work/ideaprojects/orctest/hs_err_pid1578.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

**Comment by DavyLin** [comment]
@4F2E4A2E 
tesseract 3.0.2
leptonic-1.69
tess4j-1.5 
jdk1.7.0_45
datapath=/usr/local/share/

but the error info:

**Comment by DavyLin** [comment]
@4F2E4A2E 
tesseract 3.0.2
leptonic-1.69
tess4j-1.5 
jdk1.7.0_45
datapath=/usr/local/share/

but the error info:
Failed loading language 'chi_sim'
Tesseract couldn't load any languages!

 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x000000011c657a8a, pid=1578, tid=5891

 JRE version: Java(TM) SE Runtime Environment (7.0_45-b18) (build 1.7.0_45b18)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (24.45-b08 mixed mode bsd-md64 compressed oops)
 Problematic frame:
 C  [libtesseract.dylib+0xf3a8a]  _ZN9tesseract8Classify18CharNormClassifireEP5TBLOBRK6DENORMP20INT_TEMPLATES_STRUCTP13ADAPT_RESULTS+0x7a

 Failed to write core dump. Core dumps have been disabled. To enable core umping, try "ulimit -c unlimited" before starting Java again

 An error report file with more information is saved as:
 /Volumes/HDD/work/ideaprojects/zhibird/zbOnline/hs_err_pid1578.log

 If you would like to submit a bug report, please visit:
   http://bugreport.sun.com/bugreport/crash.jsp
The crash happened outside the Java Virtual Machine in native code.
See problematic frame for where to report the bug.

**Comment by 4F2E4A2E** [comment]
Tess4j 1.5? Really? Why don't you use the latest version?

**Comment by DavyLin** [comment]
i found the information  in the sourceforege (http://tess4j.sourceforge.net/changelog.html)  i think about Tess4j 1.5 is supported for Tesseract 3.02.   i  try the latest version ,thank you!

**Comment by DavyLin** [comment]
@4F2E4A2E I found the information in the sourceforege (http://tess4j.sourceforge.net/changelog.html) i think about Tess4j 1.5 is supported for Tesseract 3.02. i try the latest version ,thank you!

**Comment by aceyin** [comment]
@4F2E4A2E  i got the same issue under Mac OS
tesseract, tesseract-eng and tesseract-chi-sim are all installed by port:
the version of tesseract is 3.04.00_3

the error messages are:
Failed loading language 'chi_sim'
Tesseract couldn't load any languages!

but if i switch the language back to "eng", it worked fine ...

the libraries i used are:
<dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>3.2.1</version>
        </dependency>
        <dependency>
            <groupId>com.github.jai-imageio</groupId>
            <artifactId>jai-imageio-core</artifactId>
            <version>1.3.1</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.1.0</version>
        </dependency>

could u pls help to have a look ?

**Comment by aceyin** [comment]
@DavyLin have u solved that issue?

**Comment by fivesmallq** [comment]
@aceyin use tesseract 3.04 to solve this issue.

**Comment by aceyin** [comment]
@fivesmallq i'am using tesseract 3.04, and this issue occurred in 3.04 also ...

**Comment by fivesmallq** [comment]
@aceyin 
![image](https://cloud.githubusercontent.com/assets/745063/16109939/eb68248e-33dd-11e6-8666-116b8a9113a3.png)


maven:

```xml
        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>2.0.1</version>
        </dependency>
```

➜ ~ tesseract -v
tesseract 3.04.01dev
leptonica-1.72
libjpeg 8d : libpng 1.6.20 : libtiff 4.0.6 : zlib 1.2.5

**Comment by 4F2E4A2E** [comment]
Hi guys! Did you for sure add and double checked that the lang-pack is in the correct by you define datafolder?

**Comment by aceyin** [comment]
@fivesmallq @4F2E4A2E 
thanks guys, but it didnot work under my Mac...
here are the tesseract version and lang package 
![image](https://cloud.githubusercontent.com/assets/482266/16117892/fb672a28-3406-11e6-9565-733c357e6856.png)

**Comment by 4F2E4A2E** [comment]
Maybe you are using the wrong language pack files? https://github.com/tesseract-ocr/langdata/tree/master/chi_sim

**Comment by aceyin** [comment]
@4F2E4A2E @fivesmallq 
i tried run tesseract from command line, and it worked.
![test](https://cloud.githubusercontent.com/assets/482266/16119041/4bb37a86-340c-11e6-9d9c-acab9c67a975.png)
so i think the problem should be something like path or classpath etc.

**Comment by 4F2E4A2E** [comment]
Can you confirm if english langpack is working?

**Comment by 4F2E4A2E** [comment]
@aceyin ?

**Comment by tonydeng** [comment]
@aceyin 
I was the same question, would you like to ask you now to solve it?

**Comment by struCoder** [comment]
@tonydeng 
you can download `chi_sim` or other languages from `https://github.com/tesseract-ocr/tessdata`
to your `/usr/local/Cellar/tesseract/3.04.01_2/share/tessdata`

**Comment by zcmgyu** [comment]
It also not work for me on macOS 10.12.3

**Tess4j latest version.**
```
<dependency>
    <groupId>net.sourceforge.tess4j</groupId>
    <artifactId>tess4j</artifactId>
    <version>3.2.1</version>
</dependency>
```
I did install tesseract-ocr frow brew. Latest version: 3.04.01_2

`brew install tesseract --all-languages`

```
Tesseract instance = new Tesseract();
instance.setDatapath("/usr/local/Cellar/tesseract/3.04.01_2/share/tessdata");
instance.setLanguage("jpn");
```

**Error:**

> 
> Failed loading language 'jpn'
> Tesseract couldn't load any languages!

**Comment by nguyenq** [comment]
Try with JNA 4.3.0 to see if it makes any difference.

And the path should be set the parent directory of `tessdata` directory:

`instance.setDatapath("/usr/local/Cellar/tesseract/3.04.01_2/share/");`

**Comment by zcmgyu** [comment]
You mean I just need add this repository into Maven? 

```
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>4.3.0</version>
</dependency>

<dependency>
    <groupId>net.sourceforge.tess4j</groupId>
    <artifactId>tess4j</artifactId>
    <version>3.2.1</v</dependency>
```

And I also change path into

```
ITesseract instance = new Tesseract(); // JNA Interface Mapping
instance.setDatapath("/usr/local/Cellar/tesseract/3.04.01_2/share");
instance.setLanguage("jpn");
```
It also throws that error message.

**Comment by nguyenq** [comment]
Yes. Can you try temporarily removing `eng.traineddata` file and renaming `jpn.traineddata` to that and see if that would work?

It is really a shot in the dark since we do not have Mac to investigate the issue. The library has been tested on Windows and Linux. JNA is the only piece that is different between the platforms since it has native components specific to an OS, so we think tracing through JNA code in debugging could help.

**Comment by zcmgyu** [comment]
Thanks for your reply.
But, It still throws that error message, though I rename jpn package to eng. 
I think problem derived from jpn package. 
It's a pity if you can't check on macOS environment.
I suggest you use Hackintosh in your PC. 
[hs_err_pid86067.log.zip](https://github.com/nguyenq/tess4j/files/765928/hs_err_pid86067.log.zip)

**Comment by nguyenq** [comment]
Someone commented in #34 that "All language data larger than about 20-25 MB cannot be loaded."

**Comment by zcmgyu** [comment]
Could you fix it in next version :D

**Comment by iseegr8tfuldeadppl** [comment]
Make sure the environment variable `TESSDATA_PREFIX` is set to your tessdata directory!
(for ex. `C:\msys64\mingw32\share\tessdata`).
