### ISSUE TITLE
JVM crash when run TessAPITest#testTessBaseAPIDetectOrientationScript with non-existent datapath

### ISSUE THREAD

**Issue by fredmafu** [nguyenq/tess4j#265]
Hello,
After I change "datapath" to a non-existent directory, 
![image](https://github.com/nguyenq/tess4j/assets/91316434/027c0b76-7ace-4dde-8a52-8fccada0b296)

run TessAPITest#testTessBaseAPIDetectOrientationScript and JVM crash after output these lines in console
![image](https://github.com/nguyenq/tess4j/assets/91316434/3f1c73a3-7929-45d1-883f-443a2ac935b8)

I tried to wrap the method body with try{...}catch(Throwable ex){...} block or call Native.setProtected(true) on the top but neither worked. 

This may be a potential risk if I embed the orientation detection code in my project and get "datapath" not properly configured after deployed. May I know how to catch the exception? Thank you so much for your response.

**Comment by nguyenq** [comment]
I don't think a Java client program can catch or handle exceptions thrown by the native code; it would crash the JVM.

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/crashes001.html

That said, you can code defensively by verifying the `datapath`, or its content, after setting it to make sure it's valid. Check the [documentation](https://tess4j.sourceforge.net/docs/index.html) for `GetAvailableLanguagesAsVector` or `GetLoadedLanguagesAsVector`.

**Comment by fredmafu** [comment]
Seems all methods in the Tesseract library that throw the assert exception by ASSERT_HOST(x) may cause the crash and no fatal error log file generated by JVM...
