### ISSUE TITLE
Tess4J should support Tesseract 3.04.00

### ISSUE THREAD

**Issue by mhinters** [nguyenq/tess4j#27]
https://github.com/tesseract-ocr/tesseract/releases/tag/3.04.00

**Comment by 4F2E4A2E** [comment]
Well indeed and we are preparing for that. But why do you think it should support it?

**Comment by marek-surek** [comment]
When do you expect a new release?

**Comment by nguyenq** [comment]
Very soon, before year end. The core OCR functionality has been complete. We're wrapping up on the final piece of PDF-to-image conversion. Please help test the code in the master branch and post your feedback.

Thank you.

**Comment by mhinters** [comment]
Thanks for releasing tess4j-3.0.0!
