### ISSUE TITLE
liblept.so.4: cannot open shared object file

### ISSUE THREAD

**Issue by lukiant-dev** [nguyenq/tess4j#28]
Hello!
Unfortunately I am not able to run tesseract through tess4j on Linux (CentOS). 
I think that tesseract is being loaded correctly with JNA, but for some reason he can't find liblept.so.
Is it possible to somehow tell tesseract which is loaded through JNA where he should look for liblept.so?
Or maybe it would be possible to compile tesseract in such way that leptonica shared library wouldn't be needed at execution time?

NOTE1: I can't set LD_LIBRARY_PATH environment variable. It solves the problem but cannot be done on my system.
NOTE2: Leptonica is not installed on local machine.
NOTE3: I have compiled Tesseract from the source (tried github master branch and 3.02 from sourceforge).

**Comment by 4F2E4A2E** [comment]
Hi there! 

Which version of tess4j and centos are you using?

**Comment by lukiant-dev** [comment]
tess4j  src from master branch
CentOS 6.7 x64

**Comment by guggi1** [comment]
Hi, I am having the same issue. 

Using Tess4j-2.0.1.jar which comes with Tesseract 3.03 and Leptonica 1.7.

It works fine on Tomcat under Windows but Linux won't work.
I have compiled Tesseract and Leptonica on my Linux Servers and taken the libtesseract.so file and it recognizes it. So far so good. However the liblept.so.4 is not recognized anywhere. 
I have tried the following:

1. gave full permission (chmod 777 liblept.so.4)

2. placed the liblept.so.4 under user/local

3. placed the liblept.so.4 under user/local/share

4. added the liplept.so.4 to the tess4j JAR (together with libtesseract.so) under /linux-x86-64

5. placed the liblept.so.4 under TOMCAT_HOME/lib and set the path in the wrapper of tomcat.config
(wrapper.java.additional.4=-Djna.library.path=%TOMCAT_HOME%/lib)

6.  tried to work with LD_LIBRARY_PATH 

7. Placed it under WEB-INF/classes

Always the same error:
UnsatisfiedLinkError: liblept.so.4: cannot open shared object file: No such file or directory

**Comment by mhinters** [comment]
Had the same problem, solved it for me by loading liblept.so in the static-block in LoadLibs. So leptonica.so is loaded **before** tesseract is loaded by calling getTessAPIInstance.

**Comment by guggi1** [comment]
Very smart approach. I will try it. Did you use the static function?
System.loadLibrary("liblept");

**Comment by mhinters** [comment]
Yes, I packed liblept.so.4 with tess4j, extracted it to the tempdir like tess4j does with tesseract and called 
System.load(targetTempFolder + "/liblept.so.4");

**Comment by guggi1** [comment]
People, mhinters rules! Thanks. It worked.

Please note: 
1. Using System.loadLib("liblept") did not work although the file was present in the java.library.path (Tesseract tries to load from a different place)
2. We have also tried renaming "liblept.so.4" to "liblept.so" which did not work

The only thing was to give the real full path of "liblept.so.4" to the static function and calling it before Tesseract does, like this:

System.load("/opt/tomcat7/project/liblept.so.4") ;

mhinters, thanks again.

**Comment by 4F2E4A2E** [comment]
You can also create a symlink.
