### ISSUE TITLE
Example for stopping tesseract using ETEXT_DESC monitor

### ISSUE THREAD

**Issue by mhinters** [nguyenq/tess4j#29]
I have no idea how tessearct could be stopped using ETEXT_DESC.cancel CANCEL_FUNC. An example like ProgressMonitor would be great.

**Comment by nguyenq** [comment]
Just as specified in the [doc](http://tess4j.sourceforge.net/docs/docs-3.0/net/sourceforge/tess4j/ITessAPI.ETEXT_DESC.html). An example can also be found in the unit test.

```
ETEXT_DESC monitor = new ETEXT_DESC();

// while OCR is running in some thread, set, for instance, inside ProgressMonitor:
monitor.cancel = new CANCEL_FUNC() {
    @Override
    public boolean invoke(Pointer cancel_this, int words) {
        return false;   // return true to cancel
    }
};
```

**Comment by mhinters** [comment]
Thanks!

**Comment by magorismagor** [comment]
Hi @mhinters,

Did that solution work for you?. 

I implemented a code that tries to stop tesseract if the processing lasts more than 5 seconds. However tesseract does not stop.

My code: 

```
// Create monitor and Progress Monitor
ETEXT_DESC monitor = new ETEXT_DESC();
ProgressMonitor pmo = new ProgressMonitor(monitor, api);
pmo.start();

// Call tesseract
TessAPI1.TessBaseAPISetImage(handle, ImageIOHelper.getImageByteBuffer(image), image.getWidth(), image.getHeight(), bytespp, bytespl);
TessAPI1.TessBaseAPIRecognize(handle, monitor);
LOGGER.debug("Message: " + pmo.getMessage());
```

And the code of the progressMonitor is:

``public class ProgressMonitor extends Thread {

    ITessAPI.ETEXT_DESC monitor;
    StringBuilder outputMessage = new StringBuilder();
    TessAPI api;

    public ProgressMonitor(ITessAPI.ETEXT_DESC monitor, TessAPI api) {
        this.monitor = monitor;
        this.api = api;
    }

    public String getMessage() {
        return outputMessage.toString();
    }

    private int timeToSleep = 500; //ms
    private int totalTime = 5000; // ms
    
    @Override
    public void run() {
        int time = 0;
        try {
            while (true) {
                System.out.println("ocr alive: " + (monitor.ocr_alive == TRUE));
                System.out.println("progress: " + monitor.progress);
                outputMessage.append(monitor.more_to_come);
                if (monitor.progress >= 100) {
                    break;
                }
                Thread.sleep(timeToSleep);
                time += timeToSleep;

                if (time > this.totalTime) {
                    System.out.println("Call to cancel...");
                    cancel();
                    break;
                }
            }
        } catch (Exception ioe) {
            ioe.printStackTrace();
        }
    }

    /**
     * Cancels OCR operation.
     */
    public void cancel() {
        monitor.cancel = new ITessAPI.CANCEL_FUNC() {
            @Override
            public boolean invoke(Pointer cancel_this, int words) {
                 System.out.println("Calling with " + words  +" words");
                return true;
            }
        };
    }

    /**
     * Resets cancel flag.
     */
    public void reset() {
        monitor.cancel = null;
    }
}``


Any advice?.

**Comment by mhinters** [comment]
Hi,
no it didn't work. It stopped after Tesseract had internally finished
processing the image.Also the progress was useless for me, as it jumped
from 0 to 100 percent when done.
Sorry, no advice.

Kind regards,
Michael


2018-03-01 15:34 GMT+01:00 magorismagor <notifications@github.com>:

**Comment by magorismagor** [comment]
Hi,

Exactly the same behaviour here. I hope @nguyenq can help with this issue.

Thanks for you reply.
Alberto.
