### ISSUE TITLE
NoClassDefFoundError: net/sf/ghost4j/GhostscriptException

### ISSUE THREAD

**Issue by luis08** [nguyenq/tess4j#30]
We are having trouble making the code below work.  Could it be the PdfUtilities? 
We really appreciate any help.  The stack trace is at the bottom.  Let us know if you need more information.

Environment
============================================
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

Code
============================================
package com.jantogal.test.pdf;
//import org.ghost4j.Ghostscript;
//import org.ghost4j.GhostscriptException;
import java.io.File;
import net.sourceforge.tess4j.Tesseract;
import net.sourceforge.tess4j.TesseractException;
import net.sourceforge.vietocr.PdfUtilities;

public class App 
{
	private static final String TEST_FILE_PATH = "~/workspace/pdfs/FT0.pdf";
    public static void main(String[] args) {
        Test02();
    }
    private static void Test02(){
        Tesseract instance = Tesseract.getInstance();
        File pdfDoc = new File(TEST_FILE_PATH);
        File pngImageFiles[] = PdfUtilities.convertPdf2Png(pdfDoc);

        for (int i = 0; i < pngImageFiles.length; i++) {
          try {
			String ocrResult = instance.doOCR(pngImageFiles[i]);
			System.out.println(ocrResult);
			} catch (TesseractException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
          System.console().readLine();
        }
    }
}

Solutions attempted:
================================
(1) Tried including Ghostscript ghost4j 1.0.0  in the maven dependencies. The library was in the classpath correctly.
   Results:  Stack trace shown below - Note: I was able to instantiate Ghostscript objects using the factory without any issues inside void main.
(2) Followed the solution described here https://github.com/nguyenq/tess4j/issues/4 
   Results: same as (1)

Stack Trace:
================================
The issue happens on the line ** File pngImageFiles[] = PdfUtilities.convertPdf2Png(pdfDoc);**

We are just testing for the moment.  The exception is: 
Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/ghost4j/GhostscriptException
	at com.jantogal.test.pdf.App.Test02(App.java:24)
	at com.jantogal.test.pdf.App.main(App.java:19)
Caused by: java.lang.ClassNotFoundException: net.sf.ghost4j.GhostscriptException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more

**Comment by 4F2E4A2E** [comment]
Don't worry, we will get this running ;)

Did you install gs on Ubuntu?
Did you install tesseract on Ubuntu?

Tess4J unfortunate has only the Windows native dlls dependencies. 

I guess I will have to post an tutorial explaining on how to with Linux.

**Comment by luis08** [comment]
Thanks for your reply
**installed tesseract**:
luis@java:~$ sudo apt-get install tesseract-ocr
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tesseract-ocr is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 164 not upgraded.

**installed ghostscript**
luis@java:~$ sudo apt-get install libgs-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libgs-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 164 not upgraded.
luis@java:~$ sudo apt-get install ghostscript
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ghostscript is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 164 not upgraded.
luis@java:~$ 


Anything else I should do?   Thanks again!

**Comment by 4F2E4A2E** [comment]
Nope, that should do it. 
Do you have any stack trace for me?

**Comment by 4F2E4A2E** [comment]
Hey there, try setting the data path as [described](https://github.com/nguyenq/tess4j/wiki/Code-Sample) and link the .so files in there.

The .so files are not inside the jar only the .dll files, so you have to tell tess4j where to look for if the files are not present in the class path or not accessible through the environment variable of your system. 

Howto video is in the making.

Cheers

**Comment by 4F2E4A2E** [comment]
I will take the time today to go over this, are you going to be around?

**Comment by luis08** [comment]
Sorry I have not followed up.  Today is very difficult for me.  I have been traveling and will not be back to the office for another 2 1/2 weeks. I will try to reproduce next Tuesday or Wednesday in a VM.

Thanks for your attention to this.

**Comment by 4F2E4A2E** [comment]
hey there, i got it running on an ubuntu server 14 without a problem, here is what i did:
`apt-get update
apt-get install tesseract-ocr ghostscript openjdk-7-jdk`

After that i just created an maven project adding the [tess4j dependecy](http://search.maven.org/#artifactdetails%7Cnet.sourceforge.tess4j%7Ctess4j%7C3.0.0%7Cjar) with a junit test class from the [examples](https://github.com/nguyenq/tess4j/wiki/Code-Sample) and then ran it, with mvn test, that's all.

Here is the example project: 
[tess4j-example.zip](https://github.com/nguyenq/tess4j/files/129281/tess4j-example.zip)

**Comment by LinhTH** [comment]
Hi,
I'm running into a problem with PdfUtilities when reading text from **PDF** files on Ubuntu (it works well on both Window and Macos). 

It throws an exception as following:

> 10:41:20.535 [main] ERROR net.sourceforge.tess4j.Tesseract - Invalid calling convention 63
> java.lang.IllegalArgumentException: Invalid calling convention 63
>         at com.sun.jna.Native.createNativeCallback(Native Method) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.CallbackReference.<init>(CallbackReference.java:239) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:413) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.CallbackReference.getFunctionPointer(CallbackReference.java:395) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.Function.convertArgument(Function.java:541) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.Function.invoke(Function.java:305) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.jna.Library$Handler.invoke(Library.java:236) ~[jna-4.2.1.jar:4.2.1 (b0)]
>         at com.sun.proxy.$Proxy10.gsapi_set_stdio(Unknown Source) ~[na:na]
>         at org.ghost4j.Ghostscript.initialize(Ghostscript.java:323) ~[ghost4j-1.0.0.jar:na]
>         at net.sourceforge.tess4j.util.PdfUtilities.convertPdf2Png(PdfUtilities.java:103) ~[classes/:na]
>         at net.sourceforge.tess4j.util.PdfUtilities.convertPdf2Tiff(PdfUtilities.java:48) ~[classes/:na]
>         at net.sourceforge.tess4j.Tesseract.createDocuments(Tesseract.java:534) ~[classes/:na]
>         at net.sourceforge.tess4j.TesseractTest.testCreateDocuments(TesseractTest.java:227) [test-classes/:na]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
>         at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
>         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.12.jar:4.12]
>         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
>         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.12.jar:4.12]
>         at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.12.jar:4.12]
>         at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
>         at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.4.jar:2.12.4]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_79]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_79]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_79]
>         at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]
>         at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115) [surefire-booter-2.12.4.jar:2.12.4]
>         at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.4.jar:2.12.4]

My system:
* Ubuntu14.04 64bit
* JVM 1.7.0_79 64 bit
*  Ghostscript 9.18
* Tess4J Release 3.0.0

Thanks

**Comment by 4F2E4A2E** [comment]
Hey! Welcome to the Linux support ticket :)

Which code are you trying to get running? The example project attached or are you trying to build tess4j from the sources?

Did you run mvn install before running mvn test?

Please try the example project, thanks. 

Dear all: please understand that tess4j depends on native libraries (Tesseract and Ghostscript) that are accessible on the OS and loaded in order to run.

**Comment by LinhTH** [comment]
Hi,
Thanks for your reply.
I have already ran two cases above with a PDF file as the input, getting the same exception but worked well with image files.

i also built a project using only ghost4j dependency,copied convertPdf2Png function from PDFUtilities Class and ran it. it worked well.

Regards,

**Comment by LinhTH** [comment]
Hi 4F2E4A2E,
in #20, I saw that you replaced ghost4j by pdfbox, but the release version still use ghost4j??

**Comment by 4F2E4A2E** [comment]
Yeah, the PDFBox API is way better and does  not depend on a native Lib, but the performance was bad, so we got back to Ghostscript. 

Is it working for you now? Did you try to set the datapath as in the example project?

Please post the code / goal you are trying to get running so I can try it later on.

**Comment by LinhTH** [comment]
Hi,
I run the simple code as following:

`	public static void main(String[] args) {
		String fileURL = args[0];
		String nativeURL = args[1];
		
        File imageFile = new File(fileURL);

       Tesseract instance = Tesseract.getInstance();  // JNA Interface Mapping
//        Tesseract1 instance = new Tesseract1(); // JNA Direct Mapping
        
        instance.setDatapath("tessdata");
        
        NativeLibrary.addSearchPath("libtesseract304", nativeURL);
        NativeLibrary.addSearchPath("gsdll64", nativeURL);

        try {
        String result = instance.doOCR(imageFile);
        System.out.println(result);
        } catch (TesseractException e) {
        System.err.println(e.getMessage());
        }
 }`

Could you send me the project using PDFBox API ? 
Thanks,

**Comment by 4F2E4A2E** [comment]
This is the Version using PDFBox: https://github.com/nguyenq/tess4j/tree/b0e054a834056c5f02e0a9f8b41812ac6eb7c780

Try to add the path where the .so files are inside as an param to the NativerLibrary.addSeachPath().
You can find those with something like this:
```
locate .so | grep gs
locate .so | tess

@nguyenq what do you think?

**Comment by 4F2E4A2E** [comment]
Can we close this? Problem solved?

**Comment by luis08** [comment]
Just got back from traveling.  Can we hang on for this week?

**Comment by 4F2E4A2E** [comment]
Sure. 

> Am 02.03.2016 um 13:43 schrieb luis08 <notifications@github.com>:
> 
> Just got back from traveling. Can we hang on for this week? 
> 
> Sent from my iPhone 
>

**Comment by nguyenq** [comment]
I remember I had problems with GS 9.18 on Windows, so I stayed with 9.16. Ubuntu did not have the same issue, I recall, but you may want to try with that GS version.

**Comment by 4F2E4A2E** [comment]
@luis08 any status update for us?

**Comment by luis08** [comment]
It worked on a VM.  I'll try again in the
physical server.  Let's close it and I'll follow up if I find any issues.  

Thanks for all your help.
