### ISSUE TITLE
TessAPI1.TessBaseAPIRecognize(handle, null); Invalid memory access @question

### ISSUE THREAD

**Issue by bezlajk** [nguyenq/tess4j#31]
Hay.

I have posted my question on Stackoverflow http://stackoverflow.com/questions/35295582/tess4j-memory-access-error-in-tess4j-java ...  but I still can't solve the error... I tried to see if the problem in in bufferimage but the image bufft oky and the images on which its working or not are the same; same format, same resolution, 

hear prints of image and Baytbuff of which program workse oky
BufferedImage@169c6ba: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@daef40 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 2550 height = 4200 #numDataElements 3 dataOff[0] = 2            
its Bytebuffer : java.nio.DirectByteBuffer[pos=0 lim=32130000 cap=32130000]

image on which returns below error:
BufferedImage@169c6ba: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 color space = java.awt.color.ICC_ColorSpace@daef40 transparency = 1 has alpha = false isAlphaPre = false ByteInterleavedRaster: width = 2550 height = 4200 #numDataElements 3 dataOff[0] = 2 
its Baytbuff: java.nio.DirectByteBuffer[pos=0 lim=32130000 cap=32130000] 

Exception in thread "main" java.lang.Error: Invalid memory access
	at net.sourceforge.tess4j.TessAPI1.TessBaseAPIRecognize(Native Method)
	at TesseractUtility.TessFoLogo.testResultIterator(TessFoLogo.java:125)
	at TesseractUtility.TessFoLogo.main(TessFoLogo.java:76)

Please help me... where can I search for bug.

**Comment by nguyenq** [comment]
"Invalid memory access" usually means the datapath is not set or set to an incorrect path. Please attach your problematic image for our investigation.

**Comment by bezlajk** [comment]
![004](https://cloud.githubusercontent.com/assets/5883205/13219663/bfc72990-d971-11e5-8e79-9a3cd2e01140.jpg) .....this is one of problematic images
![007](https://cloud.githubusercontent.com/assets/5883205/13219731/34423850-d972-11e5-861d-adf43628fc77.jpg) ... on this image my progam works. 
They, how ever, are located in the same folder and images do buff.
Thx for quick answer.

**Comment by nguyenq** [comment]
First of all, no image is exactly the same. The problematic image, after applying grayscale and monochrome filters, produced results.

**Comment by bezlajk** [comment]
Thx for quick answer. Now it works for more images, still not for all but it is better. Thank you.
