### ISSUE TITLE
Change from tess4j 2.0.1 to 3.1.0

### ISSUE THREAD

**Issue by sonik340** [nguyenq/tess4j#33]
Hello. I try to go from tess4j 2.0.1 to 3.1.0. I just changed the version of tess4j in my pom (Maven) and the java version to 1.7. Everything compile in a good way. The problem is that when I launch my tests in the same way as before (and it worked) tesseract did not find the language files.
The matter must come from the new version because when I go back to 2.0.1 in java 1.6 I do the work the same as before.

**Comment by 4F2E4A2E** [comment]
Hi there. We are glad to hear you are upgrading. Please consider the example code in the wiki, adapt you Java Code and get back to us with a feedback. Setting the tessdata path should be enough. 

Beste Grüße,
O.J. Sousa Rodrigues
+43 664 8879 555 9

**Comment by nguyenq** [comment]
Don't hear from OP. Please reopen if you have more details.

Thanks.
