### ISSUE TITLE
Is there any examples on how to usee tess4J to detect table?

### ISSUE THREAD

**Issue by johnny5550822** [nguyenq/tess4j#36]
Is there any examples on how to usee tess4J to detect table?

**Comment by nguyenq** [comment]
I don't think Tesseract has the ability to detect tables, the borders of which will present a problem for Tesseract. Lept4J has `removeLines` method, which can be used to remove the table's borders before OCR.

**Comment by johnny5550822** [comment]
Yes, the removeLines option I have looked into it. Thanks. 

I think Lept4J has a memory issue for one of the example. 

https://github.com/nguyenq/lept4j/issues/2

**Comment by nguyenq** [comment]
Not an issue.
