### ISSUE TITLE
dude need some guidance

### ISSUE THREAD

**Issue by scottwhendrickson** [nguyenq/tess4j#37]
scottwhendrickson@gmail.com

**Comment by 4F2E4A2E** [comment]
Sure, why not, but why don't you just write down in here what you need?

**Comment by scottwhendrickson** [comment]
Thanks for the response. Was struggling with certain images not being
readable by tesseract while using your tess4j wrapper. Pre processing of
the image helped me get past that. Will dude u again when I hit the next
wall.

scotth

**Comment by nguyenq** [comment]
Please reopen if you need further help.

Thanks.

**Comment by scottwhendrickson** [comment]
Thanks again.

scotth
