### ISSUE TITLE
Maven break

### ISSUE THREAD

**Issue by bromoapp** [nguyenq/tess4j#39]
Hi,

I just clone your rep to my local to try out, but when I import the project into my eclipse, the POM editor shows a failure message says = Failure to transfer commons-collections:commons-collections:jar:3.2.1 from https bla bla bla...

So I went to maven repo, and found out that commons-collections already moved to common-collections4. I try to resolve this issue in local but I couldn't

Please advice, thanks Nguyen :)

**Comment by 4F2E4A2E** [comment]
I will check that by time, but it seams to be an maen issue on your local repo. Try to remove the complete .m2 folder (first backup your settings.xml - if you have any) and then run again.

**Comment by bromoapp** [comment]
I delete commons-collections inside .m2 directory and solved the issue ... thanks, you are savior :)
