### ISSUE TITLE
Add tesseract linux-x86-64 shared objects to the distribution

### ISSUE THREAD

**Issue by mjw99** [nguyenq/tess4j#4]
Currently, only win32-x86 and win32-x86-64 are supported via .dlls that are in the distro, but it is possible to get tess4j working under linux via:

    sudo apt-get install tesseract-ocr tesseract-ocr-vie
    export TESSDATA_PREFIX=/usr/share/tesseract-ocr/

However, with code that uses tess4j, and is monitored with a linux continuous integration server that one does not have the ability to install libraries to, this is not possible. Hence, would it be possible to add {32.64} bit tesseract linux .so s to the repo?

**Comment by redserpent7** [comment]
How were you able to make it run on ubuntu 64, I've been trying to make it work for several days now and all I get is this error

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f56bb919409, pid=11080, tid=140011019564800
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libtesseract.so.3.0.3+0x87409]  tesseract::TessBaseAPI::Init(char const*, char const*, tesseract::OcrEngineMode, char**, int, GenericVector<STRING> const*, GenericVector<STRING> const*, bool)+0x39
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

**Comment by 4F2E4A2E** [comment]
Hi there! Don't worry, we will get that running, give me some time and I will get back to you with an example. 

Which Version are using, I can see Java 8, but the rest of it? OS? Tess4J?

**Comment by redserpent7** [comment]
Hi, 

Thank you for taking the time to look into it. I am running my app on Ubuntu 14.04 server 64-bit. I downloaded the latest tess4j from maven central repo v2.0.1 and as you can see in using openjdk 8.



-----Original Message-----

**Comment by 4F2E4A2E** [comment]
Hi there, sorry for beeing late, this is what you have to do:
1. Install Ubuntu Server 14.04 and JDK8 (Oracle -> http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/ or OpenJDK -> http://ubuntuhandbook.org/index.php/2015/01/install-openjdk-8-ubuntu-14-04-12-04-lts)
2. install maven 3 (download, unzip and ln -s <mvn-file> /usr/bin/mvn)
3. download tess4j source wget https://github.com/nguyenq/tess4j/archive/tess4j-2.0.1.zip
4. apt-get -y install tesseract-ocr ghostscript
5. run mvn install

Please notice that Tess4J Release 2.0.1 uses Tesseract 3.0.3 and Leptonica 1.71 (or Leptonica 4):
```bash
root@ubuntu:/home/eduard/tess4j-tess4j-2.0.1# locate tesseract | grep so
/usr/lib/libtesseract.so.3
/usr/lib/libtesseract.so.3.0.3
root@ubuntu:/home/eduard/tess4j-tess4j-2.0.1# locate liblept | grep so
/usr/lib/liblept.so.4
/usr/lib/liblept.so.4.0.1
```

I did notice that you are actually using JDK 8 SE from Oracle and not the mentioned OpenJDK 8.
All tests successfull on Ubuntu 14.04 x64.

**Comment by redserpent7** [comment]
Thank you I'll try and test it first thing in the morning. Hope it works

	
Zaid Amir
Software Development
 
Genie9
Backup Redefined
..............................................................................................................
Email: mailto:zaid.a@genie9.com Web: http://www.genie9.com

**Comment by redserpent7** [comment]
Thank you so much it works now. I installed JDK 8 by Oracle and had a couple of issues during the test phase. I will list my fixes here for reference:

I had to manually install libxrender1 and libxi6:

```sudo apt-get libxrender1
sudo apt-get libxi6```

I was SSH tunneling to the server, so no display was present and it seems two of the tests required a display to work, so I added the surefire plugin to the pom.xml and used headless mode:

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>2.14</version>
    <configuration>
      <systemProperties>
        <java.awt.headless>true</java.awt.headless>
      </systemProperties>
    </configuration>
</plugin>
```

I ran mvn install and all tests worked and I had my jar files.

Thanks

**Comment by 4F2E4A2E** [comment]
Great to read that! Thank you for giving us a feedback. Please help us to grow and post the name of your company or customer so we can add it here: https://github.com/nguyenq/tess4j/wiki/Who-is-using-Tess4J
