### ISSUE TITLE
Error:Assert failed:in file ratngs.cpp, line 321

### ISSUE THREAD

**Issue by mhinters** [nguyenq/tess4j#40]
Some images are crashing tess4j with the message:
**start >= 0 && start + num <= length_:Error:Assert failed:in file ratngs.cpp, line 321**,
causing java.lang.Error: Invalid memory access.
Processing the same image with tesseract from the commandline (generating hocr) works fine.
Any ideas?

**Comment by 4F2E4A2E** [comment]
Which type and size of images? Can you provide a sample? Which version of your OS, JDK and Tess4J?

**Comment by 4F2E4A2E** [comment]
Alright, then you write the tutorial afterwards ;)

1. Get your Alfresco 5.1 up and running
2. Deploy the zefiro war file (v1.0.0 at first) on another tomcat
3. Change this line in under zefiro\WEB-INF\classes\jbrickConfig.xml:
```
<alfresco baseTypeId="D:mio:mioDocument" host="http://10.232.1.210:8080" rootFolderId="dd44465f-7563-4130-b672-b49dfb254e06"/>
```
3.1 to this:
```
<alfresco baseTypeId="cmis:document" host="http://localhost:8080" rootFolderId="<add your own folder id in here!"/>
````

I still don't understand the use case for zefiro, but in this way i got it running and was able to "use" it.

**Comment by nguyenq** [comment]
Please post your code and an example image.

**Comment by mhinters** [comment]
Sorry for not responding, was busy with other things. The code is available at https://github.com/mhinters/tess4j2any, but I'm sorry, I can't provide a sample image. The error happens approximatly with one of 1000 images, using deu_frak, but I was'n able to recognize a pattern yet.
Thanks for your support!

**Comment by 4F2E4A2E** [comment]
@mhinters can you please provide something? A log? What kind of images are those? How big? Which OCR-Class? Command? API-Call? 

Otherwise, how can we help you!?

**Comment by mhinters** [comment]
no longer relevant.

**Comment by 4F2E4A2E** [comment]
Did you solve it? If yes, how?
