### ISSUE TITLE
Can I have working Jar file under Ubuntu 15.1 and Cent OS 7?

### ISSUE THREAD

**Issue by dmitrirussu** [nguyenq/tess4j#44]
Hi, I want to build app for linux, and I see the some dependency on that library related to Win x86,x64? can I have working Jar file for Linux. may you have already a solution for that?

thanks

**Comment by 4F2E4A2E** [comment]
Hi there! Some where along the project we decided to package and deliver only the windows binaries. If you want to develop in linux, just pass the right binaries (.so) into the  instance.setDatapath method and all should be good.

**Comment by nguyenq** [comment]
Once you installed Tesseract on Linux and proved it work by successfully executing `tesseract` command, Tess4J will automatically work with the installed Tesseract library.
