### ISSUE TITLE
Include special characters when looking for character coordinates

### ISSUE THREAD

**Issue by delkant** [nguyenq/tess4j#45]
How to include white spaces, tabs or special characters when looking for character coordinates??

I found out that I will get character coordinates using 

int level = TessPageIteratorLevel.RIL_SYMBOL; (instead of RIL_WORD)

https://github.com/nguyenq/tess4j/blob/master/src/test/java/net/sourceforge/tess4j/TessAPI1Test.java#L465

The thing is that this will exclude other characters that are important to me. By important I mean I want to be able to provide text that make sense to humans too(with spaces, end lines, tabs).

So I really need to have the full OCR result of an image and also the coordinates of each character including special characters. Is this possible? Thanks.

**Comment by nguyenq** [comment]
I confirmed your findings, which by the way is consistent with the native Tesseract's behavior. As such, I suggest you to repost your question on Tesseract [Forum](https://groups.google.com/forum/#!forum/tesseract-ocr). Hope one of Tesseract developers will respond, and suggest a workaround, if any.

**Comment by delkant** [comment]
This is a Tesseract issue and has nothing to do with tess4j
