### ISSUE TITLE
How to use multi thread in tess4j

### ISSUE THREAD

**Issue by ykchina** [nguyenq/tess4j#46]
How to use multi thread in tess4j

**Comment by nguyenq** [comment]
A good example can be found in [this Forum's post](https://sourceforge.net/p/tess4j/discussion/1202293/thread/4562eccb/).

**Comment by ykchina** [comment]
So each time to initialize the tessdata data CPU directly soared to 100% and the resolution time will be doubled

**Comment by ykchina** [comment]
I am using tess4j3.2

**Comment by jedisniper17** [comment]
Yes, when I use 3.0.2 in multi thread, it was as quickly and threads works simultaneous. But when I upgraded to use 3.0.5 (tesseract305.dll with VC redistribution for X86 installed). It seems like the threads works in a sequence which take much longer time to do OCR.

**Comment by nguyenq** [comment]
Each instance of tesseract has its own copy of native resources, including `.traineddata` file, plus the images being processed, so it could consume quite a bit of system resources if you run in multi threads. Having too many threads certainly could adversely impact performance.

**Comment by NirHershkovitz** [comment]
What is the difference between Tesseract1 and Tesseract?

**Comment by nguyenq** [comment]
One uses JNA Direct Mapping; the other, JNA Interface Mapping. There's supposedly difference in performance.

https://github.com/java-native-access/jna

**Comment by nguyenq** [comment]
No response from OP.
