### ISSUE TITLE
How to change symbol value in TessResultIterator

### ISSUE THREAD

**Issue by truonghaophu** [nguyenq/tess4j#47]
Hi everyone, I am currently working on a project using Tess4J. I want to change the symbol value in the TessResultIterator like this:

```Java
TessResultIterator ri = api.TessBaseAPIGetIterator(handle);
TessPageIterator pi = api.TessResultIteratorGetPageIterator(ri);
api.TessPageIteratorBegin(pi);
int level = TessPageIteratorLevel.RIL_SYMBOL;
do {
    Pointer ptr = api.TessResultIteratorGetUTF8Text(ri, level);
    String symbol = ptr.getString(0);
    float confidence = api.TessResultIteratorConfidence(ri, level);
    if (confidence < 80){
        Rectangle rect =    // get symbol rect
        String newSymbol = doMyStuff(rect);
        ptr.setString(0, newSymbol);    // something like this
    }
} while (api.TessPageIteratorNext(pi, level) == TRUE);

Pointer utf8Text = api.TessBaseAPIGetUTF8Text(handle);
String result = utf8Text.getString(0);    // get final result here

```

How can I achieve something like that? I searched the API and have found TessMutableIterator, but I can’t make it work.
Any help would be appreciated. Thanks for your attention.

**Comment by nguyenq** [comment]
`TessResultIterator` is an immutable object, so I don't think you can change its internal state. You may want to dig into [Tesseract](https://github.com/tesseract-ocr/tesseract) code to find usage of `TessMutableIterator` class.

**Comment by truonghaophu** [comment]
Thanks for the answer 👍
