### ISSUE TITLE
How to use the picture to do some processing to improve the recognition rate?

### ISSUE THREAD

**Issue by evanosc** [nguyenq/tess4j#48]
Hello, I would like to use tess4j tool optimization accuracy, is there any relevant case reference?

        File imageFile = new File("d:\\9.jpg");
        ITesseract instance = new Tesseract(); // JNA Interface Mapping // JNA Interface Mapping
        // ITesseract instance = new Tesseract1(); // JNA Direct Mapping
        instance.setDatapath("D:\\Java\\Tesseract-OCR\\tessdata"); // replace <parentPath> with path to parent directory of tessdata
        instance.setLanguage("eng");
        
        try {
        	BufferedImage bi = ImageIO.read(imageFile);
            String result = instance.doOCR(imageFile);`

**Comment by nguyenq** [comment]
To get better OCR accuracy, some image preprocessing may be needed.

[ImproveQuality](https://github.com/tesseract-ocr/tesseract/wiki/ImproveQuality)

You can use Java ImageIO, Leptonica, or OpenCV library to implement those techniques.

**Comment by evanosc** [comment]
@nguyenq Hello, I will code the deployment to the production environment, the implementation of String result = instance.doOCR (grayImage); to stop, the back is not implemented. Nor throws TesseractException
My code is as follows:
`try {
			//将base64图片转为InputStream
			InputStream isImage = Base64Image.BaseToInputStream(base64Image);
			
	        ITesseract instance = new Tesseract(); 
	        //centos:yum install tesseract     
//	        instance.setDatapath("/usr/share/tesseract/tessdata"); // 确保该目录下有tesseract的tessdata
	        File tessDataFolder = LoadLibs.extractTessResources("tessdata");
	        instance.setLanguage("eng");
	        instance.setDatapath(tessDataFolder.getAbsolutePath());  //获取项目下的tessdata文件
	        
	        BufferedImage bimage = ImageIO.read(isImage);  
			// 这里对图片黑白处理,增强识别率.这里先通过截图,截取图片中需要识别的部分  
			BufferedImage textImage = ImageHelper.convertImageToGrayscale(bimage); 
			// 图片锐化,自己使用中影响识别率的主要因素是针式打印机字迹不连贯,所以锐化反而降低识别率
			textImage = ImageHelper.convertImageToBinary(textImage);  
			// 图片放大5倍,增强识别率(很多图片本身无法识别,放大5倍时就可以轻易识,但是考滤到客户电脑配置低,针式打印机打印不连贯的问题,这里就放大5倍)
			textImage = ImageHelper.getScaledInstance(textImage, textImage.getWidth() * 5, textImage.getHeight() * 5);  
//			String result = instance.doOCR(textImage);
			log.info("2222="+2222);
			String result = instance.doOCR(textImage);
//	        String result = instance.doOCR(grayImage);
            log.info("result="+result);
            Pattern pattern = Pattern.compile("([A-Z]\\d{8})");
			Matcher matcher = pattern.matcher(result);
			if (matcher.find()) {
				ret.put("word", matcher.group(1));
			} else {
				ret.put("word", "");
			}
			ret.put("status", true);
		} catch (TesseractException e) {
			log.info("error="+e);
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}`

**Comment by evanosc** [comment]
error=java.lang.UnsatisfiedLinkError: Unable to load library 'tesseract': Native library (linux-x86-64/libtesseract.so) not found in resource path ([file:/root/sinoicity/tomcat/tomcat_8867_temp/webapps/HealthMonitor/WEB-INF/classes/, file:/root/sinoicity/tomcat/tomcat_8867_temp/webapps/HealthMonitor/WEB-INF/lib/spring-jdbc-3.2.0.M1.jar, file:/root/sinoicity/tomcat/tomcat_8867_temp/webapps/HealthMonitor/WEB-INF/lib/jersey-media-json-jackson-2.9.jar, file:/root/sinoicity/tomcat/tomcat_8867_temp/webapps/HealthMonitor/WEB-INF/lib/commons-jxpath-1.2.jar

**Comment by nguyenq** [comment]
Did tesseract install properly and is it in system path?

I think you will need to use some thresholding on the images rather than blanket conversion, which could result in suboptimal images.

**Comment by evanosc** [comment]
Thank you! Is really installed with the problem, the server is compiled source installation, less libtesseract.so file, after the installation of the problem.
