### ISSUE TITLE
How to filter some characters

### ISSUE THREAD

**Issue by zshzj** [nguyenq/tess4j#49]
hello , i want filter some characters, How to do？
`instance.setTessVariable("tessedit_char_whitelist", "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");`

**Comment by nguyenq** [comment]
Yes, have you tried the code?

**Comment by zshzj** [comment]
@nguyenq  but this is whitelist , i want blocklist

**Comment by nguyenq** [comment]
`instance.setTessVariable("tessedit_char_blacklist", "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ");`

**Comment by zshzj** [comment]
@nguyenq  you tried the code?

**Comment by nguyenq** [comment]
To get better help, please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve). Also list your software development configuration.
