### ISSUE TITLE
Tess4j 3.3.0 in Windows and Tomcat - UnsatisfiedLinkError

### ISSUE THREAD

**Issue by delkant** [nguyenq/tess4j#50]
Hi I am having some issues after upgrading my app to tess4j 3.3.0. JNA wont find the dll no matter were I put them.

    java.lang.UnsatisfiedLinkError: The specified module could not be found.

	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:263)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
	at com.sun.jna.Library$Handler.<init>(Library.java:147)
	at com.sun.jna.Native.loadLibrary(Native.java:502)
	at com.sun.jna.Native.loadLibrary(Native.java:481)
	at net.sourceforge.tess4j.util.LoadLibs.getTessAPIInstance(LoadLibs.java:75)
	at net.sourceforge.tess4j.TessAPI.<clinit>(TessAPI.java:42)

I am using Windows 2012 R2 (64bit)
I have installed:
 - https://www.microsoft.com/en-us/download/details.aspx?id=48145
 - And also tried: http://tess4j.sourceforge.net/tutorial/
System.setProperty("jna.library.path", "32".equals(System.getProperty("sun.arch.data.model")) ? "lib/win32-x86" : "lib/win32-x86-64");
 - In my code I am using:
   
    `TessAPI api = TessAPI.INSTANCE;`

I was using tess4j 3.0.0 before without any problems. 

Is there any place where I can find more docs about how to point to the right location?

Do I need to install anything else? 

Thanks!

**Comment by delkant** [comment]
Debugging JNA with: 

System.setProperty("jna.debug_load", "true");
       
I got this:

`Looking in classpath from ParallelWebappClassLoader
  context: TessAPP
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@19469ea2
 for /com/sun/jna/win32-x86-64/jnidispatch.dll
Found library resource at jar:file:/C:/Java/apache-tomcat-8.5.11/webapps/TessAPP/WEB-INF/lib/jna-4.2.2.jar!/com/sun/jna/win32-x86-64/jnidispatch.dll
Looking for library 'libtesseract305'
Adding paths from jna.library.path: win32-x86-64;c:\Java\apache-tomcat-8.5.11\temp\tess4j\win32-x86-64
Trying c:\Java\apache-tomcat-8.5.11\win32-x86-64\libtesseract305.dll
Adding system paths: []
Trying c:\Java\apache-tomcat-8.5.11\win32-x86-64\libtesseract305.dll
Looking for lib- prefix
Trying liblibtesseract305.dll
Looking in classpath from ParallelWebappClassLoader
  context: TessAPP
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@19469ea2
 for libtesseract305
Found library resource at jar:file:/C:/Java/apache-tomcat-8.5.11/webapps/TessAPP/WEB-INF/lib/tess4j-3.3.0.jar!/win32-x86-64/libtesseract305.dll
`

**Comment by nguyenq** [comment]
Did you install the [Visual C++ 2015 x64 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=48145)? Be sure to reboot after install.

Can you test with a simple console app first before attempting it for the server environment?

**Comment by delkant** [comment]
Thank you for your time!

Yes, I installed:  Visual C++ 2015 x64 Redistributable and also I've restarted the server after that.

I could run tesseract from the console, I was using tesseract 3.04 and then I changed it to tesseract 4.00alpha to see if that makes any difference. But it looks like the problem was related to a environment variable because tesseract wasn't included correctly in the PATH (or it was there but not for the service). 

<img width="669" alt="screen shot 2017-03-07 at 10 17 23 pm" src="https://cloud.githubusercontent.com/assets/1325846/23688766/69dec3ec-0384-11e7-873a-4a4d50552d20.png">

After I verifying the PATH and restarting the server it started working.

So.. starting tess4j 3.3.0 it is a requirement to have a working installation of tesseract in the OS? I didn't need tesseract in the OS (besides the ddls) for tess4j 3.0.0.

Thank you again!.

**Comment by frankyrus** [comment]
I have the same problem after migrating from 3.3.1 to 3.4.0 in Maven project. How can I fix it?

**Comment by VirendraNaruka** [comment]
is that resolved .  I am having same issue with  Windows 2012 server  OS

**Comment by VirendraNaruka** [comment]
@frankyrus    Have you fixed at your end?  

I am facing same issue  did all efforts.  I am Using Windows Server 2012 as OS. I  Really Appreciates you reply and help

**Comment by frankyrus** [comment]
@VirendraNaruka No, I reassembled project on macOS instead of Windows and it works. I gave up attempts with Windows

**Comment by nguyenq** [comment]
Please try out the latest 4.00, which has just been released. It needs
VC++2017 runtime.
