### ISSUE TITLE
Tesseract 4.0.0

### ISSUE THREAD

**Issue by delkant** [nguyenq/tess4j#51]
Hello,

I have seem some comments in the code saying that ddls for Tesseract 4.0.0alpha were added. 
How can I do to build/test tess4j for/with Tesseract 4.0.0 (ideally on a windows machine)?.

Thanks.

**Comment by nguyenq** [comment]
Get the latest source from the trunk and execute `mvn test`.

**Comment by NookLook2014** [comment]
Tests in error: 
  testTessBaseAPIAnalyseLayout(net.sourceforge.tess4j.TessAPI1Test): cannot find the specified module

**Comment by jedisniper17** [comment]
Is it vc_dist is a must for Tesseract 4.0.0 dll? I found that it is a must for 3.0.5.

**Comment by nguyenq** [comment]
Yes, VC++ 2015 runtime is required since the DLL was compiled using VS2015.

**Comment by nguyenq** [comment]
`tess4j-4.0.0-SNAPSHOT.jar` is available from https://oss.sonatype.org/.
