### ISSUE TITLE
I cannot use the traineddata of chi_tra!

### ISSUE THREAD

**Issue by p0561199** [nguyenq/tess4j#52]
i can not use tess4j for traditional chinese
it will show something like these:

ParamsModel::Incomplete line ?覆G鋐蚆?鵿?蚇灸K濘????琨k戒??0'??接$(??洚^?"反?=I1芚錄蹍??&????-渶郈姾????
ParamsModel::Unknown parameter 渣c勤穌1f?滇?>鶷@b抰?,?p澦
ParamsModel::Incomplete line ?
ParamsModel::Incomplete line m??-蜺?沁??(??D牒鼣???CI]???:濿)陽??3c撙?鵡??<駤容???篴??!?"!x??O罊???褂剬?
ParamsModel::Incomplete line p??蕥}8抰@???矓T嬰???7JG????#q+??s齊/>=捫?43tF??k僱諗?"?(C敹w栭^埥醛??硨
ParamsModel::Incomplete line 吽鉌?T?2?覦D陲?徨響????0鏀湟蟫?XpSl蛾案^???6???3?7?U諼篛]??粲趑?/遛飂7篹?-髯?
ParamsModel::Incomplete line ??草)梲=i??W???筈Z棑諧KB?F灆?pk;?oS鏒-憎?C*m憀?GH??a}??j?>,馭恛磅???
ParamsModel::Incomplete line \捫g?8??E??7]t{??銧???輾@▼郿

**Comment by nguyenq** [comment]
What's your development environment -- OS, JDK, software version? And please post your code.

**Comment by nguyenq** [comment]
No response from OP.
