### ISSUE TITLE
can tess4j support  for linux

### ISSUE THREAD

**Issue by JackYangzg** [nguyenq/tess4j#54]
I want to develop a orc program on linux ubuntu, but I found the tess4j only support for windows;
My Question is that When the tess4j can support for linux or what can I do to support linux when using tess4j.

**Comment by joseblas** [comment]
I've used it in Mac and works fine.

**Comment by nguyenq** [comment]
Yes, it's stated on the [homepage](http://tess4j.sourceforge.net/usage.html).
