### ISSUE TITLE
mvn clean install -> Build failure

### ISSUE THREAD

**Issue by JaroslavHolan** [nguyenq/tess4j#55]
`Tests run: 102, Failures: 0, Errors: 99, Skipped: 2`

:-(

**Comment by nguyenq** [comment]
Unable to reproduce the issue. The command completed successfully against `master` branch from our end.

`Tests run: 64, Failures: 0, Errors: 0, Skipped: 2`

If you need assistance, you'll get to provide more relevant details about your s/w configuration.

**Comment by JaroslavHolan** [comment]
I'll send you log later. Try it on clean environment with empty .m2 directory.

**Comment by JaroslavHolan** [comment]
Here is the log https://gist.github.com/JaroslavHolan/e2831605014dc55fe26071ecdd0a18e2

**Comment by nguyenq** [comment]
Have you built and installed Tesseract from the [source](https://github.com/tesseract-ocr/tesseract)?

**Comment by JaroslavHolan** [comment]
No, I'll try it.
