### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by 4F2E4A2E** [nguyenq/tess4j#6]
System.out should be consequently replaced by a logging implementation / framework of our choice. 
Imho sl4j and logback is the best out there for logging, see: http://logback.qos.ch/documentation.html

What do you think?

**Comment by nguyenq** [comment]
Either we use the built-in logging framework or we use log4j, which is what ghost4j is using.

**Comment by 4F2E4A2E** [comment]
I would not recommend the built-in solution. log4j and sl4j work pretty well together, see here an example: http://www.luyue.org/configure-slf4j-working-various-logging-frameworks/
If that's a go, i would refactor the project to use log4j together with sl4j.

**Comment by 4F2E4A2E** [comment]
To understand it better take a look at [1] or read the sl4j manual [2].
1: http://www.slf4j.org/images/concrete-bindings.png
2: http://www.slf4j.org/manual.html

**Comment by nguyenq** [comment]
We can consider it for 2.1.0.

Thanks.

**Comment by nguyenq** [comment]
OJ, please go ahead with integrating slf4j to the master branch. Thanks.

**Comment by 4F2E4A2E** [comment]
Yes, i will! Thanks ;)

**Comment by 4F2E4A2E** [comment]
The logging integration is done. All tests have passed.
It may be needed to format the layout (src/test/resources/logback-test.xml) and code to have a better logging experience fromo the unit tests output.

**Comment by nguyenq** [comment]
Thank you. I published a 3.0.0-SNAPSHOT as well.
