### ISSUE TITLE
How to use on Linux - Error load native library

### ISSUE THREAD

**Issue by at-tantv** [nguyenq/tess4j#61]
Ib Your Class Loadlibs.java 
I see define Native.register("libtesseract400");
In Windows it's ok
Show I user Linux It stop working.
Please help me

**Comment by nguyenq** [comment]
You need to use a version of Tess4J compatible with your Tesseract. If you build and install Tesseract 4.00alpha on Linux, it creates a `libtesseract400.so` file or soft link.

**Comment by at-tantv** [comment]
You can explain clearly for me ?
I added lib dll to project.
So, I dont need to install Tesseract 4.00alpha ????

**Comment by nguyenq** [comment]
DLL is for Windows. You will need to build and install Tesseract on your
Linux machine first and then use the Tess4J version compatible with that
version.

**Comment by at-tantv** [comment]
I cannot find 4.00alpha.
I installed version 3.0.3, But it not compatible with your tess4j .
Can you send for me link install for linux OS ?
Thank you very much !

**Comment by at-tantv** [comment]
I installed it.
And it run OK on Ubuntu.
And Now I install on CENTOS 6 .
hope it success.
Thank for your support !!!
https://medium.com/@lucas63/installing-tesseract-3-04-in-ubuntu-14-04-1dae8b748a32

**Comment by albertoandreottiATgmail** [comment]
Hi, @nguyenq why the .so (Linux) native library is not packed with the jar?
