### ISSUE TITLE
Publish tess4j 4.0.0-SNAPSHOT artifact with Tesseract 4.0?

### ISSUE THREAD

**Issue by winitzki** [nguyenq/tess4j#62]
hello,

it would be helpful if the 4.0.0-SNAPSHOT artifact of tess4j were published and available on Sonatype. I would like to test the new Tesseract functionality but the latest version of tess4j that I can use from Maven is 3.x. Would it be difficult and would it make sense to publish a 4.0 final artifact instead of snapshot? Thank you!

**Comment by nguyenq** [comment]
A 4.0.0-SNAPSHOT has been published. Tesseract 4.0.0 is still in Alpha development stage, and thus subject to lots of changes. We'd want to wait until it is released before publishing a 4.0.0 final.

**Comment by nguyenq** [comment]
Snapshots have been made available from https://oss.sonatype.org/.
