### ISSUE TITLE
System.DllNotFoundException : Failed to find library "libtesseract400.dll" for platform x86.

### ISSUE THREAD

**Issue by TurboCar** [nguyenq/tess4j#63]
@nguyenq :  May I know how to build libtesseract400.dll & liblept1742.dll on my desktop? I got libtesseract400.dll & liblept1742.dll on other project (charlesw/tesseract, it seems you provided these library in branch feature/321-tesseract-4, right?) but it always received System.DllNotFoundException : Failed to find library "libtesseract400.dll" for platform x86.

I checked my test environment: 
* Visual C++ 2015 is installed correctly for both x64 and x86 architectures
* The tesseract DLLs have been correctly installed into the expected path.
* x64-based processor

I doubt if it's related with the libtesseract400.dll itself ... much appreciate for any clues.  thanks!

**Comment by nguyenq** [comment]
The DLLs were built from https://github.com/charlesw/tesseract-vs2012 project after updating it with the latest source from https://github.com/tesseract-ocr/tesseract project.

I just re-ran the unit tests on feature/321-tesseract-4 branch with the projects' Platform target set to Any CPU, x86, or x64, and they all passed. I'm sure charlesw saw the same results when verifying and accepting the PR.

**Comment by TurboCar** [comment]
thanks!
