### ISSUE TITLE
UnsatisfiedlinkError when using TessBaseAPICreate

### ISSUE THREAD

**Issue by shawnchen8255** [nguyenq/tess4j#64]
I am trying to create the TessBaseAPI using TessAPI1.TessBaseAPICreate() and met the error as below
java.lang.UnsatisfiedLinkError: Error looking up function 'TessPDFRendererCreateTextonly': dlsym(0x7fc93f349590, TessPDFRendererCreateTextonly): symbol not found

	at com.sun.jna.Function.<init>(Function.java:212)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:541)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:518)
	at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:504)
	at com.sun.jna.Native.register(Native.java:1655)
	at com.sun.jna.Native.register(Native.java:1529)
	at com.sun.jna.Native.register(Native.java:1252)
	at net.sourceforge.tess4j.TessAPI1.<clinit>(TessAPI1.java:41)
	at com.mail.service.Tess4jServiceImpl.<init>(Tess4jServiceImpl.java:23)

My code is as below
```
public class Tess4jServiceImpl {
    private String imageFilePath;
    private TessAPI1.TessBaseAPI tessBaseAPI;

    private static String tessDataPath = "***/tessdata/";
    public Tess4jServiceImpl(String imageFilePath) {
        this.imageFilePath = imageFilePath;
        tessBaseAPI = TessAPI1.TessBaseAPICreate();
    }
}
```

I have excluded com.sun.jna in the dependency of net.sourceforge.tess4j and added new jna dependency as 
<dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>4.2.1</version>
        </dependency>

Is there anything special i have to notice for this issue?
Thanks.

**Comment by nguyenq** [comment]
Looks like a compatibility issue. What's your version of Tess4J and Tesseract?

**Comment by shawnchen8255** [comment]
Fixed now.
I am using tesseract 4.0 and tess4j 3.4.0,got the compatibility error.
Updated to 4.0.0-snapshot and got fixed.

But for other language data like Chinese if I initialize it as 
TessAPI1.TessBaseAPIInit3(tessBaseAPI,tessDataPath,"chi_sim");
I always got the error as 
lstm_recognizer_->Load(lstm_use_matrix ? language : nullptr, mgr):Error:Assert failed:in file tessedit.cpp, line 194

For tessdata path i set it to the path set in tesseract.
If i set the path to a invalid one there will be no error in this step.
But will got another issue when getting text
The whole code is as below.

Pix pix = Leptonica1.pixRead(image.getPath());
        TessAPI1.TessBaseAPIInit3(tessBaseAPI,tessDataPath,"chi_sim");
        TessAPI1.TessBaseAPISetImage2(tessBaseAPI,pix);
        PointerByReference pixa = null;
        PointerByReference blockids = null;
        Boxa boxa = TessAPI1.TessBaseAPIGetComponentImages(tessBaseAPI, ITessAPI.TessPageIteratorLevel.RIL_TEXTLINE,1,pixa,blockids);
        int boxCount = Leptonica1.boxaGetCount(boxa);
        for(int i = 0;i<boxCount;i++){
            Box box = Leptonica1.boxaGetBox(boxa,i, ILeptonica.L_CLONE);
            TessAPI1.TessBaseAPISetRectangle(tessBaseAPI,box.x,box.y,box.w,box.h);
            **Pointer text = TessAPI1.TessBaseAPIGetUTF8Text(tessBaseAPI);**
            String t = text.getString(0);
            TessAPI1.TessDeleteText(text);
            int conf = TessAPI1.TessBaseAPIMeanTextConf(tessBaseAPI);
            LeptUtils.dispose(box);
        }
        LeptUtils.dispose(pix);
        LeptUtils.dispose(boxa);

I am not sure whether something is missing or not.

Thanks.

**Comment by nguyenq** [comment]
`tessDataPath` should be set to the parent directory of `tessdata`.

Do you have any problem with `eng` or other languages? I'm not sure how latest your `tess4j-4.0.0-snapshot.jar`, but you may want to try with the best traineddata files.

https://github.com/tesseract-ocr/tessdata/tree/master/best

**Comment by shawnchen8255** [comment]
Set it to the parent directory and got the same error.
If i set it to an invalid directory which does not exist the error disappeared but will get an error about the trained data not existed in this line
**Pointer text = TessAPI1.TessBaseAPIGetUTF8Text(tessBaseAPI);**

**Comment by nguyenq** [comment]
Which OS are you on? If Mac OSX, there have been issues reported against large `.traineddata` files. Do you a problem with loading `eng`?
