### ISSUE TITLE
extractTessResources will copy the files each time

### ISSUE THREAD

**Issue by StrimTechnologies** [nguyenq/tess4j#65]
extractTessResources will copy the files each time to tmp folder no matter if they are already there. Wouldn't it be better if we verify if the files exist, doing something like the following in LoadLibs.java ?

```
if (!targetPath.exists()) {
                    copyResources(resourceUrl, targetPath);
}
```

**Comment by nguyenq** [comment]
That way you will always get the current version of Tesseract binary.

**Comment by StrimTechnologies** [comment]
Yes, but in a production environment those files will change far less than the amount of times the OCR is ran and in parallel runs it might cause problems with overwriting the files.

**Comment by nguyenq** [comment]
That situation actually crossed my mind at times, especially when questions about multi-threading arose. Since file name changes in Tesseract and Leptonica usually accompany version changes, repeated file copying is no longer necessary. We will incorporate your suggestion in the next release.

Thank you.

**Comment by nguyenq** [comment]
@StrimTechnologies Can you verify whether the fix https://github.com/nguyenq/tess4j/commit/3244104d22de537c2032f6086387bfaa3b360d4c works for you?

Thanks.

**Comment by StrimTechnologies** [comment]
It's perfect, thanks for adding the file size check, too!

**Comment by StrimTechnologies** [comment]
Sorry to come back on this. 
The issue is OK for when the libraries are extracted from the jar/war but when they are on a nix system and copied from the common lib folder they still get replaced.
