### ISSUE TITLE
How to deal with multi page images through tess4j

### ISSUE THREAD

**Issue by shawnchen8255** [nguyenq/tess4j#66]
I am using tess4j 4.0.0 to process the image and pdf files.
For multiple page files if i use TessBaseAPIGetComponentImages(), all the boxa from all the pages will be returned,right?
If so how can i distinguish the boxes from different pages?

Also if I use TessBaseAPISetRectangle() and TessBaseAPIGetUTF8Text() how can i know the page number for the returned text?

Thanks!

**Comment by nguyenq** [comment]
Please RTM or post on Tesseract board for related questions. Those methods are believed to operate on individual images. As such, you would need to track the pages yourself.

http://tess4j.sourceforge.net/docs/
https://groups.google.com/forum/#!forum/tesseract-ocr
