### ISSUE TITLE
GetWords can not get right BoundingBox().x and BoundingBox().y

### ISSUE THREAD

**Issue by fjutxd** [nguyenq/tess4j#67]
for example 
char[x,y,height,widthg]getConfidence()
有[193.0,438.0,29.0,28.0]99.415886
没[223.0,437.0,28.0,51.0]98.77193
有[900.0,0.0,0.0,0.0]99.5725
让[290.0,437.0,28.0,46.0]99.56392
the third “有” between "没" and "让",but BoundingBox().x is 900, BoundingBox().y is 0; use LSTM by Tess4j 4.0

**Comment by nguyenq** [comment]
The data came from Tesseract engine. As such, I would suggest you to put in a ticket with them.

https://github.com/tesseract-ocr/tesseract/issues

**Comment by fjutxd** [comment]
thanks!
