### ISSUE TITLE
使用最新的Tess4j 总是报错 --> java.lang.UnsatisfiedLinkError: 找不到指定的模块。

### ISSUE THREAD

**Issue by BoolTrue** [nguyenq/tess4j#69]
看到最新的Tess4J使用了 libtesseract400.dll ，因为Tesseract 4.0的识别效果很好，所以想试一下 。
但是发现如下代码总是抛出异常：
```
public static void main(String[] args) {
	File imageFile = new File("src\\test\\resources\\test-data\\2.png");
	ITesseract instance = new Tesseract();
	instance.setLanguage("chi_sim");
	try {
		String result = instance.doOCR(imageFile);
		System.out.println(result);
	} catch (TesseractException e) {
		e.printStackTrace();
	}
}
```
请问该如何解决？ 

if you can't understand chinese please use [Google translate](https://translate.google.cn/) . Thanks

**Comment by BoolTrue** [comment]
code ：
`
public static void main(String[] args) {
	File imageFile = new File("src\\test\\resources\\test-data\\2.png");
	ITesseract instance = new Tesseract();
	instance.setLanguage("chi_sim");
	try {
		String result = instance.doOCR(imageFile);
		System.out.println(result);
	} catch (TesseractException e) {
		e.printStackTrace();
	}
}
`

**Comment by nguyenq** [comment]
What's your software configuration? You have VC++ 2015 runtime installed?

**Comment by BoolTrue** [comment]
我已经安装了VC ++ 2015 runtime。
是的我看到了三个DLL文件被释放到了  C:\Users\myName\AppData\Local\Temp\tess4j 文件夹。
我用的是  libtesseract400.dll ，从git上下载的。
但是，问题出在 加载 libtesseract400.dll 的时候 会抛出异常 ： java.lang.UnsatisfiedLinkError 。
我的开发环境：JDK 1.8 

I have installed VC ++ 2015 runtime installed .

Yes i saw three DLL files being released to the C: \ Users \ myName \ AppData \ Local \ Temp \ tess4j folder.
I use the libtesseract400.dll, downloaded from the lastest github.
However, the problems is when I  load 'libtesseract400.dll'  , eclipse always throw a Exception (java.lang.UnsatisfiedLinkError) .
However, the problem is when loading libtesseract400.dll will throw an exception: java.lang.UnsatisfiedLinkError.
My dev environment : JDK1.8 .

My English is not very good, please forgive me.

**Comment by xchz** [comment]
你在哪里看到使用Tesseract 4.0的？我反了released log没有使用Tesseract 4.0的啊？

**Comment by nguyenq** [comment]
Can you delete `C:\Users\myName\AppData\Local\Temp\tess4j` folder and try again?

Or use Maven if possible.

Solutions for `UnsatisfiedLinkError` exceptions have been posted by many other developers in https://sourceforge.net/p/tess4j/discussion/ and https://stackoverflow.com/tags/tess4j forums.

**Comment by xchz** [comment]
@nguyenq i have same problem...first,i use idea and maven on windows10,it's ok. So i copy the project to windows7, but throw that exception.....

**Comment by xchz** [comment]
i found the DLLs extracted to user's Temp folder,
code:
```
public static void main(String[] args) {
	File imageFile = new File("....x.png");
	ITesseract instance = new Tesseract();
	instance.setLanguage("chi_sim");
       instance.setDataPath("....");
	try {
		String result = instance.doOCR(imageFile);
		System.out.println(result);
	} catch (TesseractException e) {
		e.printStackTrace();
	}
}
```

**Comment by siyueshiqi** [comment]
@BoolTrue 你把项目clone下来，然后直接转成Maven项目，跑里面的junit test就行了，dll里面自带的，不用自己下载。

**Comment by BoolTrue** [comment]
@siyueshiqi  感谢，我立马去试试

**Comment by nguyenq** [comment]
Please try again with the latest versions.

**Comment by hejunmingstrogner** [comment]
楼主解决没有，我也遇到这个问题了，好烦人  ！！！咋搞定的 ？？？？？

**Comment by BoolTrue** [comment]
> 楼主解决没有，我也遇到这个问题了，好烦人 ！！！咋搞定的 ？？？？？

Please try again with the latest versions. 看上面的回答

**Comment by hejunmingstrogner** [comment]
我这里问题比较奇怪，我这里有另一个demo ，里面的代码也是用的同一个版本的 tess4j ，就正常执行，  在实际工程里面就是报错， 其它都是一样的。

**Comment by hejunmingstrogner** [comment]
这个是实际工程的 pom.xml 文件


<modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>PC-Tools</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>8</source>
                    <target>8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>net.sourceforge.tess4j</groupId>
            <artifactId>tess4j</artifactId>
            <version>3.0.0</version>
        </dependency>
    </dependencies>





















这里是demo 工程的pom.xml

    <groupId>org.example</groupId>
    <artifactId>tess4j</artifactId>
    <version>1.0-SNAPSHOT</version>
   <dependencies>
    <dependency>
        <groupId>net.sourceforge.tess4j</groupId>
        <artifactId>tess4j</artifactId>
        <version>3.2.1</version>
    </dependency>
   </dependencies>
