### ISSUE TITLE
tess4j slow and very heavy PDF generated

### ISSUE THREAD

**Issue by jmarmu** [nguyenq/tess4j#71]
It is a nice library, but in some cases is very very slow and the pdf generated is too big or heavy. For example, I apply OCR the attached document and I have the result 50 minutes later and a 70 megabytes PDF resultant. How can I fix this, please?
[ABOGACIA 2020_FINAL.pdf](https://github.com/nguyenq/tess4j/files/1382149/ABOGACIA.2020_FINAL.pdf)

**Comment by nguyenq** [comment]
Tess4J loads all the pages of the PDF file into memory. Thus if the PDF has a large number of pages, the performance will likely suffer. So we suggest that you break it up into smaller chunks of 20-25 pages, or even less.

Tess4J's PDF component converts input PDF to high-resolution images for maximum recognition rates; as a result, the OCR process on PDF likely takes longer to complete.

**Comment by jmarmu** [comment]
Thank you @nguyenq
