### ISSUE TITLE
tess4j4.0 linux runtime

### ISSUE THREAD

**Issue by IT-Glory** [nguyenq/tess4j#73]
hi nguyenq, I build a javaweb project with tess4j4.0, and then I run the project with last ubuntu16.04 version had compile & isntall Leptonica and Tesseract, and it work. But, when I run the project with CentOS7.2 had not  isntall Leptonica and Tesseract, and get a exception like this: java.lang.UnsatisfiedLinkError: Unable to load library 'tesseract': Native library (linux-x86-64/libtesseract.so)
    I remember I build project with tess4j3.4.0, and run it with CentOS7.2 don't isntall Tesseract, it work. Do you know what the problem is.

**Comment by IT-Glory** [comment]
I use tomcat8.5 as the app server

**Comment by nguyenq** [comment]
Of course, Tesseract has to be built or installed on Linux before the Java wrapper could work. You need to make sure `libtesseract.so` exists because Tess4J invokes it.
