### ISSUE TITLE
How to set a white list of characters to use getWords()

### ISSUE THREAD

**Issue by jyotikatuladhar** [nguyenq/tess4j#76]
getWords processes on finding UTF-8 text ->(TessResultIteratorGetUTF8Text(ri, pageIteratorLevel)).
But I want to use only the alphabets and few punctuation marks. Is there any way I can change or set the whitelist for the getWords() function?

**Comment by nguyenq** [comment]
You can use `setTessVariable` method for this.

**Comment by jyotikatuladhar** [comment]
I did try that, but the results came in UTF-8,it didn't alter the results.

**Comment by nguyenq** [comment]
Tess4.00alpha does not support it yet. What version are you running? And please post your code, if possible.

**Comment by jyotikatuladhar** [comment]
Yes, I am running version 4.00. The output of scala code below contains UTF-8 characters.

    val instance: ITesseract = new Tesseract
    instance.setDatapath("C:\\Users\\vostro\\workspace\\CardOCR\\tessdata-best")
    //    instance.setLanguage("eng")
    instance.setOcrEngineMode(3)
    instance.setPageSegMode(ITessAPI.TessPageSegMode.PSM_SPARSE_TEXT_OSD)
    instance.setTessVariable("tessedit_char_whitelist", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz:'/-")
    var words = Buffer.empty[Word]
    val im: BufferedImage = ImageIO.read(new File(file))
    try {
      words = instance.getWords(im, 3)
      //      words = instance.doOCR(im).split("[ \t\n]").toList
    } catch {
      case e: TesseractException => e.printStackTrace()
      case e: Exception          => e.printStackTrace()
    }

**Comment by nguyenq** [comment]
https://github.com/tesseract-ocr/tesseract/issues/751

**Comment by jyotikatuladhar** [comment]
Thank you.

**Comment by AbdelsalamHaa** [comment]
Hi , I'm using tesseract 4 with vs 2017 . i have used with English characters first , now i started to include arabic as well . the thing is got weird characters even when i change the eng.traineddata to ara.traineddata. 

i found out that it's the characters when the UTF8 code is treated as Hex code . 
![image](https://user-images.githubusercontent.com/35866217/39512903-1cb50738-4e25-11e8-8d0b-eba47c163d8b.png)
 this is the image i want to recognize . 
the result is 
![image](https://user-images.githubusercontent.com/35866217/39513059-9a6a2424-4e25-11e8-9bcd-2eb56d3437b6.png)
i convert the letters in arabic to  UTF8 code using this website
https://r12a.github.io/app-conversion/
 and when i take this code and converted as a hex code to character i get the same characters that tesseract showed me the first time.

**Comment by nguyenq** [comment]
@AbdelsalamHaa This ticket has been closed, and seems unrelated to yours. Please open a new issue.

Thanks.
