### ISSUE TITLE
error on centos7  "java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.Tesseract1"

### ISSUE THREAD

**Issue by andrew0213** [nguyenq/tess4j#77]
I installed tesseract of version 3.05.01 and lep of version 1.74.4 in my centos7 system, and it's ok to recognition images by shell command.   
I use tess4j of version 3.4.2 in my java code, and it runs ok in my local mac system. 
But, when i run my java service in the centos, I got the error message "java.lang.NoClassDefFoundError: Could not initialize class net.sourceforge.tess4j.Tesseract1".
I have no idea where i did wrong. Can anyone give my some advice?

**Comment by andrew0213** [comment]
I've solve this myself. I just set dataPath the wrong value.

**Comment by whoisalan** [comment]
i met the SAME problem as you did, but i don't know what do you mean by DATAPATH, can you give me some advice?
