### ISSUE TITLE
Question：Can tess4j be used for captcha recognition

### ISSUE THREAD

**Issue by xiaoyu1985ban** [nguyenq/tess4j#79]
![6477](https://user-images.githubusercontent.com/6438918/33935731-f2413266-e037-11e7-984c-82b23921bc4b.jpg)
Can tess4j recognize picture above directly ? 
If not, is there any suggestion? 
any advice would be appreciated;

**Comment by nguyenq** [comment]
AFAIK, none of current OCR engines can recognize captcha out of the box. You'll need to preprocess the images first -- and still, it may only work for relatively simple ones.
