### ISSUE TITLE
extractTessResources spinoff from #65

### ISSUE THREAD

**Issue by StrimTechnologies** [nguyenq/tess4j#80]
Sorry to come back on this. I was working on a linux system and I noticed that the same behavior is not applied.
The issue is OK for when the libraries are extracted from the jar/war but when they are on a nix system and copied from the common lib folder they still get replaced.

**Comment by nguyenq** [comment]
The Tesseract Linux binaries are not embedded in the .jar. What's the actual problem? Can you elaborate?

**Comment by StrimTechnologies** [comment]
In LoadLibs at line 140 you start an else that will copy all the libraries required by tess4j in a *nix system to the java.io.tmpdir\tess4j folder
These files get rewritten each time the application will run thus causing failures when running tess4j from different processes.
I think the same solution of checking the file size would fix this as well.

**Comment by nguyenq** [comment]
Just committed a fix ([b048a8e](https://github.com/nguyenq/tess4j/commit/b048a8e923c09131532fa11ddb90a606c4d3a7d6)). Can you help verify?

**Comment by StrimTechnologies** [comment]
Thank you!
I tested on an old version, using 3.4.3 and it's working perfectly.
Please include it in 4.0.0 as well.

**Comment by nguyenq** [comment]
Fixed by Release-3.4.3 (1d639bb).
