### ISSUE TITLE
java.lang.Error: Invalid memory access

### ISSUE THREAD

**Issue by Singhak** [nguyenq/tess4j#81]
As I am using the eng training dataset [Error-causing](https://github.com/tesseract-ocr/tessdata_best) Tessdata then tess4j says that Invalid memory access But I am using tessdata from here [Working testsdata](https://github.com/tesseract-ocr/tessdata) it is working fine. Is there is some difference in the tessdata in both link which I mention here

I am using Tess4j Version: 3.4.2

**Comment by nguyenq** [comment]
Those `tessdata_best` language packs are only compatible with Tesseract 4.0 -- hence Tess4J 4.0.
