### ISSUE TITLE
Failed loading language 'eng' Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by mmmoonie** [nguyenq/tess4j#82]
I clone tess4j from github, and run the test case: net.sourceforge.tess4j.TesseractTest.testDoOCR_File(), and then console will show me: "Failed loading language 'eng' Tesseract couldn't load any languages!"
my develop environment is Mac OS , java 8
![image](https://user-images.githubusercontent.com/17509860/35783594-d3bd9f14-0a44-11e8-95f3-219ab0aee829.png)
this is my tesseract installed by homebrew:
![image](https://user-images.githubusercontent.com/17509860/35783618-518b0792-0a45-11e8-9a84-fbf0dc86542d.png)

**Comment by nguyenq** [comment]
Make sure you `setDatapath` to parent of `tessdata` folder.

**Comment by mmmoonie** [comment]
![image](https://user-images.githubusercontent.com/17509860/35785298-696a5f42-0a5a-11e8-9dd8-46d890caeb0d.png)
yes , instance.setDatapath was called

**Comment by nguyenq** [comment]
Are you on `tess4j-3` branch? Open a command prompt and run: `mvn test`

**Comment by mmmoonie** [comment]
but ... one data what i trained use jTessBoxEditor , "tyc.traineddata" for example ,  i put it in tessdata folder , then run the test case : 
![image](https://user-images.githubusercontent.com/17509860/35790416-49f84d36-0a7d-11e8-82a9-1d1ddb57c32b.png)

**Comment by nguyenq** [comment]
The `master` branch is for Tesseract 4.00 development; as such, you'll need to build or install Tesseract 4.00alpha to be able to use it. On Windows, the appropriate shared libraries are already bundled in the package.

The error indicates Tesseract cannot find the specified data file. Make sure you set data path to the right location.

**Comment by mmmoonie** [comment]
As you can see from my screenshot ,  i just write a test case in class `TesseractTest` , other code is ok , and the data path is ok , but it does't work. The other data what i trained , like `number.traineddata` is ok , so i think something is wrong when i use jTessBoxEditor to train my data .  Now i will go to lean how to use jTessBoxEditor again. Thanks Very much!
