### ISSUE TITLE
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.

### ISSUE THREAD

**Issue by asdf5252** [nguyenq/tess4j#83]
Hello ,

I am facing the problem while using tess4j
```
java.lang.RuntimeException: Unsupported image format. May need to install JAI Image I/O package.
https://java.net/projects/jai-imageio/
at net.sourceforge.tess4j.util.ImageIOHelper.getIIOImageList(ImageIOHelper.java:408)
at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:224)
at net.sourceforge.tess4j.Tesseract.doOCR(Tesseract.java:208)
at com.purpose.all.Strip.c1.isScan(c1.java:113)
at com.purpose.all.Strip.c1.checkpdf(c1.java:155)
at com.purpose.all.Strip.c1.main(c1.java:39)
```

I have checked in two ways , first by using maven repository i.e
```
<!-- https://mvnrepository.com/artifact/com.github.jai-imageio/jai-imageio-core -->
<dependency>
    <groupId>com.github.jai-imageio</groupId>
    <artifactId>jai-imageio-core</artifactId>
    <version>1.3.1</version>
</dependency>
```
Secondly , I have also checked by including the jar i.e jai-imageio-core-1.3.1.jar

In both ways I am getting the same error , how can I fix this?

**Comment by asdf5252** [comment]
Issue solved.

**Comment by HugoRiggs** [comment]
@asdf5252 Could you tell me how the issue was solved, because I have the same issue.

**Comment by asdf5252** [comment]
Hello @HugoRiggs  You have to set the datapath for Tessdata if you are using tess4j in code , see the below code

```
public static final String datapath = "/home/grid/Downloads/Tess4J/tessdata";
instance.setDatapath (new File(datapath).getPath());
```

**Comment by nathaliegh** [comment]
@asdf5252  I trying to read an image using the same logic that's you suggest , and it's still return the same error , I'm  using java version 1.8 , os Centos 6 , and websphere server .

**Comment by vijayalangaram** [comment]
@asdf5252  same error for me  unable to resolve even after applied datapath. Is it possible to doocr on mongodb stored image

```
public static void main(String[] args) {
		SpringApplication.run(JavalocaldoocrApplication.class, args);		
		Mongo mongodb = new MongoClient("localhost", 27017);		
		DB db = mongodb.getDB("test-db");	
		DBCollection collection = db.getCollection("user");		
               **File image = new File("mongodb://localhost:27017//test-db//user");**	
	    Tesseract tessInst = new Tesseract();     	   
          //	    tessInst.setDatapath("C:\Program Files (x86)\Tesseract-OCR\tessdata");
	    final String datapath =  "C:\\Program Files (x86)\\Tesseract-OCR\\tessdata";	    		
	    tessInst.setDatapath (new File("datapath").getPath());   
	    try {
	          String result= tessInst.doOCR(image);
	          System.out.println(result);
	       } catch (TesseractException e) {
	          System.err.println(e.getMessage());
		 }		 }}
```
**It's Perfectly working for local image file and Is it possible for stored image in mongodb ?**
 
**got a errors regarding jar file and i was correctly added dependency nd jar cross checked with version also but unable to resolve.**

Can please guide me !!

**Comment by Nathiya-theScore** [comment]
@asdf5252 ,Can you please help me, what this means 'public static final String datapath = "/home/grid/Downloads/Tess4J/tessdata";'
what path should be going inside dataPath. I don't understand the above line.

**Comment by Selvam-N** [comment]
Hi @asdf5252 , I don't understand this 'public static final String datapath = "/home/grid/Downloads/Tess4J/tessdata";'. What goes in the dataPath. Am new to use this tess4j. Can you please help me.
