### ISSUE TITLE
Convert Scanned PDF or TIFF to a Searchable PDF

### ISSUE THREAD

**Issue by luizgustavogp** [nguyenq/tess4j#85]
Is possible to convert Scanned PDF to new Searchable PDF file using **tess4j**?
If yes, could please provide a sample or documentation?

**Comment by nguyenq** [comment]
Yes, it's possible. Check the unit test for example.

**Comment by nguyenq** [comment]
Get the source files, cd to its root directory, and execute either `mvn test` or `ant test` and check the results.

The [.NET wrapper](https://github.com/charlesw/tesseract) provides similar support for searchable PDF generation.
