### ISSUE TITLE
License incompatible with Ghostscripts AGPL

### ISSUE THREAD

**Issue by maherm** [nguyenq/tess4j#87]
tess4j bundles binaries from Ghostscript (gsdll32.dll & gsdll64.dll).
Ghostscript is distributed under the AGPL. With my limited understanding of the AGPL, I think that means that, if you distribute those binaries with tess4j, it actually has to be AGPL, too.  
This would also be true for every program that uses tess4j - if you use it in a closed source program, you are violating the Ghostscript License - maybe even without knowing it, because it is a transitive dependency of the Apache-Licensed tess4j-library. 

I think the same might apply for the pdfpagecount.ps script, which seems to be a derivate of several scripts shipped with GS - although one might argue that a script this short does not meet the threshold of originality for actually being copyrighted.

**Comment by nguyenq** [comment]
Thanks for bringing the license compatibility issue to our attention. It was not easy to fully understand all the free, open source licenses, but we thought they -- Apache and GPL v3 or AGPL -- were compatible. If they are indeed not (could you please cite a reference source for definitive clarity?), what may be the possible satisfactory solutions to this issue -- either change Tess4J's license to AGPL or remove the offending DLLs from the bundle?

**Comment by maherm** [comment]
First off: I'm by no means an expert for legal issues. I am a software developer. My understanding of software licenses is characterized by the policies of the companies I worked in and summaries of the licenses by people who understand this stuff.

This is the [TL;DL Legal summary of the AGPL ](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)) ( I highlighted the relevant part):

> The AGPL license differs from the other GNU licenses in that it was built for network software. You can distribute modified versions if you keep track of the changes and the date you made them. ***As per usual with GNU licenses, you must license derivatives under AGPL.*** It provides the same restrictions and freedoms as the GPLv3 but with an additional clause which makes it so that source code must be distributed along with web publication. Since web sites and services are never distributed in the traditional sense, the AGPL is the GPL of the web.

So the question is, what counts as a derivate of the GPL work? There are several threads on StackExchange about that issue, and you will find people arguing for either interpretation, e.g.: 

- [If I'm using a GPL 3 library in my project, can I license my project under MIT license?](https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l)
- [AGPL what you can do and what you can't](https://softwareengineering.stackexchange.com/questions/107883/agpl-what-you-can-do-and-what-you-cant)  

But on top of the AGPL, Ghostscript has [special licensing conditions for commercial products](https://www.ghostscript.com/doc/current/Commprod.htm) (highlighting by me):
> 1. Anyone may copy and distribute GPL Ghostscript (both source and object code), but they must distribute the source code as well as the object code (or, if they distribute only the object code, they must include an offer in writing to provide the source code at no more than reproduction cost), keep all copyright and other notices, and include the AGPL with the copies. (Note that this allows anyone receiving such a copy to distribute it freely as well.)
>
>2. Anyone may modify GPL Ghostscript, but the provisions of (1) apply to modified or derived works as well.
>
>**_Provision (2) effectively prevents the development of proprietary commercial products that incorporate GPL Ghostscript without a commercial license as a part, since these are "derived works" in the legal sense._**

Then it says 
> IF YOUR ENTIRE APPLICATION IS LICENSED TO THE PUBLIC UNDER EITHER THE AFPL OR THE GNU AGPL, YOU CAN DISTRIBUTE AFPL GHOSTSCRIPT OR GNU GHOSTSCRIPT, RESPECTIVELY, WITH YOUR APPLICATION WITHOUT A COMMERCIAL LICENSE . . .

I think this is the crucial part, because it clearly says you need to purchase a commercial license to distribute Ghostscript (or parts of it) if your work is not AGPL itself.

To resolve this issue, I see the two options you mentioned and an additional third one:
1. Making Tess4j AGPL
Changing the license might be the least effort for you, but it shifts the problem to the tess4j users. It would be practically unusable for most closed-source products, because nobody wants to purchase a GS license for $40k/annually just to use tess4j.
2. Removing the binaries from the jar
Since gs needs to be installed nevertheless to use those features, it should be doable to determine the location of the *.dlls at runtime.
3. Removing Ghostscript dependency entirely
There is a pull request (#60) that seems to remove the Ghostscript dependency entirely in favor of PDFBox. 

Since the PDFBox version seems to be significantly slower than GS, I think a combination of option 2 and 3 is the way to go:
- If ghostscript is installed, find the *.dlls and use GS
- Else, use the PDFBox conversion
This leaves the license untouched, and it seems that @robdrysdale already did a major part of the work.

Side note: unlike @robdrysdale, I don't think it is a problem that ghost4j is LGPL, because as of my understanding of the LGPL, it is totally okay to use a LGPL java library, as long as you distribute that libraries code with your application.

**Comment by nguyenq** [comment]
Thanks for the detailed response. The complexities of these licenses are a bit above my head, if not frightening. I, too, am a s/w developer, not a legal expert.

You've made excellent suggestions; we will go with option 2 & 3 combo and keep the original license for users' benefits. It just dawned on me that GS and PDFBox can work in tandem, like the way you described; it doesn't have to be outright replacement of GS.

The GS .dll and .ps files have been removed. We'll tell the users to download and install GS themselves. We'll take another close look at the PDFBox PR in the next few days before merging it into the baseline. A clean version should be released shortly after.

Again, thank you for all the invaluable input.

**Comment by nguyenq** [comment]
The change has been implemented. Please check it out.

Thanks.

**Comment by maherm** [comment]
Happy to hear that :+1: Thanks for your great work!

**Comment by nguyenq** [comment]
Fixed with Release [tess4j-3.4.5](https://github.com/nguyenq/tess4j/releases/tag/tess4j-3.4.5).
