### ISSUE TITLE
detect orientation fail if image path contains Chinese

### ISSUE THREAD

**Issue by pauljlchen** [nguyenq/tess4j#89]
I was failed to detect the image orientation if the image path contains Chinese with tess4j 4.0. 
The code is from the sample. Could you help and let me know how to deal with it? Thanks.

`Pix pix = Leptonica1.pixRead(**image.getPath()**);
TessAPI1.TessBaseAPISetImage2(handle, pix);

					 
IntBuffer orient_degB = IntBuffer.allocate(1);
FloatBuffer orient_confB = FloatBuffer.allocate(1);
PointerByReference script_nameB = new PointerByReference();
FloatBuffer script_confB = FloatBuffer.allocate(1);

int oriDetectResult = TessAPI1.TessBaseAPIDetectOrientationScript(handle, orient_degB, orient_confB, script_nameB, script_confB);`

Exception:
tess->pix_binary() != NULL:Error:Assert failed:in file ..\..\ccmain\osdetect.cpp, line 199
java.util.concurrent.ExecutionException: java.lang.Error: Invalid memory access
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)

**Comment by nguyenq** [comment]
Make sure the input image file exists by checking `imageFile.exists()`.

If that's truly a Java language issue with Chinese characters in folder or file names, then... you'll probably need to go to a Java-centric site for help. Try Java Forum or stackoverflow.com.

**Comment by nguyenq** [comment]
Duplicate of https://github.com/nguyenq/tess4j/issues/75.
