### ISSUE TITLE
ImageDeskew.getSkewAngle returns incorrect value in some cases

### ISSUE THREAD

**Issue by hoaknoppix** [nguyenq/tess4j#90]
It happens in my project when the document image is not correct such as containing fingers or the image quality is not so good. (The attached images here is just an example, in my project they are id cards or passports).

Please let me know the criteria to ensure getSkewAngle has a correct result. Thank you. 

Original Image:
![documentimage1524458532261](https://user-images.githubusercontent.com/7200050/39107430-50b1a400-46ec-11e8-8d5f-d6c7e1aeaa14.png)

After Deskew:
![deskewdocumentimage1524458532319](https://user-images.githubusercontent.com/7200050/39107429-50753fb0-46ec-11e8-92c2-3fcfa34867ce.png)

**Comment by nguyenq** [comment]
Having a clean and uncomplicated image would help.

You may also want to try the deskew methods offered by Leptonica library to see if it could produce better results.

http://www.leptonica.com/skew-measurement.html
https://tpgit.github.io/Leptonica/skew_8c.html
