### ISSUE TITLE
Tesseract 4 on RHEL 6 - undefined symbol: GOMP_parallel_start

### ISSUE THREAD

**Issue by NirHershkovitz** [nguyenq/tess4j#96]
Hi,

I've build leptonica 1.76.0 and Tesseract from master branch on Red Hat 6 and I'm getting 
java: symbol lookup error: /usr/local/lib/libtesseract.so: undefined symbol: GOMP_parallel_start

tess4j version 4.0.2.
When running Tesseract from the command line it works perfectly. I've tried it on Red Hat 7 using pre-compiled binaries and it works. Unfortunately, I need it to run on Red Had 6.

Any suggestions on how to troubleshot this?

**Comment by NirHershkovitz** [comment]
Thanks @nguyenq for this awesome help! I've recompiled with '--disable-openmp' and it works now.

**Comment by amitdo** [comment]
>That symbol seems to belong to OpenMP library, or libgomp, which I'm not sure how tesseract or leptonica depends on or interacts with.

Tesseract 4.0 indeed uses OpenMP, but Leptonica does not use it.

Use of OpenMP can be disabled at build time:
`./configure --disable-openmp `
 or at run time with an environment variable:
`OMP_THREAD_LIMIT=1 tesseract in.png out --oem 1`

**Comment by Kwei9** [comment]
Hello, I got the same problem. 
My tesseract is v4.1.1 and tess4j is v4.5.3.
Use disable OpenMP at build time, I failed to install.

After installed Leptonica, I download tesseract and do like this:
`# export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
# ./autogen.sh
# ./configure --disbale-openmp --prefix=/usr/local/ --with-extra-libraries=/usr/local/lib/
# make install` 

And I got:
`libtool: link: g++ -g -O2 -std=c++11 -o .libs/tesseract tesseract-tesseractmain.o  -L/usr/local/lib/ ./.libs/libtesseract.so -L/usr/local/lib /usr/local/lib/liblept.so
-lpng12 -ljpeg -ltiff -lm -lz -lrt -lpthread -Wl,-rpath -Wl,/usr/local/lib
./.libs/libtesseract.so: undefined reference to `omp_get_thread_num'
./.libs/libtesseract.so: undefined reference to `GOMP_sections_end_nowait'
./.libs/libtesseract.so: undefined reference to `omp_get_num_threads'
./.libs/libtesseract.so: undefined reference to `GOMP_parallel_start'
./.libs/libtesseract.so: undefined reference to `GOMP_parallel_end'
./.libs/libtesseract.so: undefined reference to `GOMP_sections_next'
./.libs/libtesseract.so: undefined reference to `GOMP_parallel_sections_start'
collect2: error: ld returned 1 exit status
make[2]: *** [tesseract] Error 1
make[2]: Leaving directory `/usr/src/tesseract-4.1.1/src/api'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/usr/src/tesseract-4.1.1'
make: *** [all] Error 2` 

could anyone help me? thx for your help😜

**Comment by nguyenq** [comment]
@Kwei9 Check you command syntax; it's `--disable-openmp`, not `--disbale-openmp`.

**Comment by Kwei9** [comment]
> @Kwei9 Check you command syntax; it's `--disable-openmp`, not `--disbale-openmp`.

Sorry for wrong spelling, but it's right in my command and  failed to install.
