### ISSUE TITLE
How to wrap all the required jar and dll in one tess4j jar

### ISSUE THREAD

**Issue by YongPengPeng** [nguyenq/tess4j#97]
Hi,

I want to use tess4j in my project, for some reason, I can't use maven to add dependency. 
I am wondering how can I use just one tess4j jar rather than 10+ jar in my project.
The 10+ jar are all the dependency tess4j needed, like lept4j, imageio,....
And how can I let others use my software without installing vc2015 first.

Thanks a lot.

**Comment by nguyenq** [comment]
I think there are ways to package all the JARs together -- you will have to look up the web for solutions.

VC++2015 is a hard dependency for Tesseract, Windows version.

**Comment by YongPengPeng** [comment]
Thanks for your reply, I will try it later.

**Comment by nguyenq** [comment]
I think this is what you're looking for packaging all in one:

https://maven.apache.org/plugins/maven-assembly-plugin/descriptor-refs.html
https://stackoverflow.com/questions/574594/how-can-i-create-an-executable-jar-with-dependencies-using-maven

**Comment by YongPengPeng** [comment]
Thanks a lot. I will try it.
