### ISSUE TITLE
i think tess4j can't recognize calculator font numbers

### ISSUE THREAD

**Issue by Alejandrorbp** [nguyenq/tess4j#98]
i think tess4j can't recognize calculator font numbers like above
![image](https://user-images.githubusercontent.com/29313952/41131199-1973f076-6a80-11e8-8486-0a4a24239cc5.png)

**Comment by Alejandrorbp** [comment]
or
![image](https://user-images.githubusercontent.com/29313952/41131313-b79d2e16-6a80-11e8-94a4-16d3181a3c70.png)

**Comment by nguyenq** [comment]
The question should be re-cast as: "Can Tesseract recognize calculator font numbers?"

Check out this issue: https://github.com/tesseract-ocr/langdata/issues/65

**Comment by nguyenq** [comment]
Not an issue.
